begin_unit
comment|'# Copyright (c) 2013 Rackspace Hosting'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Middleware that attaches a correlation id to WSGI request"""'
newline|'\n'
nl|'\n'
name|'import'
name|'uuid'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
op|'.'
name|'middleware'
name|'import'
name|'base'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
name|'import'
name|'versionutils'
newline|'\n'
nl|'\n'
nl|'\n'
op|'@'
name|'versionutils'
op|'.'
name|'deprecated'
op|'('
name|'as_of'
op|'='
name|'versionutils'
op|'.'
name|'deprecated'
op|'.'
name|'JUNO'
op|','
nl|'\n'
DECL|variable|in_favor_of
name|'in_favor_of'
op|'='
string|"'oslo.middleware.CorrelationId'"
op|')'
newline|'\n'
DECL|class|CorrelationIdMiddleware
name|'class'
name|'CorrelationIdMiddleware'
op|'('
name|'base'
op|'.'
name|'Middleware'
op|')'
op|':'
newline|'\n'
nl|'\n'
DECL|member|process_request
indent|'    '
name|'def'
name|'process_request'
op|'('
name|'self'
op|','
name|'req'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'correlation_id'
op|'='
op|'('
name|'req'
op|'.'
name|'headers'
op|'.'
name|'get'
op|'('
string|'"X_CORRELATION_ID"'
op|')'
name|'or'
nl|'\n'
name|'str'
op|'('
name|'uuid'
op|'.'
name|'uuid4'
op|'('
op|')'
op|')'
op|')'
newline|'\n'
name|'req'
op|'.'
name|'headers'
op|'['
string|"'X_CORRELATION_ID'"
op|']'
op|'='
name|'correlation_id'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
