begin_unit
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Compatibility shim for Kilo, while operators migrate to oslo.middleware."""'
newline|'\n'
nl|'\n'
name|'from'
name|'oslo_middleware'
name|'import'
name|'request_id'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
name|'import'
name|'versionutils'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|ENV_REQUEST_ID
name|'ENV_REQUEST_ID'
op|'='
string|"'openstack.request_id'"
newline|'\n'
DECL|variable|HTTP_RESP_HEADER_REQUEST_ID
name|'HTTP_RESP_HEADER_REQUEST_ID'
op|'='
string|"'x-openstack-request-id'"
newline|'\n'
nl|'\n'
nl|'\n'
op|'@'
name|'versionutils'
op|'.'
name|'deprecated'
op|'('
name|'as_of'
op|'='
name|'versionutils'
op|'.'
name|'deprecated'
op|'.'
name|'KILO'
op|','
nl|'\n'
DECL|variable|in_favor_of
name|'in_favor_of'
op|'='
string|"'oslo.middleware.RequestId'"
op|')'
newline|'\n'
DECL|class|RequestIdMiddleware
name|'class'
name|'RequestIdMiddleware'
op|'('
name|'request_id'
op|'.'
name|'RequestId'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'pass'
newline|'\n'
dedent|''
endmarker|''
end_unit
