begin_unit
comment|'# Copyright 2014 NEC Corporation.  All rights reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
DECL|variable|update
name|'update'
op|'='
op|'{'
nl|'\n'
string|"'type'"
op|':'
string|"'object'"
op|','
nl|'\n'
string|"'properties'"
op|':'
op|'{'
nl|'\n'
string|"'status'"
op|':'
op|'{'
nl|'\n'
string|"'type'"
op|':'
string|"'string'"
op|','
nl|'\n'
string|"'enum'"
op|':'
op|'['
string|"'enable'"
op|','
string|"'disable'"
op|','
nl|'\n'
string|"'Enable'"
op|','
string|"'Disable'"
op|','
nl|'\n'
string|"'ENABLE'"
op|','
string|"'DISABLE'"
op|']'
op|','
nl|'\n'
op|'}'
op|','
nl|'\n'
string|"'maintenance_mode'"
op|':'
op|'{'
nl|'\n'
string|"'type'"
op|':'
string|"'string'"
op|','
nl|'\n'
string|"'enum'"
op|':'
op|'['
string|"'enable'"
op|','
string|"'disable'"
op|','
nl|'\n'
string|"'Enable'"
op|','
string|"'Disable'"
op|','
nl|'\n'
string|"'ENABLE'"
op|','
string|"'DISABLE'"
op|']'
op|','
nl|'\n'
op|'}'
op|','
nl|'\n'
string|"'anyOf'"
op|':'
op|'['
nl|'\n'
op|'{'
string|"'required'"
op|':'
op|'['
string|"'status'"
op|']'
op|'}'
op|','
nl|'\n'
op|'{'
string|"'required'"
op|':'
op|'['
string|"'maintenance_mode'"
op|']'
op|'}'
nl|'\n'
op|']'
op|','
nl|'\n'
op|'}'
op|','
nl|'\n'
string|"'additionalProperties'"
op|':'
name|'False'
nl|'\n'
op|'}'
newline|'\n'
endmarker|''
end_unit
