begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 OpenStack LLC.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'utils'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|BaseImageService
name|'class'
name|'BaseImageService'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Base class for providing image search and retrieval services\n\n    ImageService exposes two concepts of metadata:\n\n        1. First-class attributes: This is metadata that is common to all\n           ImageService subclasses and is shared across all hypervisors. These\n           attributes are defined by IMAGE_ATTRS.\n\n        2. Properties: This is metdata that is specific to an ImageService,\n           and Image, or a particular hypervisor. Any attribute not present in\n           BASE_IMAGE_ATTRS should be considered an image property.\n\n    This means that ImageServices will return BASE_IMAGE_ATTRS as keys in the\n    metadata dict, all other attributes will be returned as keys in the nested\n    \'properties\' dict.\n    """'
newline|'\n'
DECL|variable|BASE_IMAGE_ATTRS
name|'BASE_IMAGE_ATTRS'
op|'='
op|'['
string|"'id'"
op|','
string|"'name'"
op|','
string|"'created_at'"
op|','
string|"'updated_at'"
op|','
nl|'\n'
string|"'deleted_at'"
op|','
string|"'deleted'"
op|','
string|"'status'"
op|','
string|"'is_public'"
op|']'
newline|'\n'
nl|'\n'
comment|'# NOTE(sirp): ImageService subclasses may override this to aid translation'
nl|'\n'
comment|'# between BaseImageService attributes and additional metadata stored by'
nl|'\n'
comment|'# the ImageService subclass'
nl|'\n'
DECL|variable|SERVICE_IMAGE_ATTRS
name|'SERVICE_IMAGE_ATTRS'
op|'='
op|'['
op|']'
newline|'\n'
nl|'\n'
op|'@'
name|'classmethod'
newline|'\n'
DECL|member|_translate_to_base
name|'def'
name|'_translate_to_base'
op|'('
name|'cls'
op|','
name|'metadata'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return a metadata dictionary that is BaseImageService compliant.\n\n        This is used by subclasses to expose only a metadata dictionary that\n        is the same across ImageService implementations.\n        """'
newline|'\n'
name|'return'
name|'cls'
op|'.'
name|'propertify_metadata'
op|'('
name|'metadata'
op|','
name|'cls'
op|'.'
name|'BASE_IMAGE_ATTRS'
op|')'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'classmethod'
newline|'\n'
DECL|member|_translate_to_service
name|'def'
name|'_translate_to_service'
op|'('
name|'cls'
op|','
name|'metadata'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return a metadata dictionary that is usable by the ImageService\n        subclass.\n\n        As an example, Glance has additional attributes (like \'location\'); the\n        BaseImageService considers these properties, but we need to translate\n        these back to first-class attrs for sending to Glance. This method\n        handles this by allowing you to specify the attributes an ImageService\n        considers first-class.\n        """'
newline|'\n'
name|'if'
name|'not'
name|'cls'
op|'.'
name|'SERVICE_IMAGE_ATTRS'
op|':'
newline|'\n'
indent|'            '
name|'raise'
name|'NotImplementedError'
op|'('
name|'_'
op|'('
string|'"Cannot use this without specifying "'
nl|'\n'
string|'"SERVICE_IMAGE_ATTRS for subclass"'
op|')'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'cls'
op|'.'
name|'propertify_metadata'
op|'('
name|'metadata'
op|','
name|'cls'
op|'.'
name|'SERVICE_IMAGE_ATTRS'
op|')'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'staticmethod'
newline|'\n'
DECL|member|propertify_metadata
name|'def'
name|'propertify_metadata'
op|'('
name|'metadata'
op|','
name|'keys'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return a dict with any unrecognized keys placed in the nested\n        \'properties\' dict.\n        """'
newline|'\n'
name|'flattened'
op|'='
name|'utils'
op|'.'
name|'flatten_dict'
op|'('
name|'metadata'
op|')'
newline|'\n'
name|'attributes'
op|','
name|'properties'
op|'='
name|'utils'
op|'.'
name|'partition_dict'
op|'('
name|'flattened'
op|','
name|'keys'
op|')'
newline|'\n'
name|'attributes'
op|'['
string|"'properties'"
op|']'
op|'='
name|'properties'
newline|'\n'
name|'return'
name|'attributes'
newline|'\n'
nl|'\n'
DECL|member|index
dedent|''
name|'def'
name|'index'
op|'('
name|'self'
op|','
name|'context'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Returns a sequence of mappings of id and name information about\n        images.\n\n        :rtype: array\n        :retval: a sequence of mappings with the following signature\n                    {\'id\': opaque id of image, \'name\': name of image}\n\n        """'
newline|'\n'
name|'raise'
name|'NotImplementedError'
newline|'\n'
nl|'\n'
DECL|member|detail
dedent|''
name|'def'
name|'detail'
op|'('
name|'self'
op|','
name|'context'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Returns a sequence of mappings of detailed information about images.\n\n        :rtype: array\n        :retval: a sequence of mappings with the following signature\n                    {\'id\': opaque id of image,\n                     \'name\': name of image,\n                     \'created_at\': creation timestamp,\n                     \'updated_at\': modification timestamp,\n                     \'deleted_at\': deletion timestamp or None,\n                     \'deleted\': boolean indicating if image has been deleted,\n                     \'status\': string description of image status,\n                     \'is_public\': boolean indicating if image is public\n                     }\n\n        If the service does not implement a method that provides a detailed\n        set of information about images, then the method should raise\n        NotImplementedError, in which case Nova will emulate this method\n        with repeated calls to show() for each image received from the\n        index() method.\n        """'
newline|'\n'
name|'raise'
name|'NotImplementedError'
newline|'\n'
nl|'\n'
DECL|member|show
dedent|''
name|'def'
name|'show'
op|'('
name|'self'
op|','
name|'context'
op|','
name|'image_id'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Returns a dict containing image metadata for the given opaque image id.\n\n        :retval a mapping with the following signature:\n\n            {\'id\': opaque id of image,\n             \'name\': name of image,\n             \'created_at\': creation timestamp,\n             \'updated_at\': modification timestamp,\n             \'deleted_at\': deletion timestamp or None,\n             \'deleted\': boolean indicating if image has been deleted,\n             \'status\': string description of image status,\n             \'is_public\': boolean indicating if image is public\n             }, ...\n\n        :raises NotFound if the image does not exist\n        """'
newline|'\n'
name|'raise'
name|'NotImplementedError'
newline|'\n'
nl|'\n'
DECL|member|get
dedent|''
name|'def'
name|'get'
op|'('
name|'self'
op|','
name|'context'
op|','
name|'data'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Returns a dict containing image metadata and writes image data to data.\n\n        :param data: a file-like object to hold binary image data\n\n        :raises NotFound if the image does not exist\n        """'
newline|'\n'
name|'raise'
name|'NotImplementedError'
newline|'\n'
nl|'\n'
DECL|member|create
dedent|''
name|'def'
name|'create'
op|'('
name|'self'
op|','
name|'context'
op|','
name|'metadata'
op|','
name|'data'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Store the image metadata and data and return the new image id.\n\n        :raises AlreadyExists if the image already exist.\n\n        """'
newline|'\n'
name|'raise'
name|'NotImplementedError'
newline|'\n'
nl|'\n'
DECL|member|update
dedent|''
name|'def'
name|'update'
op|'('
name|'self'
op|','
name|'context'
op|','
name|'image_id'
op|','
name|'metadata'
op|','
name|'data'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Update the given image with the new metadata and data.\n\n        :raises NotFound if the image does not exist.\n\n        """'
newline|'\n'
name|'raise'
name|'NotImplementedError'
newline|'\n'
nl|'\n'
DECL|member|delete
dedent|''
name|'def'
name|'delete'
op|'('
name|'self'
op|','
name|'context'
op|','
name|'image_id'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Delete the given image.\n\n        :raises NotFound if the image does not exist.\n\n        """'
newline|'\n'
name|'raise'
name|'NotImplementedError'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
