begin_unit
comment|'#!/usr/bin/env python'
nl|'\n'
comment|'# Copyright (c) 2013 Hewlett-Packard Development Company, L.P.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License");'
nl|'\n'
comment|'# you may not use this file except in compliance with the License.'
nl|'\n'
comment|'# You may obtain a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS,'
nl|'\n'
comment|'# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or'
nl|'\n'
comment|'# implied.'
nl|'\n'
comment|'# See the License for the specific language governing permissions and'
nl|'\n'
comment|'# limitations under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'setuptools'
newline|'\n'
nl|'\n'
name|'setuptools'
op|'.'
name|'setup'
op|'('
nl|'\n'
name|'setup_requires'
op|'='
op|'['
string|"'d2to1>=0.2.10,<0.3'"
op|','
string|"'pbr>=0.5,<0.6'"
op|']'
op|','
nl|'\n'
DECL|variable|d2to1
name|'d2to1'
op|'='
name|'True'
op|')'
newline|'\n'
endmarker|''
end_unit
