begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'# Copyright (c) 2010 Citrix Systems, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nThe built-in instance properties.\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'context'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'db'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'flags'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'exception'
newline|'\n'
nl|'\n'
DECL|variable|FLAGS
name|'FLAGS'
op|'='
name|'flags'
op|'.'
name|'FLAGS'
newline|'\n'
comment|'# FIXME(kpepple) for dynamic flavors'
nl|'\n'
comment|'# INSTANCE_TYPES = {'
nl|'\n'
comment|"#     'm1.tiny': dict(memory_mb=512, vcpus=1, local_gb=0, flavorid=1),"
nl|'\n'
comment|"#     'm1.small': dict(memory_mb=2048, vcpus=1, local_gb=20, flavorid=2),"
nl|'\n'
comment|"#     'm1.medium': dict(memory_mb=4096, vcpus=2, local_gb=40, flavorid=3),"
nl|'\n'
comment|"#     'm1.large': dict(memory_mb=8192, vcpus=4, local_gb=80, flavorid=4),"
nl|'\n'
comment|"#     'm1.xlarge': dict(memory_mb=16384, vcpus=8, local_gb=160, flavorid=5)}"
nl|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_all_types
name|'def'
name|'get_all_types'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""retrieves all instance_types"""'
newline|'\n'
name|'return'
name|'db'
op|'.'
name|'instance_type_get_all'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_all_flavors
dedent|''
name|'def'
name|'get_all_flavors'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""retrieves all flavors. alias for instance_types.get_all_types()"""'
newline|'\n'
name|'return'
name|'get_all_types'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_by_type
dedent|''
name|'def'
name|'get_by_type'
op|'('
name|'instance_type'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""retrieve instance_type details"""'
newline|'\n'
comment|'# FIXME(kpepple) for dynamic flavors'
nl|'\n'
name|'if'
name|'instance_type'
name|'is'
name|'None'
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'FLAGS'
op|'.'
name|'default_instance_type'
newline|'\n'
dedent|''
name|'try'
op|':'
newline|'\n'
indent|'        '
name|'ctxt'
op|'='
name|'context'
op|'.'
name|'get_admin_context'
op|'('
op|')'
newline|'\n'
name|'inst_type'
op|'='
name|'db'
op|'.'
name|'instance_type_get_by_name'
op|'('
name|'ctxt'
op|','
name|'instance_type'
op|')'
newline|'\n'
dedent|''
name|'except'
name|'Exception'
op|','
name|'e'
op|':'
newline|'\n'
indent|'        '
name|'print'
name|'e'
newline|'\n'
name|'raise'
name|'exception'
op|'.'
name|'ApiError'
op|'('
name|'_'
op|'('
string|'"Unknown instance type: %s"'
op|')'
op|','
nl|'\n'
name|'instance_type'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'inst_type'
op|'['
string|"'name'"
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_by_flavor_id
dedent|''
name|'def'
name|'get_by_flavor_id'
op|'('
name|'flavor_id'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""retrieve instance_type\'s name by flavor_id"""'
newline|'\n'
name|'if'
name|'flavor_id'
name|'is'
name|'None'
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'FLAGS'
op|'.'
name|'default_instance_type'
newline|'\n'
dedent|''
name|'try'
op|':'
newline|'\n'
indent|'        '
name|'ctxt'
op|'='
name|'context'
op|'.'
name|'get_admin_context'
op|'('
op|')'
newline|'\n'
name|'flavor'
op|'='
name|'db'
op|'.'
name|'instance_type_get_by_flavor_id'
op|'('
name|'ctxt'
op|','
name|'flavor_id'
op|')'
newline|'\n'
dedent|''
name|'except'
name|'Exception'
op|','
name|'e'
op|':'
newline|'\n'
indent|'        '
name|'raise'
name|'exception'
op|'.'
name|'ApiError'
op|'('
name|'_'
op|'('
string|'"Unknown flavor: %s"'
op|')'
op|','
nl|'\n'
name|'flavor_id'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'flavor'
op|'['
string|"'name'"
op|']'
newline|'\n'
dedent|''
endmarker|''
end_unit
