begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 OpenStack LLC.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Possible task states for instances.\n\nCompute instance task states represent what is happening to the instance at the\ncurrent moment. These tasks can be generic, such as \'spawning\', or specific,\nsuch as \'block_device_mapping\'. These task states allow for a better view into\nwhat an instance is doing and should be displayed to users/administrators as\nnecessary.\n\n"""'
newline|'\n'
nl|'\n'
DECL|variable|SCHEDULING
name|'SCHEDULING'
op|'='
string|"'scheduling'"
newline|'\n'
DECL|variable|BLOCK_DEVICE_MAPPING
name|'BLOCK_DEVICE_MAPPING'
op|'='
string|"'block_device_mapping'"
newline|'\n'
DECL|variable|NETWORKING
name|'NETWORKING'
op|'='
string|"'networking'"
newline|'\n'
DECL|variable|SPAWNING
name|'SPAWNING'
op|'='
string|"'spawning'"
newline|'\n'
nl|'\n'
DECL|variable|IMAGE_SNAPSHOT
name|'IMAGE_SNAPSHOT'
op|'='
string|"'image_snapshot'"
newline|'\n'
DECL|variable|IMAGE_BACKUP
name|'IMAGE_BACKUP'
op|'='
string|"'image_backup'"
newline|'\n'
nl|'\n'
DECL|variable|UPDATING_PASSWORD
name|'UPDATING_PASSWORD'
op|'='
string|"'updating_password'"
newline|'\n'
nl|'\n'
DECL|variable|RESIZE_PREP
name|'RESIZE_PREP'
op|'='
string|"'resize_prep'"
newline|'\n'
DECL|variable|RESIZE_MIGRATING
name|'RESIZE_MIGRATING'
op|'='
string|"'resize_migrating'"
newline|'\n'
DECL|variable|RESIZE_MIGRATED
name|'RESIZE_MIGRATED'
op|'='
string|"'resize_migrated'"
newline|'\n'
DECL|variable|RESIZE_FINISH
name|'RESIZE_FINISH'
op|'='
string|"'resize_finish'"
newline|'\n'
DECL|variable|RESIZE_REVERTING
name|'RESIZE_REVERTING'
op|'='
string|"'resize_reverting'"
newline|'\n'
DECL|variable|RESIZE_CONFIRMING
name|'RESIZE_CONFIRMING'
op|'='
string|"'resize_confirming'"
newline|'\n'
DECL|variable|RESIZE_VERIFY
name|'RESIZE_VERIFY'
op|'='
string|"'resize_verify'"
newline|'\n'
nl|'\n'
DECL|variable|REBUILDING
name|'REBUILDING'
op|'='
string|"'rebuilding'"
newline|'\n'
nl|'\n'
DECL|variable|REBOOTING
name|'REBOOTING'
op|'='
string|"'rebooting'"
newline|'\n'
DECL|variable|REBOOTING_HARD
name|'REBOOTING_HARD'
op|'='
string|"'rebooting_hard'"
newline|'\n'
DECL|variable|PAUSING
name|'PAUSING'
op|'='
string|"'pausing'"
newline|'\n'
DECL|variable|UNPAUSING
name|'UNPAUSING'
op|'='
string|"'unpausing'"
newline|'\n'
DECL|variable|SUSPENDING
name|'SUSPENDING'
op|'='
string|"'suspending'"
newline|'\n'
DECL|variable|RESUMING
name|'RESUMING'
op|'='
string|"'resuming'"
newline|'\n'
DECL|variable|POWERING_OFF
name|'POWERING_OFF'
op|'='
string|"'powering-off'"
newline|'\n'
DECL|variable|POWERING_ON
name|'POWERING_ON'
op|'='
string|"'powering-on'"
newline|'\n'
nl|'\n'
DECL|variable|RESCUING
name|'RESCUING'
op|'='
string|"'rescuing'"
newline|'\n'
DECL|variable|UNRESCUING
name|'UNRESCUING'
op|'='
string|"'unrescuing'"
newline|'\n'
nl|'\n'
DECL|variable|DELETING
name|'DELETING'
op|'='
string|"'deleting'"
newline|'\n'
DECL|variable|STOPPING
name|'STOPPING'
op|'='
string|"'stopping'"
newline|'\n'
DECL|variable|STARTING
name|'STARTING'
op|'='
string|"'starting'"
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_list
name|'def'
name|'get_list'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Returns a list of all the possible task_states"""'
newline|'\n'
name|'return'
op|'['
name|'SCHEDULING'
op|','
name|'BLOCK_DEVICE_MAPPING'
op|','
name|'NETWORKING'
op|','
name|'SPAWNING'
op|','
nl|'\n'
name|'IMAGE_SNAPSHOT'
op|','
name|'IMAGE_BACKUP'
op|','
name|'UPDATING_PASSWORD'
op|','
name|'RESIZE_PREP'
op|','
nl|'\n'
name|'RESIZE_MIGRATING'
op|','
name|'RESIZE_MIGRATED'
op|','
name|'RESIZE_FINISH'
op|','
name|'RESIZE_REVERTING'
op|','
nl|'\n'
name|'RESIZE_CONFIRMING'
op|','
name|'RESIZE_VERIFY'
op|','
name|'REBUILDING'
op|','
name|'REBOOTING'
op|','
nl|'\n'
name|'REBOOTING_HARD'
op|','
name|'PAUSING'
op|','
name|'UNPAUSING'
op|','
name|'SUSPENDING'
op|','
name|'RESUMING'
op|','
nl|'\n'
name|'POWERING_OFF'
op|','
name|'POWERING_ON'
op|','
name|'RESCUING'
op|','
name|'UNRESCUING'
op|','
name|'DELETING'
op|','
nl|'\n'
name|'STOPPING'
op|','
name|'STARTING'
op|']'
newline|'\n'
dedent|''
endmarker|''
end_unit
