begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2012 Cloudbase Solutions Srl'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nUtility class to ease the task of creating stubs of built in IO functions.\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'__builtin__'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|open
name|'def'
name|'open'
op|'('
name|'name'
op|','
name|'mode'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'__builtin__'
op|'.'
name|'open'
op|'('
name|'name'
op|','
name|'mode'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
