begin_unit
comment|'# Copyright 2013 Cloudbase Solutions Srl'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|class|RDPConsoleUtils
name|'class'
name|'RDPConsoleUtils'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
DECL|variable|_DEFAULT_HYPERV_RDP_PORT
indent|'    '
name|'_DEFAULT_HYPERV_RDP_PORT'
op|'='
number|'2179'
newline|'\n'
nl|'\n'
DECL|member|get_rdp_console_port
name|'def'
name|'get_rdp_console_port'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'self'
op|'.'
name|'_DEFAULT_HYPERV_RDP_PORT'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
