begin_unit
comment|'# Copyright 2011 OpenStack Foundation'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'api'
op|'.'
name|'openstack'
op|'.'
name|'compute'
op|'.'
name|'schemas'
name|'import'
name|'scheduler_hints'
name|'as'
name|'schema'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'api'
op|'.'
name|'openstack'
name|'import'
name|'extensions'
newline|'\n'
nl|'\n'
DECL|variable|ALIAS
name|'ALIAS'
op|'='
string|'"os-scheduler-hints"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SchedulerHints
name|'class'
name|'SchedulerHints'
op|'('
name|'extensions'
op|'.'
name|'V3APIExtensionBase'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Pass arbitrary key/value pairs to the scheduler."""'
newline|'\n'
nl|'\n'
DECL|variable|name
name|'name'
op|'='
string|'"SchedulerHints"'
newline|'\n'
DECL|variable|alias
name|'alias'
op|'='
name|'ALIAS'
newline|'\n'
DECL|variable|version
name|'version'
op|'='
number|'1'
newline|'\n'
nl|'\n'
DECL|member|get_controller_extensions
name|'def'
name|'get_controller_extensions'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
op|'['
op|']'
newline|'\n'
nl|'\n'
DECL|member|get_resources
dedent|''
name|'def'
name|'get_resources'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
op|'['
op|']'
newline|'\n'
nl|'\n'
comment|'# NOTE(gmann): Accepting request body in this function to fetch "scheduler'
nl|'\n'
comment|'# hint". This is a workaround to allow OS_SCH-HNT at the top level'
nl|'\n'
comment|'# of the body request, but that it will be changed in the future to be a'
nl|'\n'
comment|'# subset of the servers dict.'
nl|'\n'
DECL|member|server_create
dedent|''
name|'def'
name|'server_create'
op|'('
name|'self'
op|','
name|'server_dict'
op|','
name|'create_kwargs'
op|','
name|'req_body'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'scheduler_hints'
op|'='
op|'{'
op|'}'
newline|'\n'
name|'if'
string|"'os:scheduler_hints'"
name|'in'
name|'req_body'
op|':'
newline|'\n'
indent|'            '
name|'scheduler_hints'
op|'='
name|'req_body'
op|'['
string|"'os:scheduler_hints'"
op|']'
newline|'\n'
dedent|''
name|'elif'
string|"'OS-SCH-HNT:scheduler_hints'"
name|'in'
name|'req_body'
op|':'
newline|'\n'
indent|'            '
name|'scheduler_hints'
op|'='
name|'req_body'
op|'['
string|"'OS-SCH-HNT:scheduler_hints'"
op|']'
newline|'\n'
nl|'\n'
dedent|''
name|'create_kwargs'
op|'['
string|"'scheduler_hints'"
op|']'
op|'='
name|'scheduler_hints'
newline|'\n'
nl|'\n'
DECL|member|get_server_create_schema
dedent|''
name|'def'
name|'get_server_create_schema'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'schema'
op|'.'
name|'server_create'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
