begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2010 Openstack, LLC.'
nl|'\n'
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nSimple Scheduler\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'db'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'flags'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'scheduler'
name|'import'
name|'driver'
newline|'\n'
nl|'\n'
DECL|variable|FLAGS
name|'FLAGS'
op|'='
name|'flags'
op|'.'
name|'FLAGS'
newline|'\n'
name|'flags'
op|'.'
name|'DEFINE_integer'
op|'('
string|'"max_instances"'
op|','
number|'16'
op|','
nl|'\n'
string|'"maximum number of instances to allow per host"'
op|')'
newline|'\n'
name|'flags'
op|'.'
name|'DEFINE_integer'
op|'('
string|'"max_volumes"'
op|','
number|'100'
op|','
nl|'\n'
string|'"maximum number of volumes to allow per host"'
op|')'
newline|'\n'
name|'flags'
op|'.'
name|'DEFINE_integer'
op|'('
string|'"max_networks"'
op|','
number|'1000'
op|','
nl|'\n'
string|'"maximum number of networks to allow per host"'
op|')'
newline|'\n'
nl|'\n'
DECL|class|SimpleScheduler
name|'class'
name|'SimpleScheduler'
op|'('
name|'driver'
op|'.'
name|'Scheduler'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""\n    Implements Naive Scheduler that tries to find least loaded host\n    """'
newline|'\n'
nl|'\n'
DECL|member|pick_compute_host
name|'def'
name|'pick_compute_host'
op|'('
name|'self'
op|','
name|'context'
op|','
name|'instance_id'
op|','
op|'**'
name|'_kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Picks a host that is up and has the fewest running instances\n        """'
newline|'\n'
nl|'\n'
name|'results'
op|'='
name|'db'
op|'.'
name|'daemon_get_all_compute_sorted'
op|'('
name|'context'
op|')'
newline|'\n'
name|'for'
name|'result'
name|'in'
name|'results'
op|':'
newline|'\n'
indent|'            '
op|'('
name|'daemon'
op|','
name|'instance_count'
op|')'
op|'='
name|'result'
newline|'\n'
name|'if'
name|'instance_count'
op|'>='
name|'FLAGS'
op|'.'
name|'max_instances'
op|':'
newline|'\n'
indent|'                '
name|'raise'
name|'driver'
op|'.'
name|'NoValidHost'
op|'('
string|'"All hosts have too many instances"'
op|')'
newline|'\n'
dedent|''
name|'if'
name|'self'
op|'.'
name|'daemon_is_up'
op|'('
name|'daemon'
op|')'
op|':'
newline|'\n'
indent|'                '
name|'return'
name|'daemon'
op|'['
string|"'host'"
op|']'
newline|'\n'
dedent|''
dedent|''
name|'raise'
name|'driver'
op|'.'
name|'NoValidHost'
op|'('
string|'"No hosts found"'
op|')'
newline|'\n'
nl|'\n'
DECL|member|pick_volume_host
dedent|''
name|'def'
name|'pick_volume_host'
op|'('
name|'self'
op|','
name|'context'
op|','
name|'volume_id'
op|','
op|'**'
name|'_kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Picks a host that is up and has the fewest volumes\n        """'
newline|'\n'
nl|'\n'
name|'results'
op|'='
name|'db'
op|'.'
name|'daemon_get_all_volume_sorted'
op|'('
name|'context'
op|')'
newline|'\n'
name|'for'
name|'result'
name|'in'
name|'results'
op|':'
newline|'\n'
indent|'            '
op|'('
name|'daemon'
op|','
name|'instance_count'
op|')'
op|'='
name|'result'
newline|'\n'
name|'if'
name|'instance_count'
op|'>='
name|'FLAGS'
op|'.'
name|'max_volumes'
op|':'
newline|'\n'
indent|'                '
name|'raise'
name|'driver'
op|'.'
name|'NoValidHost'
op|'('
string|'"All hosts have too many volumes"'
op|')'
newline|'\n'
dedent|''
name|'if'
name|'self'
op|'.'
name|'daemon_is_up'
op|'('
name|'daemon'
op|')'
op|':'
newline|'\n'
indent|'                '
name|'return'
name|'daemon'
op|'['
string|"'host'"
op|']'
newline|'\n'
dedent|''
dedent|''
name|'raise'
name|'driver'
op|'.'
name|'NoValidHost'
op|'('
string|'"No hosts found"'
op|')'
newline|'\n'
nl|'\n'
DECL|member|pick_network_host
dedent|''
name|'def'
name|'pick_network_host'
op|'('
name|'self'
op|','
name|'context'
op|','
name|'network_id'
op|','
op|'**'
name|'_kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Picks a host that is up and has the fewest networks\n        """'
newline|'\n'
nl|'\n'
name|'results'
op|'='
name|'db'
op|'.'
name|'daemon_get_all_network_sorted'
op|'('
name|'context'
op|')'
newline|'\n'
name|'for'
name|'result'
name|'in'
name|'results'
op|':'
newline|'\n'
indent|'            '
op|'('
name|'daemon'
op|','
name|'instance_count'
op|')'
op|'='
name|'result'
newline|'\n'
name|'if'
name|'instance_count'
op|'>='
name|'FLAGS'
op|'.'
name|'max_networks'
op|':'
newline|'\n'
indent|'                '
name|'raise'
name|'driver'
op|'.'
name|'NoValidHost'
op|'('
string|'"All hosts have too many networks"'
op|')'
newline|'\n'
dedent|''
name|'if'
name|'self'
op|'.'
name|'daemon_is_up'
op|'('
name|'daemon'
op|')'
op|':'
newline|'\n'
indent|'                '
name|'return'
name|'daemon'
op|'['
string|"'host'"
op|']'
newline|'\n'
dedent|''
dedent|''
name|'raise'
name|'driver'
op|'.'
name|'NoValidHost'
op|'('
string|'"No hosts found"'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
