begin_unit
comment|'#    Copyright 2013 IBM Corp.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|function|register_all
name|'def'
name|'register_all'
op|'('
op|')'
op|':'
newline|'\n'
comment|'# NOTE(danms): You must make sure your object gets imported in this'
nl|'\n'
comment|'# function in order for it to be registered by services that may'
nl|'\n'
comment|'# need to receive it via RPC.'
nl|'\n'
indent|'    '
name|'__import__'
op|'('
string|"'nova.objects.instance'"
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
