begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
comment|'# Copyright 2012 Nebula, Inc.'
nl|'\n'
comment|'# Copyright 2013 IBM Corp.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo'
op|'.'
name|'config'
name|'import'
name|'cfg'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'compute'
name|'import'
name|'vm_states'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'tests'
op|'.'
name|'integrated'
op|'.'
name|'v3'
name|'import'
name|'test_servers'
newline|'\n'
nl|'\n'
DECL|variable|CONF
name|'CONF'
op|'='
name|'cfg'
op|'.'
name|'CONF'
newline|'\n'
name|'CONF'
op|'.'
name|'import_opt'
op|'('
string|"'osapi_hide_server_address_states'"
op|','
nl|'\n'
string|"'nova.api.openstack.compute.plugins.v3.hide_server_addresses'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ServersSampleHideAddressesJsonTest
name|'class'
name|'ServersSampleHideAddressesJsonTest'
op|'('
name|'test_servers'
op|'.'
name|'ServersSampleJsonTest'
op|')'
op|':'
newline|'\n'
DECL|variable|extension_name
indent|'    '
name|'extension_name'
op|'='
string|"'os-hide-server-addresses'"
newline|'\n'
comment|'# Override the sample dirname because'
nl|'\n'
comment|"# test_servers.ServersSampleJsonTest does and so it won't default"
nl|'\n'
comment|'# to the extension name'
nl|'\n'
DECL|variable|sample_dir
name|'sample_dir'
op|'='
name|'extension_name'
newline|'\n'
nl|'\n'
DECL|member|setUp
name|'def'
name|'setUp'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
comment|'# We override osapi_hide_server_address_states in order'
nl|'\n'
comment|'# to have an example of in the json/xml samples of the'
nl|'\n'
comment|'# addresses being hidden'
nl|'\n'
indent|'        '
name|'CONF'
op|'.'
name|'set_override'
op|'('
string|'"osapi_hide_server_address_states"'
op|','
nl|'\n'
op|'['
name|'vm_states'
op|'.'
name|'ACTIVE'
op|']'
op|')'
newline|'\n'
name|'super'
op|'('
name|'ServersSampleHideAddressesJsonTest'
op|','
name|'self'
op|')'
op|'.'
name|'setUp'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ServersSampleHideAddressesXMLTest
dedent|''
dedent|''
name|'class'
name|'ServersSampleHideAddressesXMLTest'
op|'('
name|'ServersSampleHideAddressesJsonTest'
op|')'
op|':'
newline|'\n'
DECL|variable|ctype
indent|'    '
name|'ctype'
op|'='
string|"'xml'"
newline|'\n'
dedent|''
endmarker|''
end_unit
