begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
comment|'# Copyright 2012 Nebula, Inc.'
nl|'\n'
comment|'# Copyright 2013 IBM Corp.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'tests'
op|'.'
name|'integrated'
op|'.'
name|'v3'
name|'import'
name|'api_sample_base'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|QuotaClassesSampleJsonTests
name|'class'
name|'QuotaClassesSampleJsonTests'
op|'('
name|'api_sample_base'
op|'.'
name|'ApiSampleTestBaseV3'
op|')'
op|':'
newline|'\n'
DECL|variable|extension_name
indent|'    '
name|'extension_name'
op|'='
string|'"os-quota-class-sets"'
newline|'\n'
DECL|variable|set_id
name|'set_id'
op|'='
string|"'test_class'"
newline|'\n'
nl|'\n'
DECL|member|test_show_quota_classes
name|'def'
name|'test_show_quota_classes'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
comment|'# Get api sample to show quota classes.'
nl|'\n'
indent|'        '
name|'response'
op|'='
name|'self'
op|'.'
name|'_do_get'
op|'('
string|"'os-quota-class-sets/%s'"
op|'%'
name|'self'
op|'.'
name|'set_id'
op|')'
newline|'\n'
name|'subs'
op|'='
op|'{'
string|"'set_id'"
op|':'
name|'self'
op|'.'
name|'set_id'
op|'}'
newline|'\n'
name|'self'
op|'.'
name|'_verify_response'
op|'('
string|"'quota-classes-show-get-resp'"
op|','
name|'subs'
op|','
nl|'\n'
name|'response'
op|','
number|'200'
op|')'
newline|'\n'
nl|'\n'
DECL|member|test_update_quota_classes
dedent|''
name|'def'
name|'test_update_quota_classes'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
comment|'# Get api sample to update quota classes.'
nl|'\n'
indent|'        '
name|'response'
op|'='
name|'self'
op|'.'
name|'_do_put'
op|'('
string|"'os-quota-class-sets/%s'"
op|'%'
name|'self'
op|'.'
name|'set_id'
op|','
nl|'\n'
string|"'quota-classes-update-post-req'"
op|','
nl|'\n'
op|'{'
op|'}'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'_verify_response'
op|'('
string|"'quota-classes-update-post-resp'"
op|','
nl|'\n'
op|'{'
op|'}'
op|','
name|'response'
op|','
number|'200'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|QuotaClassesSampleXmlTests
dedent|''
dedent|''
name|'class'
name|'QuotaClassesSampleXmlTests'
op|'('
name|'QuotaClassesSampleJsonTests'
op|')'
op|':'
newline|'\n'
DECL|variable|ctype
indent|'    '
name|'ctype'
op|'='
string|'"xml"'
newline|'\n'
dedent|''
endmarker|''
end_unit
