begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\n:mod:`nova.endpoint` -- Main NOVA Api endpoints\n=====================================================\n\n.. automodule:: nova.endpoint\n   :platform: Unix\n   :synopsis: REST APIs for all nova functions\n.. moduleauthor:: Jesse Andrews <jesse@ansolabs.com>\n.. moduleauthor:: Devin Carlen <devin.carlen@gmail.com>\n.. moduleauthor:: Vishvananda Ishaya <vishvananda@yahoo.com>\n.. moduleauthor:: Joshua McKenty <joshua@cognition.ca>\n.. moduleauthor:: Manish Singh <yosh@gimp.org>\n.. moduleauthor:: Andy Smith <andy@anarkystic.com>\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'wsgi'
newline|'\n'
name|'import'
name|'routes'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'endpoint'
name|'import'
name|'rackspace'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'endpoint'
name|'import'
name|'aws'
newline|'\n'
nl|'\n'
DECL|class|APIVersionRouter
name|'class'
name|'APIVersionRouter'
op|'('
name|'wsgi'
op|'.'
name|'Router'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Routes top-level requests to the appropriate API."""'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'mapper'
op|'='
name|'routes'
op|'.'
name|'Mapper'
op|'('
op|')'
newline|'\n'
nl|'\n'
name|'rsapi'
op|'='
name|'rackspace'
op|'.'
name|'API'
op|'('
op|')'
newline|'\n'
name|'mapper'
op|'.'
name|'connect'
op|'('
name|'None'
op|','
string|'"/v1.0/{path_info:.*}"'
op|','
name|'controller'
op|'='
name|'rsapi'
op|')'
newline|'\n'
nl|'\n'
name|'mapper'
op|'.'
name|'connect'
op|'('
name|'None'
op|','
string|'"/ec2/{path_info:.*}"'
op|','
name|'controller'
op|'='
name|'aws'
op|'.'
name|'API'
op|'('
op|')'
op|')'
newline|'\n'
nl|'\n'
name|'super'
op|'('
name|'APIVersionRouter'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'mapper'
op|')'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
