begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|"'''\nUtility methods for working with WSGI servers\n'''"
newline|'\n'
nl|'\n'
DECL|class|Util
name|'class'
name|'Util'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
nl|'\n'
indent|'    '
op|'@'
name|'staticmethod'
newline|'\n'
DECL|member|route
name|'def'
name|'route'
op|'('
name|'reqstr'
op|','
name|'controllers'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'len'
op|'('
name|'reqstr'
op|')'
op|'=='
number|'0'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'Util'
op|'.'
name|'select_root_controller'
op|'('
name|'controllers'
op|')'
op|','
op|'['
op|']'
newline|'\n'
dedent|''
name|'parts'
op|'='
op|'['
name|'x'
name|'for'
name|'x'
name|'in'
name|'reqstr'
op|'.'
name|'split'
op|'('
string|'"/"'
op|')'
name|'if'
name|'len'
op|'('
name|'x'
op|')'
op|'>'
number|'0'
op|']'
newline|'\n'
name|'if'
name|'len'
op|'('
name|'parts'
op|')'
op|'=='
number|'0'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'Util'
op|'.'
name|'select_root_controller'
op|'('
name|'controllers'
op|')'
op|','
op|'['
op|']'
newline|'\n'
dedent|''
name|'return'
name|'controllers'
op|'['
name|'parts'
op|'['
number|'0'
op|']'
op|']'
op|','
name|'parts'
op|'['
number|'1'
op|':'
op|']'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'staticmethod'
newline|'\n'
DECL|member|select_root_controller
name|'def'
name|'select_root_controller'
op|'('
name|'controllers'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'if'
string|"''"
name|'in'
name|'controllers'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'controllers'
op|'['
string|"''"
op|']'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'None'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
dedent|''
endmarker|''
end_unit
