begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Copyright 2013 NEC Corporation.  All rights reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
string|'"""\nRequest Body validating middleware.\n\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'functools'
newline|'\n'
nl|'\n'
name|'from'
name|'validators'
name|'import'
name|'_SchemaValidator'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|schema
name|'def'
name|'schema'
op|'('
name|'request_body_schema'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""\n    Register a schema to validate request body.\n\n    Registered schema will be used for validating request body just before\n    API method executing.\n\n    :argument dict request_body_schema: a schema to validate request body\n\n    """'
newline|'\n'
name|'schema_validator'
op|'='
name|'_SchemaValidator'
op|'('
name|'request_body_schema'
op|')'
newline|'\n'
nl|'\n'
DECL|function|add_validator
name|'def'
name|'add_validator'
op|'('
name|'func'
op|')'
op|':'
newline|'\n'
indent|'        '
op|'@'
name|'functools'
op|'.'
name|'wraps'
op|'('
name|'func'
op|')'
newline|'\n'
DECL|function|wrapper
name|'def'
name|'wrapper'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'schema_validator'
op|'.'
name|'validate'
op|'('
name|'kwargs'
op|'['
string|"'body'"
op|']'
op|')'
newline|'\n'
name|'return'
name|'func'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'wrapper'
newline|'\n'
dedent|''
name|'return'
name|'add_validator'
newline|'\n'
dedent|''
endmarker|''
end_unit
