begin_unit
comment|'# Copyright 2013 NEC Corporation.  All rights reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
string|'"""\nRequest Body validating middleware.\n\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'functools'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'api'
op|'.'
name|'openstack'
name|'import'
name|'api_version_request'
name|'as'
name|'api_version'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'api'
op|'.'
name|'validation'
name|'import'
name|'validators'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|schema
name|'def'
name|'schema'
op|'('
name|'request_body_schema'
op|','
name|'min_version'
op|'='
name|'None'
op|','
name|'max_version'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Register a schema to validate request body.\n\n    Registered schema will be used for validating request body just before\n    API method executing.\n\n    :argument dict request_body_schema: a schema to validate request body\n\n    """'
newline|'\n'
nl|'\n'
DECL|function|add_validator
name|'def'
name|'add_validator'
op|'('
name|'func'
op|')'
op|':'
newline|'\n'
indent|'        '
op|'@'
name|'functools'
op|'.'
name|'wraps'
op|'('
name|'func'
op|')'
newline|'\n'
DECL|function|wrapper
name|'def'
name|'wrapper'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'min_ver'
op|'='
name|'api_version'
op|'.'
name|'APIVersionRequest'
op|'('
name|'min_version'
op|')'
newline|'\n'
name|'max_ver'
op|'='
name|'api_version'
op|'.'
name|'APIVersionRequest'
op|'('
name|'max_version'
op|')'
newline|'\n'
nl|'\n'
comment|'# The request object is always the second argument.'
nl|'\n'
comment|'# However numerous unittests pass in the request object'
nl|'\n'
comment|'# via kwargs instead so we handle that as well.'
nl|'\n'
comment|"# TODO(cyeoh): cleanup unittests so we don't have to"
nl|'\n'
comment|'# to do this'
nl|'\n'
name|'if'
string|"'req'"
name|'in'
name|'kwargs'
op|':'
newline|'\n'
indent|'                '
name|'ver'
op|'='
name|'kwargs'
op|'['
string|"'req'"
op|']'
op|'.'
name|'api_version_request'
newline|'\n'
name|'legacy_v2'
op|'='
name|'kwargs'
op|'['
string|"'req'"
op|']'
op|'.'
name|'is_legacy_v2'
op|'('
op|')'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'                '
name|'ver'
op|'='
name|'args'
op|'['
number|'1'
op|']'
op|'.'
name|'api_version_request'
newline|'\n'
name|'legacy_v2'
op|'='
name|'args'
op|'['
number|'1'
op|']'
op|'.'
name|'is_legacy_v2'
op|'('
op|')'
newline|'\n'
nl|'\n'
dedent|''
name|'if'
name|'legacy_v2'
op|':'
newline|'\n'
comment|'# NOTE: For v2.0 compatible API, here should work like'
nl|'\n'
comment|'#    client  | schema min_version | schema'
nl|'\n'
comment|'# -----------+--------------------+--------'
nl|'\n'
comment|'#  legacy_v2 | None               | work'
nl|'\n'
comment|'#  legacy_v2 | 2.0                | work'
nl|'\n'
comment|"#  legacy_v2 | 2.1+               | don't"
nl|'\n'
indent|'                '
name|'if'
name|'min_version'
name|'is'
name|'None'
name|'or'
name|'min_version'
op|'=='
string|"'2.0'"
op|':'
newline|'\n'
indent|'                    '
name|'schema_validator'
op|'='
name|'validators'
op|'.'
name|'_SchemaValidator'
op|'('
nl|'\n'
name|'request_body_schema'
op|','
name|'legacy_v2'
op|')'
newline|'\n'
name|'schema_validator'
op|'.'
name|'validate'
op|'('
name|'kwargs'
op|'['
string|"'body'"
op|']'
op|')'
newline|'\n'
dedent|''
dedent|''
name|'elif'
name|'ver'
op|'.'
name|'matches'
op|'('
name|'min_ver'
op|','
name|'max_ver'
op|')'
op|':'
newline|'\n'
comment|'# Only validate against the schema if it lies within'
nl|'\n'
comment|'# the version range specified. Note that if both min'
nl|'\n'
comment|'# and max are not specified the validator will always'
nl|'\n'
comment|'# be run.'
nl|'\n'
indent|'                '
name|'schema_validator'
op|'='
name|'validators'
op|'.'
name|'_SchemaValidator'
op|'('
nl|'\n'
name|'request_body_schema'
op|','
name|'legacy_v2'
op|')'
newline|'\n'
name|'schema_validator'
op|'.'
name|'validate'
op|'('
name|'kwargs'
op|'['
string|"'body'"
op|']'
op|')'
newline|'\n'
nl|'\n'
dedent|''
name|'return'
name|'func'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'wrapper'
newline|'\n'
nl|'\n'
dedent|''
name|'return'
name|'add_validator'
newline|'\n'
dedent|''
endmarker|''
end_unit
