begin_unit
comment|'# Copyright 2013 Red Hat, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Provides a way to generate serializable reports\n\nThis package/module provides mechanisms for defining reports\nwhich may then be serialized into various data types.  Each\nreport ( :class:`openstack.common.report.report.BasicReport` )\nis composed of one or more report sections\n( :class:`openstack.common.report.report.BasicSection` ),\nwhich contain generators which generate data models\n( :class:`openstack.common.report.models.base.ReportModels` ),\nwhich are then serialized by views.\n"""'
newline|'\n'
endmarker|''
end_unit
