begin_unit
comment|'# Copyright 2016 Hewlett Packard Enterprise Development Company, L.P.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'# not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'# a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#      http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'# License for the specific language governing permissions and limitations'
nl|'\n'
comment|'# under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_config'
name|'import'
name|'cfg'
newline|'\n'
name|'from'
name|'oslo_middleware'
name|'import'
name|'cors'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|set_middleware_defaults
name|'def'
name|'set_middleware_defaults'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Update default configuration options for oslo.middleware."""'
newline|'\n'
comment|'# CORS Defaults'
nl|'\n'
comment|'# TODO(krotscheck): Update with https://review.openstack.org/#/c/285368/'
nl|'\n'
name|'cfg'
op|'.'
name|'set_defaults'
op|'('
name|'cors'
op|'.'
name|'CORS_OPTS'
op|','
nl|'\n'
name|'allow_headers'
op|'='
op|'['
string|"'X-Auth-Token'"
op|','
nl|'\n'
string|"'X-Openstack-Request-Id'"
op|','
nl|'\n'
string|"'X-Identity-Status'"
op|','
nl|'\n'
string|"'X-Roles'"
op|','
nl|'\n'
string|"'X-Service-Catalog'"
op|','
nl|'\n'
string|"'X-User-Id'"
op|','
nl|'\n'
string|"'X-Tenant-Id'"
op|']'
op|','
nl|'\n'
name|'expose_headers'
op|'='
op|'['
string|"'X-Auth-Token'"
op|','
nl|'\n'
string|"'X-Openstack-Request-Id'"
op|','
nl|'\n'
string|"'X-Subject-Token'"
op|','
nl|'\n'
string|"'X-Service-Token'"
op|']'
op|','
nl|'\n'
name|'allow_methods'
op|'='
op|'['
string|"'GET'"
op|','
nl|'\n'
string|"'PUT'"
op|','
nl|'\n'
string|"'POST'"
op|','
nl|'\n'
string|"'DELETE'"
op|','
nl|'\n'
string|"'PATCH'"
op|']'
nl|'\n'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
