begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
string|'"""\n:mod:`nova.console` -- Console Prxy to set up VM console access (i.e. with xvp)\n=====================================================\n\n.. automodule:: nova.console\n   :platform: Unix\n   :synopsis: Wrapper around console proxies such as xvp to set up\n              multitenant VM console access\n.. moduleauthor:: Monsyne Dragon <mdragon@rackspace.com>\n"""'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'console'
op|'.'
name|'api'
name|'import'
name|'API'
newline|'\n'
endmarker|''
end_unit
