begin_unit
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'keystoneauth1'
name|'import'
name|'loading'
name|'as'
name|'ks_loading'
newline|'\n'
name|'from'
name|'oslo_config'
name|'import'
name|'cfg'
newline|'\n'
nl|'\n'
DECL|variable|barbican_group
name|'barbican_group'
op|'='
name|'cfg'
op|'.'
name|'OptGroup'
op|'('
nl|'\n'
string|"'barbican'"
op|','
nl|'\n'
DECL|variable|title
name|'title'
op|'='
string|"'Barbican options'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|barbican_opts
name|'barbican_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'catalog_info'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'key-manager:barbican:public'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Info to match when looking for barbican in the service '"
nl|'\n'
string|"'catalog. Format is: separated values of the form: '"
nl|'\n'
string|"'<service_type>:<service_name>:<endpoint_type>'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'endpoint_template'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Override service catalog lookup with template for '"
nl|'\n'
string|"'barbican endpoint e.g. '"
nl|'\n'
string|"'http://localhost:9311/v1/%(project_id)s'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'os_region_name'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Region name of this node'"
op|')'
op|','
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|register_opts
name|'def'
name|'register_opts'
op|'('
name|'conf'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'conf'
op|'.'
name|'register_group'
op|'('
name|'barbican_group'
op|')'
newline|'\n'
name|'conf'
op|'.'
name|'register_opts'
op|'('
name|'barbican_opts'
op|','
name|'group'
op|'='
name|'barbican_group'
op|')'
newline|'\n'
name|'ks_loading'
op|'.'
name|'register_session_conf_options'
op|'('
name|'conf'
op|','
name|'barbican_group'
op|'.'
name|'name'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|list_opts
dedent|''
name|'def'
name|'list_opts'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
op|'{'
nl|'\n'
name|'barbican_group'
op|'.'
name|'name'
op|':'
name|'barbican_opts'
nl|'\n'
op|'}'
newline|'\n'
dedent|''
endmarker|''
end_unit
