begin_unit
comment|'# Copyright 2015 Huawei Technology corp.'
nl|'\n'
comment|'# Copyright 2015 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_config'
name|'import'
name|'cfg'
newline|'\n'
nl|'\n'
DECL|variable|ephemeral_storage_encryption_group
name|'ephemeral_storage_encryption_group'
op|'='
name|'cfg'
op|'.'
name|'OptGroup'
op|'('
nl|'\n'
DECL|variable|name
name|'name'
op|'='
string|"'ephemeral_storage_encryption'"
op|','
nl|'\n'
DECL|variable|title
name|'title'
op|'='
string|"'Ephemeral storage encryption options'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|ephemeral_storage_encryption_opts
name|'ephemeral_storage_encryption_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'BoolOpt'
op|'('
string|"'enabled'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
name|'False'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Whether to encrypt ephemeral storage'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'cipher'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'aes-xts-plain64'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'The cipher and mode to be used to encrypt ephemeral '"
nl|'\n'
string|"'storage. Which ciphers are available ciphers depends '"
nl|'\n'
string|"'on kernel support. See /proc/crypto for the list of '"
nl|'\n'
string|"'available options.'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'key_size'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'512'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'The bit length of the encryption key to be used to '"
nl|'\n'
string|"'encrypt ephemeral storage (in XTS mode only half of '"
nl|'\n'
string|"'the bits are used for encryption key)'"
op|')'
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|register_opts
name|'def'
name|'register_opts'
op|'('
name|'conf'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'conf'
op|'.'
name|'register_group'
op|'('
name|'ephemeral_storage_encryption_group'
op|')'
newline|'\n'
name|'conf'
op|'.'
name|'register_opts'
op|'('
name|'ephemeral_storage_encryption_opts'
op|','
nl|'\n'
name|'group'
op|'='
string|"'ephemeral_storage_encryption'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|list_opts
dedent|''
name|'def'
name|'list_opts'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
op|'{'
string|"'ephemeral_storage_encryption'"
op|':'
name|'ephemeral_storage_encryption_opts'
op|'}'
newline|'\n'
dedent|''
endmarker|''
end_unit
