begin_unit
comment|'# Copyright 2016 Huawei Technology corp.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_config'
name|'import'
name|'cfg'
newline|'\n'
nl|'\n'
DECL|variable|default_floating_pool_opt
name|'default_floating_pool_opt'
op|'='
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'default_floating_pool'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'nova'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Default pool for floating IPs'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|auto_assign_opt
name|'auto_assign_opt'
op|'='
name|'cfg'
op|'.'
name|'BoolOpt'
op|'('
string|"'auto_assign_floating_ip'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
name|'False'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Autoassigning floating IP to VM'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|dns_mgr_opt
name|'dns_mgr_opt'
op|'='
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'floating_ip_dns_manager'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'nova.network.noop_dns_driver.NoopDNSDriver'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Full class name for the DNS Manager for '"
nl|'\n'
string|"'floating IPs'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|instance_dns_opt
name|'instance_dns_opt'
op|'='
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'instance_dns_manager'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'nova.network.noop_dns_driver.NoopDNSDriver'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Full class name for the DNS Manager for '"
nl|'\n'
string|"'instance IPs'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|dns_domain_opt
name|'dns_domain_opt'
op|'='
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'instance_dns_domain'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"''"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Full class name for the DNS Zone '"
nl|'\n'
string|"'for instance IPs'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|ALL_OPTS
name|'ALL_OPTS'
op|'='
op|'['
nl|'\n'
name|'default_floating_pool_opt'
op|','
nl|'\n'
name|'auto_assign_opt'
op|','
nl|'\n'
name|'dns_domain_opt'
op|','
nl|'\n'
name|'dns_mgr_opt'
op|','
nl|'\n'
name|'instance_dns_opt'
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|register_opts
name|'def'
name|'register_opts'
op|'('
name|'conf'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'conf'
op|'.'
name|'register_opts'
op|'('
name|'ALL_OPTS'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|list_opts
dedent|''
name|'def'
name|'list_opts'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
op|'{'
string|"'DEFAULT'"
op|':'
name|'ALL_OPTS'
op|'}'
newline|'\n'
dedent|''
endmarker|''
end_unit
