begin_unit
comment|'# Copyright (c) 2016 Intel, Inc.'
nl|'\n'
comment|'# Copyright (c) 2013 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_config'
name|'import'
name|'cfg'
newline|'\n'
nl|'\n'
DECL|variable|notify_on_state_change
name|'notify_on_state_change'
op|'='
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'notify_on_state_change'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'If set, send compute.instance.update notifications on instance '"
nl|'\n'
string|"'state changes.  Valid values are None for no notifications, '"
nl|'\n'
string|'\'"vm_state" for notifications on VM state changes, or \''
nl|'\n'
string|'\'"vm_and_task_state" for notifications on VM and task state \''
nl|'\n'
string|"'changes.'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|notify_api_faults
name|'notify_api_faults'
op|'='
name|'cfg'
op|'.'
name|'BoolOpt'
op|'('
string|"'notify_api_faults'"
op|','
name|'default'
op|'='
name|'False'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'If set, send api.fault notifications on caught exceptions '"
nl|'\n'
string|"'in the API service.'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|default_notification_level
name|'default_notification_level'
op|'='
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'default_notification_level'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'INFO'"
op|','
nl|'\n'
DECL|variable|choices
name|'choices'
op|'='
op|'('
string|"'DEBUG'"
op|','
string|"'INFO'"
op|','
string|"'WARN'"
op|','
string|"'ERROR'"
op|','
string|"'CRITICAL'"
op|')'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Default notification level for outgoing notifications'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|default_publisher_id
name|'default_publisher_id'
op|'='
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'default_publisher_id'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Default publisher_id for outgoing notifications'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|ALL_OPTS
name|'ALL_OPTS'
op|'='
op|'['
name|'notify_on_state_change'
op|','
name|'notify_api_faults'
op|','
nl|'\n'
name|'default_notification_level'
op|','
nl|'\n'
name|'default_publisher_id'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|register_opts
name|'def'
name|'register_opts'
op|'('
name|'conf'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'conf'
op|'.'
name|'register_opts'
op|'('
name|'ALL_OPTS'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|list_opts
dedent|''
name|'def'
name|'list_opts'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
op|'{'
string|"'DEFAULT'"
op|':'
name|'ALL_OPTS'
op|'}'
newline|'\n'
dedent|''
endmarker|''
end_unit
