begin_unit
comment|'# Copyright 2015 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_config'
name|'import'
name|'cfg'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|api_opts
name|'api_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'ListOpt'
op|'('
string|"'extensions_blacklist'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
op|'['
op|']'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'DEPRECATED: A list of v2.1 API extensions to never '"
nl|'\n'
string|"'load. Specify the extension aliases here. '"
nl|'\n'
string|"'This option will be removed in the near future. '"
nl|'\n'
string|"'After that point you have to run all of the API.'"
op|','
nl|'\n'
name|'deprecated_for_removal'
op|'='
name|'True'
op|','
name|'deprecated_group'
op|'='
string|"'osapi_v21'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'ListOpt'
op|'('
string|"'extensions_whitelist'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
op|'['
op|']'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'DEPRECATED: If the list is not empty then a v2.1 '"
nl|'\n'
string|"'API extension will only be loaded if it exists in this '"
nl|'\n'
string|"'list. Specify the extension aliases here. '"
nl|'\n'
string|"'This option will be removed in the near future. '"
nl|'\n'
string|"'After that point you have to run all of the API.'"
op|','
nl|'\n'
name|'deprecated_for_removal'
op|'='
name|'True'
op|','
name|'deprecated_group'
op|'='
string|"'osapi_v21'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'project_id_regex'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
name|'None'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'DEPRECATED: The validation regex for project_ids '"
nl|'\n'
string|"'used in urls. This defaults to [0-9a-f\\-]+ if not set, '"
nl|'\n'
string|"'which matches normal uuids created by keystone.'"
op|','
nl|'\n'
name|'deprecated_for_removal'
op|'='
name|'True'
op|','
name|'deprecated_group'
op|'='
string|"'osapi_v21'"
op|')'
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
DECL|variable|api_opts_group
name|'api_opts_group'
op|'='
name|'cfg'
op|'.'
name|'OptGroup'
op|'('
name|'name'
op|'='
string|'"osapi_v21"'
op|','
name|'title'
op|'='
string|'"API v2.1 Options"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|register_opts
name|'def'
name|'register_opts'
op|'('
name|'conf'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'conf'
op|'.'
name|'register_group'
op|'('
name|'api_opts_group'
op|')'
newline|'\n'
name|'conf'
op|'.'
name|'register_opts'
op|'('
name|'api_opts'
op|','
name|'api_opts_group'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|list_opts
dedent|''
name|'def'
name|'list_opts'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
op|'{'
name|'api_opts_group'
op|':'
name|'api_opts'
op|'}'
newline|'\n'
dedent|''
endmarker|''
end_unit
