begin_unit
comment|'# Copyright 2016 Intel Corporation'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'# not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'# a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#   http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'# License for the specific language governing permissions and limitations'
nl|'\n'
comment|'# under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_config'
name|'import'
name|'cfg'
newline|'\n'
nl|'\n'
DECL|variable|notification_format
name|'notification_format'
op|'='
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
nl|'\n'
string|"'notification_format'"
op|','
nl|'\n'
DECL|variable|choices
name|'choices'
op|'='
op|'['
string|"'unversioned'"
op|','
string|"'versioned'"
op|','
string|"'both'"
op|']'
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'both'"
op|','
nl|'\n'
name|'help'
op|'='
string|'"""Specifies which notification format shall be used by nova.\n\nPossible values:\n* unversioned: Only the legacy unversioned notifications are emitted.\n* versioned: Only the new versioned notifications are emitted.\n* both: Both the legacy unversioned and the new versioned notifications are\n  emitted. (Default)\n\nCurrently there is no feature parity between unversioned and versioned\nnotifications. If the deployment needs the full range of legacy notifications\nthen the recommended setting is \'both\' or \'unversioned\'. Nova does not allow\nadding new legacy notifications so new notification will be emitted as\nversioned notifications. If the deployment needs the new notifications then\neither \'both\' or \'versioned\' value is required. The list of versioned\nnotifications is visible in\nhttp://docs.openstack.org/developer/nova/notifications.html\nNova is planning to deprecate this parameter as soon as feature parity is\nachieved.\n\nThis is an advanced option, deployers rarely needs to change the default value.\n\nServices which consume this:\n\n* nova-api\n* nova-conductor\n* nova-compute\n* nova-scheduler\n\nRelated options:\n\n* None"""'
op|')'
newline|'\n'
nl|'\n'
DECL|variable|ALL_OPTS
name|'ALL_OPTS'
op|'='
op|'['
name|'notification_format'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|register_opts
name|'def'
name|'register_opts'
op|'('
name|'conf'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'conf'
op|'.'
name|'register_opts'
op|'('
name|'ALL_OPTS'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|list_opts
dedent|''
name|'def'
name|'list_opts'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
op|'{'
string|'"DEFAULT"'
op|':'
name|'ALL_OPTS'
op|'}'
newline|'\n'
dedent|''
endmarker|''
end_unit
