begin_unit
comment|'# Copyright (c) 2016 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_config'
name|'import'
name|'cfg'
newline|'\n'
nl|'\n'
DECL|variable|servicegroup_driver
name|'servicegroup_driver'
op|'='
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'servicegroup_driver'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'db'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'The driver for servicegroup '"
nl|'\n'
string|"'service.'"
op|','
nl|'\n'
DECL|variable|choices
name|'choices'
op|'='
op|'['
string|"'db'"
op|','
string|"'mc'"
op|']'
op|')'
newline|'\n'
nl|'\n'
DECL|variable|SERVICEGROUP_OPTS
name|'SERVICEGROUP_OPTS'
op|'='
op|'['
name|'servicegroup_driver'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|register_opts
name|'def'
name|'register_opts'
op|'('
name|'conf'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'conf'
op|'.'
name|'register_opts'
op|'('
name|'SERVICEGROUP_OPTS'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|list_opts
dedent|''
name|'def'
name|'list_opts'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
op|'{'
string|"'DEFAULT'"
op|':'
name|'SERVICEGROUP_OPTS'
op|'}'
newline|'\n'
dedent|''
endmarker|''
end_unit
