begin_unit
comment|'# Copyright 2016 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_config'
name|'import'
name|'cfg'
newline|'\n'
name|'from'
name|'oslo_utils'
name|'import'
name|'units'
newline|'\n'
nl|'\n'
DECL|variable|xenserver_group
name|'xenserver_group'
op|'='
name|'cfg'
op|'.'
name|'OptGroup'
op|'('
string|"'xenserver'"
op|','
name|'title'
op|'='
string|"'Xenserver Options'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|xenapi_agent_opts
name|'xenapi_agent_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'agent_timeout'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'30'
op|','
nl|'\n'
name|'help'
op|'='
string|'"""\n               Number of seconds to wait for agent\'s reply to a request.\n\n               Nova configures/performs certain administrative actions on a\n               server with the help of an agent that\'s installed on the server.\n               The communication between Nova and the agent is achieved via\n               sharing messages, called records, over xenstore, a shared\n               storage across all the domains on a Xenserver host.\n               Operations performed by the agent on behalf of nova are:\n               \'version\',\' key_init\', \'password\',\'resetnetwork\',\'inject_file\',\n               and \'agentupdate\'.\n\n               To perform one of the above operations, the xapi \'agent\' plugin\n               writes the command and its associated parameters to a certain\n               location known to the domain and awaits response. On being\n               notified of the message, the agent performs appropriate actions\n               on the server and writes the result back to xenstore.\n               This result is then read by the xapi \'agent\' plugin to\n               determine the success/failure of the operation.\n\n               This config option determines how long the xapi \'agent\' plugin\n               shall wait to read the response off of xenstore for a given\n               request/command. If the agent on the instance fails to write\n               the result in this time period, the operation is considered to\n               have timed out.\n\n               Services which consume this:\n               * ``nova-compute``\n\n               Possible values:\n               * Any positive integer\n\n               Related options:\n               * ``agent_version_timeout``\n               * ``agent_resetnetwork_timeout``\n\n               """'
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'agent_version_timeout'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'300'
op|','
nl|'\n'
name|'help'
op|'='
string|'"""\n               Number of seconds to wait for agent\'t reply to version request.\n\n               This indicates the amount of time xapi \'agent\' plugin waits\n               for the agent to respond to the \'version\' request specifically.\n               The generic timeout for agent communication ``agent_timeout``\n               is ignored in this case.\n\n               During the build process the \'version\' request is used to\n               determine if the agent is available/operational to perform\n               other requests such as \'resetnetwork\', \'password\', \'key_init\'\n               and \'inject_file\'. If the \'version\' call fails, the other\n               configuration is skipped. So, this configuration option can\n               also be interpreted as time in which agent is expected to be\n               fully operational.\n\n               Services which consume this:\n               * ``nova-compute``\n\n               Possible values:\n               * Any positive integer\n\n               Related options:\n               * None\n\n               """'
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'agent_resetnetwork_timeout'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'60'
op|','
nl|'\n'
name|'help'
op|'='
string|'"""\n               Number of seconds to wait for agent\'s reply to resetnetwork\n               request.\n\n               This indicates the amount of time xapi \'agent\' plugin waits\n               for the agent to respond to the \'resetnetwork\' request\n               specifically. The generic timeout for agent communication\n               ``agent_timeout`` is ignored in this case.\n\n               Services which consume this:\n               * ``nova-compute``\n\n               Possible values:\n               * Any positive integer\n\n               Related options:\n               * None\n\n               """'
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'agent_path'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'usr/sbin/xe-update-networking'"
op|','
nl|'\n'
name|'help'
op|'='
string|'"""\n               Path to locate guest agent on the server.\n\n               Specifies the path in which the XenAPI guest agent should be\n               located. If the agent is present, network configuration is not\n               injected into the image.\n               Used if compute_driver=xenapi.XenAPIDriver and\n               flat_injected=True.\n\n               Services which consume this:\n               * ``nova-compute``\n\n               Possible values:\n               * A valid path\n\n               Related options:\n               * ``flat_injected``\n               * ``compute_driver``\n\n               """'
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'BoolOpt'
op|'('
string|"'disable_agent'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
name|'False'
op|','
nl|'\n'
name|'help'
op|'='
string|'"""\n                Disables the use of XenAPI agent.\n\n                This configuration option suggests whether the use of agent\n                should be enabled or not regardless of what image properties\n                are present. Image properties have an effect only when this\n                is set to ``True``. Read description of config option\n                ``use_agent_default`` for more information.\n\n                Services which consume this:\n                * ``nova-compute``\n\n                Possible values:\n                * True\n                * False\n\n                Related options:\n                * ``use_agent_default``\n\n                """'
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'BoolOpt'
op|'('
string|"'use_agent_default'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
name|'False'
op|','
nl|'\n'
name|'help'
op|'='
string|'"""\n                Whether or not to use the agent by default when its usage is\n                enabled but not indicated by the image.\n\n                The use of XenAPI agent can be disabled altogether using the\n                configuration option ``disable_agent``. However, if it is not\n                disabled, the use of an agent can still be controlled by the\n                image in use through one of its properties,\n                ``xenapi_use_agent``. If this property is either not present\n                or specified incorrectly on the image, the use of agent is\n                determined by this configuration option.\n\n                Note that if this configuration is set to ``True`` when the\n                agent is not present, the boot times will increase\n                significantly.\n\n                Services which consume this:\n                * ``nova-compute``\n\n                Possible values:\n                * True\n                * False\n\n                Related options:\n                * ``disable_agent``\n\n                """'
op|')'
op|','
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|xenapi_session_opts
name|'xenapi_session_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'login_timeout'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'10'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Timeout in seconds for XenAPI login.'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'connection_concurrent'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'5'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Maximum number of concurrent XenAPI connections. '"
nl|'\n'
string|"'Used only if compute_driver=xenapi.XenAPIDriver'"
op|')'
op|','
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|xenapi_torrent_opts
name|'xenapi_torrent_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'torrent_base_url'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Base URL for torrent files; must contain a slash'"
nl|'\n'
string|"' character (see RFC 1808, step 6)'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'FloatOpt'
op|'('
string|"'torrent_seed_chance'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'1.0'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Probability that peer will become a seeder.'"
nl|'\n'
string|"' (1.0 = 100%)'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'torrent_seed_duration'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'3600'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Number of seconds after downloading an image via'"
nl|'\n'
string|"' BitTorrent that it should be seeded for other peers.'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'torrent_max_last_accessed'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'86400'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Cached torrent files not accessed within this number of'"
nl|'\n'
string|"' seconds can be reaped'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'torrent_listen_port_start'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'6881'
op|','
nl|'\n'
DECL|variable|min
name|'min'
op|'='
number|'1'
op|','
nl|'\n'
DECL|variable|max
name|'max'
op|'='
number|'65535'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Beginning of port range to listen on'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'torrent_listen_port_end'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'6891'
op|','
nl|'\n'
DECL|variable|min
name|'min'
op|'='
number|'1'
op|','
nl|'\n'
DECL|variable|max
name|'max'
op|'='
number|'65535'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'End of port range to listen on'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'torrent_download_stall_cutoff'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'600'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Number of seconds a download can remain at the same'"
nl|'\n'
string|"' progress percentage w/o being considered a stall'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'torrent_max_seeder_processes_per_host'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'1'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Maximum number of seeder processes to run concurrently'"
nl|'\n'
string|"' within a given dom0. (-1 = no limit)'"
op|')'
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|xenapi_vm_utils_opts
name|'xenapi_vm_utils_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'cache_images'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'all'"
op|','
nl|'\n'
DECL|variable|choices
name|'choices'
op|'='
op|'('
string|"'all'"
op|','
string|"'some'"
op|','
string|"'none'"
op|')'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Cache glance images locally. `all` will cache all'"
nl|'\n'
string|"' images, `some` will only cache images that have the'"
nl|'\n'
string|"' image_property `cache_in_nova=True`, and `none` turns'"
nl|'\n'
string|"' off caching entirely'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'image_compression_level'"
op|','
nl|'\n'
DECL|variable|min
name|'min'
op|'='
number|'1'
op|','
nl|'\n'
DECL|variable|max
name|'max'
op|'='
number|'9'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Compression level for images, e.g., 9 for gzip -9.'"
nl|'\n'
string|"' Range is 1-9, 9 being most compressed but most CPU'"
nl|'\n'
string|"' intensive on dom0.'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'default_os_type'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'linux'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Default OS type'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'block_device_creation_timeout'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'10'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Time to wait for a block device to be created'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'max_kernel_ramdisk_size'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'16'
op|'*'
name|'units'
op|'.'
name|'Mi'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Maximum size in bytes of kernel or ramdisk images'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'sr_matching_filter'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'default-sr:true'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Filter for finding the SR to be used to install guest '"
nl|'\n'
string|"'instances on. To use the Local Storage in default '"
nl|'\n'
string|"'XenServer/XCP installations set this flag to '"
nl|'\n'
string|"'other-config:i18n-key=local-storage. To select an SR '"
nl|'\n'
string|"'with a different matching criteria, you could set it to '"
nl|'\n'
string|"'other-config:my_favorite_sr=true. On the other hand, to '"
nl|'\n'
string|"'fall back on the Default SR, as displayed by XenCenter, '"
nl|'\n'
string|"'set this flag to: default-sr:true'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'BoolOpt'
op|'('
string|"'sparse_copy'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
name|'True'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Whether to use sparse_copy for copying data on a '"
nl|'\n'
string|"'resize down (False will use standard dd). This speeds '"
nl|'\n'
string|"'up resizes down considerably since large runs of zeros '"
nl|'\n'
string|"'won\\'t have to be rsynced'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'num_vbd_unplug_retries'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'10'
op|','
nl|'\n'
name|'help'
op|'='
string|"'Maximum number of retries to unplug VBD. if <=0, '"
nl|'\n'
string|"'should try once and no retry'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'torrent_images'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'none'"
op|','
nl|'\n'
DECL|variable|choices
name|'choices'
op|'='
op|'('
string|"'all'"
op|','
string|"'some'"
op|','
string|"'none'"
op|')'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Whether or not to download images via Bit Torrent.'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'ipxe_network_name'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Name of network to use for booting iPXE ISOs'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'ipxe_boot_menu_url'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'URL to the iPXE boot menu'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'ipxe_mkisofs_cmd'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'mkisofs'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Name and optionally path of the tool used for '"
nl|'\n'
string|"'ISO image creation'"
op|')'
op|','
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|xenapi_opts
name|'xenapi_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'connection_url'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'URL for connection to XenServer/Xen Cloud Platform. '"
nl|'\n'
string|"'A special value of unix://local can be used to connect '"
nl|'\n'
string|"'to the local unix socket.  '"
nl|'\n'
string|"'Required if compute_driver=xenapi.XenAPIDriver'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'connection_username'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'root'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Username for connection to XenServer/Xen Cloud Platform. '"
nl|'\n'
string|"'Used only if compute_driver=xenapi.XenAPIDriver'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'connection_password'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Password for connection to XenServer/Xen Cloud Platform. '"
nl|'\n'
string|"'Used only if compute_driver=xenapi.XenAPIDriver'"
op|','
nl|'\n'
DECL|variable|secret
name|'secret'
op|'='
name|'True'
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'FloatOpt'
op|'('
string|"'vhd_coalesce_poll_interval'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'5.0'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'The interval used for polling of coalescing vhds. '"
nl|'\n'
string|"'Used only if compute_driver=xenapi.XenAPIDriver'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'BoolOpt'
op|'('
string|"'check_host'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
name|'True'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Ensure compute service is running on host XenAPI '"
nl|'\n'
string|"'connects to.'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'vhd_coalesce_max_attempts'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'20'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Max number of times to poll for VHD to coalesce. '"
nl|'\n'
string|"'Used only if compute_driver=xenapi.XenAPIDriver'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'sr_base_path'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'/var/run/sr-mount'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Base path to the storage repository'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'target_host'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'The iSCSI Target Host'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'target_port'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'3260'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'The iSCSI Target Port, default is port 3260'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'iqn_prefix'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'iqn.2010-10.org.openstack'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'IQN Prefix'"
op|')'
op|','
nl|'\n'
comment|'# NOTE(sirp): This is a work-around for a bug in Ubuntu Maverick,'
nl|'\n'
comment|'# when we pull support for it, we should remove this'
nl|'\n'
name|'cfg'
op|'.'
name|'BoolOpt'
op|'('
string|"'remap_vbd_dev'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
name|'False'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Used to enable the remapping of VBD dev '"
nl|'\n'
string|"'(Works around an issue in Ubuntu Maverick)'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'remap_vbd_dev_prefix'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'sd'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Specify prefix to remap VBD dev to '"
nl|'\n'
string|"'(ex. /dev/xvdb -> /dev/sdb)'"
op|')'
op|','
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
DECL|variable|xenapi_vmops_opts
name|'xenapi_vmops_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'IntOpt'
op|'('
string|"'running_timeout'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
number|'60'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Number of seconds to wait for instance '"
nl|'\n'
string|"'to go to running state'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'vif_driver'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'nova.virt.xenapi.vif.XenAPIBridgeDriver'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'The XenAPI VIF driver using XenServer Network APIs.'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'StrOpt'
op|'('
string|"'image_upload_handler'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
string|"'nova.virt.xenapi.image.glance.GlanceStore'"
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Dom0 plugin driver used to handle image uploads.'"
op|')'
op|','
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
DECL|variable|ALL_XENSERVER_OPTS
name|'ALL_XENSERVER_OPTS'
op|'='
op|'('
name|'xenapi_agent_opts'
op|'+'
nl|'\n'
name|'xenapi_session_opts'
op|'+'
nl|'\n'
name|'xenapi_torrent_opts'
op|'+'
nl|'\n'
name|'xenapi_vm_utils_opts'
op|'+'
nl|'\n'
name|'xenapi_opts'
op|'+'
nl|'\n'
name|'xenapi_vmops_opts'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|register_opts
name|'def'
name|'register_opts'
op|'('
name|'conf'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'conf'
op|'.'
name|'register_group'
op|'('
name|'xenserver_group'
op|')'
newline|'\n'
name|'conf'
op|'.'
name|'register_opts'
op|'('
name|'ALL_XENSERVER_OPTS'
op|','
name|'group'
op|'='
name|'xenserver_group'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|list_opts
dedent|''
name|'def'
name|'list_opts'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
op|'{'
name|'xenserver_group'
op|':'
name|'ALL_XENSERVER_OPTS'
op|'}'
newline|'\n'
dedent|''
endmarker|''
end_unit
