begin_unit
comment|'# Copyright 2014 Red Hat, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Provides process view\n\nThis module provides a view for\nvisualizing processes in human-readable formm\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
op|'.'
name|'report'
op|'.'
name|'views'
op|'.'
name|'jinja_view'
name|'as'
name|'jv'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ProcessView
name|'class'
name|'ProcessView'
op|'('
name|'jv'
op|'.'
name|'JinjaView'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""A Process View\n\n    This view displays process models defined by\n    :class:`openstack.common.report.models.process.ProcessModel`\n    """'
newline|'\n'
nl|'\n'
DECL|variable|VIEW_TEXT
name|'VIEW_TEXT'
op|'='
op|'('
nl|'\n'
string|'"Process {{ pid }} (under {{ parent_pid }}) "'
nl|'\n'
string|'"[ run by: {{ username }} ({{ uids.real|default(\'unknown uid\') }}),"'
nl|'\n'
string|'" state: {{ state }} ]\\n"'
nl|'\n'
string|'"{% for child in children %}"'
nl|'\n'
string|'"    {{ child }}"'
nl|'\n'
string|'"{% endfor %}"'
nl|'\n'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
