begin_unit
comment|'# Copyright (c) 2014 Red Hat, Inc.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|class|SchedulerReportClient
name|'class'
name|'SchedulerReportClient'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Client class for updating the scheduler."""'
newline|'\n'
nl|'\n'
DECL|member|update_resource_stats
name|'def'
name|'update_resource_stats'
op|'('
name|'self'
op|','
name|'compute_node'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Creates or updates stats for the supplied compute node.\n\n        :param compute_node: updated nova.objects.ComputeNode to report\n        """'
newline|'\n'
name|'compute_node'
op|'.'
name|'save'
op|'('
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
