begin_unit
comment|'# Copyright 2014 IBM Corp.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|class|VersionedMethod
name|'class'
name|'VersionedMethod'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
nl|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'name'
op|','
name|'start_version'
op|','
name|'end_version'
op|','
name|'func'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Versioning information for a single method\n\n        @name: Name of the method\n        @start_version: Minimum acceptable version\n        @end_version: Maximum acceptable_version\n        @func: Method to call\n\n        Minimum and maximums are inclusive\n        """'
newline|'\n'
name|'self'
op|'.'
name|'name'
op|'='
name|'name'
newline|'\n'
name|'self'
op|'.'
name|'start_version'
op|'='
name|'start_version'
newline|'\n'
name|'self'
op|'.'
name|'end_version'
op|'='
name|'end_version'
newline|'\n'
name|'self'
op|'.'
name|'func'
op|'='
name|'func'
newline|'\n'
nl|'\n'
DECL|member|__str__
dedent|''
name|'def'
name|'__str__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
op|'('
string|'"Version Method %s: min: %s, max: %s"'
nl|'\n'
op|'%'
op|'('
name|'self'
op|'.'
name|'name'
op|','
name|'self'
op|'.'
name|'start_version'
op|','
name|'self'
op|'.'
name|'end_version'
op|')'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
