begin_unit
comment|'# Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'# not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'# a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#      http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'# License for the specific language governing permissions and limitations'
nl|'\n'
comment|'# under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_reports'
name|'import'
name|'guru_meditation_report'
name|'as'
name|'gmr'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'test'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'version'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|TestServerGet
name|'class'
name|'TestServerGet'
op|'('
name|'test'
op|'.'
name|'TestCase'
op|')'
op|':'
newline|'\n'
nl|'\n'
DECL|member|test_guru_meditation_report_generation
indent|'    '
name|'def'
name|'test_guru_meditation_report_generation'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Regression test for bug #1568208.\n\n        This test ensures a text guru meditation report can be generated\n        successfully and generation does not fail e.g. due to incorrectly\n        registered config options.\n\n        """'
newline|'\n'
nl|'\n'
comment|'# NOTE(rpodolyaka): we are only interested in success of run() call'
nl|'\n'
comment|"# here, it's up to oslo_reports tests to check the generated report"
nl|'\n'
name|'generator'
op|'='
name|'gmr'
op|'.'
name|'TextGuruMeditation'
op|'('
name|'version'
op|')'
newline|'\n'
name|'generator'
op|'.'
name|'run'
op|'('
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
