begin_unit
comment|'#!/usr/bin/env python'
nl|'\n'
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2010 Openstack, LLC.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License");'
nl|'\n'
comment|'#    you may not use this file except in compliance with the License.'
nl|'\n'
comment|'#    You may obtain a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#        http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS,'
nl|'\n'
comment|'#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
nl|'\n'
comment|'#    See the License for the specific language governing permissions and'
nl|'\n'
comment|'#    limitations under the License.'
nl|'\n'
nl|'\n'
string|'"""Module for VNC Proxying."""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'flags'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|FLAGS
name|'FLAGS'
op|'='
name|'flags'
op|'.'
name|'FLAGS'
newline|'\n'
name|'flags'
op|'.'
name|'DEFINE_string'
op|'('
string|"'novncproxy_base_url'"
op|','
nl|'\n'
string|"'http://127.0.0.1:6080/vnc_auto.html'"
op|','
nl|'\n'
string|'\'location of vnc console proxy, \\\n                    in the form "http://127.0.0.1:6080/vnc_auto.html"\''
op|')'
newline|'\n'
name|'flags'
op|'.'
name|'DEFINE_string'
op|'('
string|"'xvpvncproxy_base_url'"
op|','
nl|'\n'
string|"'http://127.0.0.1:6081/console'"
op|','
nl|'\n'
string|'\'location of nova xvp vnc console proxy, \\\n                    in the form "http://127.0.0.1:6081/console"\''
op|')'
newline|'\n'
name|'flags'
op|'.'
name|'DEFINE_string'
op|'('
string|"'vncserver_listen'"
op|','
string|"'127.0.0.1'"
op|','
nl|'\n'
string|"'Ip address on which instance vncservers\\\n                     should listen'"
op|')'
newline|'\n'
name|'flags'
op|'.'
name|'DEFINE_string'
op|'('
string|"'vncserver_proxyclient_address'"
op|','
string|"'127.0.0.1'"
op|','
nl|'\n'
string|"'the address to which proxy clients \\\n                    (like nova-xvpvncproxy) should connect'"
op|')'
newline|'\n'
name|'flags'
op|'.'
name|'DEFINE_bool'
op|'('
string|"'vnc_enabled'"
op|','
name|'True'
op|','
nl|'\n'
string|"'enable vnc related features'"
op|')'
newline|'\n'
name|'flags'
op|'.'
name|'DEFINE_string'
op|'('
string|"'vnc_keymap'"
op|','
string|"'en-us'"
op|','
nl|'\n'
string|"'keymap for vnc'"
op|')'
newline|'\n'
endmarker|''
end_unit
