begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
op|'*'
newline|'\n'
name|'from'
name|'migrate'
name|'import'
op|'*'
newline|'\n'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'log'
name|'as'
name|'logging'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|meta
name|'meta'
op|'='
name|'MetaData'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# New Tables'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Here are the old static instance types'
nl|'\n'
comment|'# INSTANCE_TYPES = {'
nl|'\n'
comment|"# 'm1.tiny': dict(memory_mb=512, vcpus=1, local_gb=0, flavorid=1),"
nl|'\n'
comment|"# 'm1.small': dict(memory_mb=2048, vcpus=1, local_gb=20, flavorid=2),"
nl|'\n'
comment|"# 'm1.medium': dict(memory_mb=4096, vcpus=2, local_gb=40, flavorid=3),"
nl|'\n'
comment|"# 'm1.large': dict(memory_mb=8192, vcpus=4, local_gb=80, flavorid=4),"
nl|'\n'
comment|"# 'm1.xlarge': dict(memory_mb=16384, vcpus=8, local_gb=160, flavorid=5)}"
nl|'\n'
DECL|variable|instance_types
name|'instance_types'
op|'='
name|'Table'
op|'('
string|"'instance_types'"
op|','
name|'meta'
op|','
nl|'\n'
name|'Column'
op|'('
string|"'created_at'"
op|','
name|'DateTime'
op|'('
name|'timezone'
op|'='
name|'False'
op|')'
op|')'
op|','
nl|'\n'
name|'Column'
op|'('
string|"'deleted_at'"
op|','
name|'DateTime'
op|'('
name|'timezone'
op|'='
name|'False'
op|')'
op|')'
op|','
nl|'\n'
name|'Column'
op|'('
string|"'deleted'"
op|','
name|'Boolean'
op|'('
name|'create_constraint'
op|'='
name|'True'
op|','
name|'name'
op|'='
name|'None'
op|')'
op|')'
op|','
nl|'\n'
name|'Column'
op|'('
string|"'id'"
op|','
name|'Integer'
op|'('
op|')'
op|','
name|'primary_key'
op|'='
name|'True'
op|','
name|'nullable'
op|'='
name|'False'
op|')'
op|','
nl|'\n'
name|'Column'
op|'('
string|"'memory_mb'"
op|','
name|'Integer'
op|'('
op|')'
op|','
name|'nullable'
op|'='
name|'False'
op|')'
op|','
nl|'\n'
name|'Column'
op|'('
string|"'vcpus'"
op|','
name|'Integer'
op|'('
op|')'
op|','
name|'nullable'
op|'='
name|'False'
op|')'
op|','
nl|'\n'
name|'Column'
op|'('
string|"'local_gb'"
op|','
name|'Integer'
op|'('
op|')'
op|','
name|'nullable'
op|'='
name|'False'
op|')'
op|','
nl|'\n'
name|'Column'
op|'('
string|"'flavorid'"
op|','
name|'Integer'
op|'('
op|')'
op|','
name|'nullable'
op|'='
name|'False'
op|')'
op|','
nl|'\n'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
comment|'# Upgrade operations go here'
nl|'\n'
comment|"# Don't create your own engine; bind migrate_engine"
nl|'\n'
comment|'# to your metadata'
nl|'\n'
indent|'    '
name|'meta'
op|'.'
name|'bind'
op|'='
name|'migrate_engine'
newline|'\n'
name|'try'
op|':'
newline|'\n'
indent|'        '
name|'instance_types'
op|'.'
name|'create'
op|'('
op|')'
newline|'\n'
dedent|''
name|'except'
name|'Exception'
op|':'
newline|'\n'
indent|'        '
name|'logging'
op|'.'
name|'info'
op|'('
name|'repr'
op|'('
name|'table'
op|')'
op|')'
newline|'\n'
name|'logging'
op|'.'
name|'exception'
op|'('
string|"'Exception while creating table'"
op|')'
newline|'\n'
name|'raise'
newline|'\n'
nl|'\n'
comment|'# TODO(ken-pepple) fix this to pre-populate the default EC2 types'
nl|'\n'
comment|'#INSTANCE_TYPES = {'
nl|'\n'
comment|"#    'm1.tiny': dict(memory_mb=512, vcpus=1, local_gb=0, flavorid=1),"
nl|'\n'
comment|"#    'm1.small': dict(memory_mb=2048, vcpus=1, local_gb=20, flavorid=2),"
nl|'\n'
comment|"#    'm1.medium': dict(memory_mb=4096, vcpus=2, local_gb=40, flavorid=3),"
nl|'\n'
comment|"#    'm1.large': dict(memory_mb=8192, vcpus=4, local_gb=80, flavorid=4),"
nl|'\n'
comment|"#    'm1.xlarge': dict(memory_mb=16384, vcpus=8, local_gb=160, flavorid=5)}"
nl|'\n'
comment|'# for instance_type in INSTANCE_TYPES:'
nl|'\n'
comment|'#\ttry:'
nl|'\n'
comment|'# prepopulate tables with EC2 types'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|function|downgrade
dedent|''
dedent|''
name|'def'
name|'downgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
comment|'# Operations to reverse the above upgrade go here.'
nl|'\n'
comment|'#    # Operations to reverse the above upgrade go here.'
nl|'\n'
comment|'#    for table in (instance_types):'
nl|'\n'
comment|'#        table.drop()'
nl|'\n'
indent|'    '
name|'pass'
newline|'\n'
dedent|''
endmarker|''
end_unit
