begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2011 OpenStack LLC.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
name|'MetaData'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
comment|"# Upgrade operations go here. Don't create your own engine;"
nl|'\n'
comment|'# bind migrate_engine to your metadata'
nl|'\n'
nl|'\n'
indent|'    '
name|'tables'
op|'='
op|'['
string|'"agent_builds"'
op|','
string|'"aggregate_hosts"'
op|','
string|'"aggregate_metadata"'
op|','
nl|'\n'
string|'"aggregates"'
op|','
string|'"block_device_mapping"'
op|','
string|'"bw_usage_cache"'
op|','
nl|'\n'
string|'"dns_domains"'
op|','
string|'"instance_faults"'
op|','
string|'"instance_type_extra_specs"'
op|','
nl|'\n'
string|'"provider_fw_rules"'
op|','
string|'"quota_classes"'
op|','
string|'"s3_images"'
op|','
nl|'\n'
string|'"sm_backend_config"'
op|','
string|'"sm_flavors"'
op|','
string|'"sm_volume"'
op|','
nl|'\n'
string|'"virtual_storage_arrays"'
op|','
string|'"volume_metadata"'
op|','
nl|'\n'
string|'"volume_type_extra_specs"'
op|','
string|'"volume_types"'
op|']'
newline|'\n'
nl|'\n'
name|'meta'
op|'='
name|'MetaData'
op|'('
op|')'
newline|'\n'
name|'meta'
op|'.'
name|'bind'
op|'='
name|'migrate_engine'
newline|'\n'
name|'if'
name|'migrate_engine'
op|'.'
name|'name'
op|'=='
string|'"mysql"'
op|':'
newline|'\n'
indent|'        '
name|'d'
op|'='
name|'migrate_engine'
op|'.'
name|'execute'
op|'('
string|'"SHOW TABLE STATUS WHERE Engine!=\'InnoDB\';"'
op|')'
newline|'\n'
name|'for'
name|'row'
name|'in'
name|'d'
op|'.'
name|'fetchall'
op|'('
op|')'
op|':'
newline|'\n'
indent|'            '
name|'table_name'
op|'='
name|'row'
op|'['
number|'0'
op|']'
newline|'\n'
name|'if'
name|'table_name'
name|'in'
name|'tables'
op|':'
newline|'\n'
indent|'                '
name|'migrate_engine'
op|'.'
name|'execute'
op|'('
string|'"ALTER TABLE %s Engine=InnoDB"'
op|'%'
nl|'\n'
name|'table_name'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|downgrade
dedent|''
dedent|''
dedent|''
dedent|''
name|'def'
name|'downgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'pass'
newline|'\n'
dedent|''
endmarker|''
end_unit
