begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2012 Red Hat, Inc.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
name|'MetaData'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'meta'
op|'='
name|'MetaData'
op|'('
op|')'
newline|'\n'
name|'meta'
op|'.'
name|'bind'
op|'='
name|'migrate_engine'
newline|'\n'
nl|'\n'
comment|'# NOTE(dprince): Remove unused snapshots/volumes sequences.'
nl|'\n'
comment|'# These are leftovers from the ID --> UUID conversion for these tables'
nl|'\n'
comment|'# that occurred in Folsom.'
nl|'\n'
name|'if'
name|'migrate_engine'
op|'.'
name|'name'
op|'=='
string|'"postgresql"'
op|':'
newline|'\n'
indent|'        '
name|'base_query'
op|'='
string|'"""SELECT COUNT(*) FROM pg_class c\n                     WHERE c.relkind = \'S\'\n                     AND relname = \'%s\';"""'
newline|'\n'
name|'result'
op|'='
name|'migrate_engine'
op|'.'
name|'execute'
op|'('
name|'base_query'
op|'%'
string|'"snapshots_id_seq"'
op|')'
newline|'\n'
name|'if'
name|'result'
op|'.'
name|'scalar'
op|'('
op|')'
op|'>'
number|'0'
op|':'
newline|'\n'
indent|'            '
name|'sql'
op|'='
string|'"DROP SEQUENCE snapshots_id_seq CASCADE;"'
newline|'\n'
name|'migrate_engine'
op|'.'
name|'execute'
op|'('
name|'sql'
op|')'
newline|'\n'
nl|'\n'
dedent|''
name|'result'
op|'='
name|'migrate_engine'
op|'.'
name|'execute'
op|'('
name|'base_query'
op|'%'
string|'"volumes_id_seq"'
op|')'
newline|'\n'
name|'if'
name|'result'
op|'.'
name|'scalar'
op|'('
op|')'
op|'>'
number|'0'
op|':'
newline|'\n'
indent|'            '
name|'sql'
op|'='
string|'"DROP SEQUENCE volumes_id_seq CASCADE;"'
newline|'\n'
name|'migrate_engine'
op|'.'
name|'execute'
op|'('
name|'sql'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|downgrade
dedent|''
dedent|''
dedent|''
name|'def'
name|'downgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'meta'
op|'='
name|'MetaData'
op|'('
op|')'
newline|'\n'
name|'meta'
op|'.'
name|'bind'
op|'='
name|'migrate_engine'
newline|'\n'
nl|'\n'
name|'if'
name|'migrate_engine'
op|'.'
name|'name'
op|'=='
string|'"postgresql"'
op|':'
newline|'\n'
indent|'        '
name|'sql'
op|'='
string|'"""CREATE SEQUENCE snapshots_id_seq START WITH 1 INCREMENT BY 1\n              NO MINVALUE NO MAXVALUE CACHE 1;\n              ALTER SEQUENCE snapshots_id_seq OWNED BY snapshots.id;\n              SELECT pg_catalog.setval(\'snapshots_id_seq\', 1, false);\n              ALTER TABLE ONLY snapshots ALTER COLUMN id SET DEFAULT\n              nextval(\'snapshots_id_seq\'::regclass);"""'
newline|'\n'
nl|'\n'
name|'sql'
op|'+='
string|'"""CREATE SEQUENCE volumes_id_seq START WITH 1 INCREMENT BY 1\n               NO MINVALUE NO MAXVALUE CACHE 1;\n               ALTER SEQUENCE volumes_id_seq OWNED BY volumes.id;\n               SELECT pg_catalog.setval(\'volumes_id_seq\', 1, false);\n               ALTER TABLE ONLY volumes ALTER COLUMN id SET DEFAULT\n               nextval(\'volumes_id_seq\'::regclass);"""'
newline|'\n'
name|'migrate_engine'
op|'.'
name|'execute'
op|'('
name|'sql'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
