begin_unit
comment|'# Copyright 2013 Rackspace Hosting'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'sqlalchemy'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'meta'
op|'='
name|'sqlalchemy'
op|'.'
name|'MetaData'
op|'('
op|')'
newline|'\n'
name|'meta'
op|'.'
name|'bind'
op|'='
name|'migrate_engine'
newline|'\n'
name|'sys_meta'
op|'='
name|'sqlalchemy'
op|'.'
name|'Table'
op|'('
string|"'instance_system_metadata'"
op|','
name|'meta'
op|','
nl|'\n'
name|'autoload'
op|'='
name|'True'
op|')'
newline|'\n'
comment|'# is None does not work here.'
nl|'\n'
name|'sys_meta'
op|'.'
name|'update'
op|'('
op|')'
op|'.'
name|'where'
op|'('
name|'sys_meta'
op|'.'
name|'c'
op|'.'
name|'deleted'
op|'=='
name|'None'
op|')'
op|'.'
name|'values'
op|'('
name|'deleted'
op|'='
number|'0'
op|')'
op|'.'
name|'execute'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|downgrade
dedent|''
name|'def'
name|'downgrade'
op|'('
name|'migration_engine'
op|')'
op|':'
newline|'\n'
comment|"# This migration only corrects NULL to be 0.  There's no action to"
nl|'\n'
comment|'# revert this.'
nl|'\n'
indent|'    '
name|'pass'
newline|'\n'
dedent|''
endmarker|''
end_unit
