begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2013 OpenStack Foundation'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# This migration adds the availability_zone to the volume_usage_cache table.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# This table keeps a cache of the volume usage. Every minute (or what ever'
nl|'\n'
comment|'# is configured for volume_usage_poll_interval value) one row in this table'
nl|'\n'
comment|'# gets updated for each attached volume. After this patch is applied, for'
nl|'\n'
comment|'# any currently attached volumes, the value will immediately be null, but'
nl|'\n'
comment|'# will get updated to the correct value on the next tick of the volume'
nl|'\n'
comment|'# usage poll.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# The volume usage poll function is the only code to access this table. The'
nl|'\n'
comment|'# sequence of operation in that function is to first update the field with'
nl|'\n'
comment|'# the correct value and then to pass the updated data to the consumer.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Hence this new column does not need to be pre-populated.'
nl|'\n'
comment|'#'
nl|'\n'
nl|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
name|'MetaData'
op|','
name|'String'
op|','
name|'Table'
op|','
name|'Column'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
name|'import'
name|'log'
name|'as'
name|'logging'
newline|'\n'
nl|'\n'
DECL|variable|LOG
name|'LOG'
op|'='
name|'logging'
op|'.'
name|'getLogger'
op|'('
name|'__name__'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'meta'
op|'='
name|'MetaData'
op|'('
op|')'
newline|'\n'
name|'meta'
op|'.'
name|'bind'
op|'='
name|'migrate_engine'
newline|'\n'
nl|'\n'
name|'volume_usage_cache'
op|'='
name|'Table'
op|'('
string|"'volume_usage_cache'"
op|','
name|'meta'
op|','
name|'autoload'
op|'='
name|'True'
op|')'
newline|'\n'
name|'availability_zone'
op|'='
name|'Column'
op|'('
string|"'availability_zone'"
op|','
name|'String'
op|'('
number|'255'
op|')'
op|')'
newline|'\n'
name|'volume_usage_cache'
op|'.'
name|'create_column'
op|'('
name|'availability_zone'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|downgrade
dedent|''
name|'def'
name|'downgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'meta'
op|'='
name|'MetaData'
op|'('
op|')'
newline|'\n'
name|'meta'
op|'.'
name|'bind'
op|'='
name|'migrate_engine'
newline|'\n'
nl|'\n'
name|'volume_usage_cache'
op|'='
name|'Table'
op|'('
string|"'volume_usage_cache'"
op|','
name|'meta'
op|','
name|'autoload'
op|'='
name|'True'
op|')'
newline|'\n'
name|'volume_usage_cache'
op|'.'
name|'drop_column'
op|'('
string|"'availability_zone'"
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
