begin_unit
comment|'# Copyright 2013 IBM Corp.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migration_engine'
op|')'
op|':'
newline|'\n'
comment|'# Soft-delete all compute node stats whose corresponding compute node has'
nl|'\n'
comment|'# been deleted. Using "straight SQL" here as this will be a lot faster than'
nl|'\n'
comment|'# issuing individual updates for each (deleted) compute node.'
nl|'\n'
indent|'    '
name|'conn'
op|'='
name|'migration_engine'
op|'.'
name|'connect'
op|'('
op|')'
newline|'\n'
name|'result'
op|'='
name|'conn'
op|'.'
name|'execute'
op|'('
nl|'\n'
string|"'update compute_node_stats set deleted = id, '"
nl|'\n'
string|"'deleted_at = current_timestamp where compute_node_id not in '"
nl|'\n'
string|"'(select id from compute_nodes where deleted <> 0)'"
op|')'
newline|'\n'
name|'result'
op|'.'
name|'close'
op|'('
op|')'
newline|'\n'
name|'conn'
op|'.'
name|'close'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|downgrade
dedent|''
name|'def'
name|'downgrade'
op|'('
name|'migration_engine'
op|')'
op|':'
newline|'\n'
comment|"# This migration fixes compute nodes' stats. No need to go back and reverse"
nl|'\n'
comment|'# this change.'
nl|'\n'
indent|'    '
name|'pass'
newline|'\n'
dedent|''
endmarker|''
end_unit
