begin_unit
comment|'# Copyright 2013 NEC Corporation'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
name|'MetaData'
op|','
name|'String'
op|','
name|'Table'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'meta'
op|'='
name|'MetaData'
op|'('
name|'bind'
op|'='
name|'migrate_engine'
op|')'
newline|'\n'
name|'table'
op|'='
name|'Table'
op|'('
string|"'project_user_quotas'"
op|','
name|'meta'
op|','
name|'autoload'
op|'='
name|'True'
op|')'
newline|'\n'
name|'col_resource'
op|'='
name|'getattr'
op|'('
name|'table'
op|'.'
name|'c'
op|','
string|"'resource'"
op|')'
newline|'\n'
nl|'\n'
name|'if'
name|'col_resource'
op|'.'
name|'type'
op|'.'
name|'length'
op|'=='
number|'25'
op|':'
newline|'\n'
comment|'# The resource of project_user_quotas table had been changed to'
nl|'\n'
comment|'# invalid length(25) since I56ad98d3702f53fe8cfa94093fea89074f7a5e90.'
nl|'\n'
comment|'# The following code fixes the length for the environments which are'
nl|'\n'
comment|'# deployed after I56ad98d3702f53fe8cfa94093fea89074f7a5e90.'
nl|'\n'
indent|'        '
name|'col_resource'
op|'.'
name|'alter'
op|'('
name|'type'
op|'='
name|'String'
op|'('
number|'255'
op|')'
op|')'
newline|'\n'
name|'table'
op|'.'
name|'update'
op|'('
op|')'
op|'.'
name|'where'
op|'('
name|'table'
op|'.'
name|'c'
op|'.'
name|'resource'
op|'=='
string|"'injected_file_content_byt'"
op|')'
op|'.'
name|'values'
op|'('
name|'resource'
op|'='
string|"'injected_file_content_bytes'"
op|')'
op|'.'
name|'execute'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|downgrade
dedent|''
dedent|''
name|'def'
name|'downgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
comment|'# This migration fixes the resource of project_user_quotas table.'
nl|'\n'
comment|'# No need to go back and reverse this change.'
nl|'\n'
indent|'    '
name|'pass'
newline|'\n'
dedent|''
endmarker|''
end_unit
