begin_unit
comment|'# Copyright (c) 2014 Rackspace Hosting'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
name|'Column'
newline|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
name|'MetaData'
newline|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
name|'Table'
newline|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
name|'Text'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'engine'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'meta'
op|'='
name|'MetaData'
op|'('
op|')'
newline|'\n'
name|'meta'
op|'.'
name|'bind'
op|'='
name|'engine'
newline|'\n'
nl|'\n'
comment|"# Drop the compute_node_stats table and add a 'stats' column to"
nl|'\n'
comment|"# compute_nodes directly.  The data itself is transient and doesn't"
nl|'\n'
comment|'# need to be copied over.'
nl|'\n'
name|'table_names'
op|'='
op|'('
string|"'compute_node_stats'"
op|','
string|"'shadow_compute_node_stats'"
op|')'
newline|'\n'
name|'for'
name|'table_name'
name|'in'
name|'table_names'
op|':'
newline|'\n'
indent|'        '
name|'table'
op|'='
name|'Table'
op|'('
name|'table_name'
op|','
name|'meta'
op|','
name|'autoload'
op|'='
name|'True'
op|')'
newline|'\n'
name|'table'
op|'.'
name|'drop'
op|'('
op|')'
newline|'\n'
nl|'\n'
comment|'# Add a new stats column to compute nodes'
nl|'\n'
dedent|''
name|'table_names'
op|'='
op|'('
string|"'compute_nodes'"
op|','
string|"'shadow_compute_nodes'"
op|')'
newline|'\n'
name|'for'
name|'table_name'
name|'in'
name|'table_names'
op|':'
newline|'\n'
indent|'        '
name|'table'
op|'='
name|'Table'
op|'('
name|'table_name'
op|','
name|'meta'
op|','
name|'autoload'
op|'='
name|'True'
op|')'
newline|'\n'
name|'stats'
op|'='
name|'Column'
op|'('
string|"'stats'"
op|','
name|'Text'
op|','
name|'default'
op|'='
string|"'{}'"
op|')'
newline|'\n'
name|'table'
op|'.'
name|'create_column'
op|'('
name|'stats'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
