begin_unit
comment|'# Copyright 2014 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
name|'MetaData'
op|','
name|'Table'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'meta'
op|'='
name|'MetaData'
op|'('
name|'bind'
op|'='
name|'migrate_engine'
op|')'
newline|'\n'
nl|'\n'
name|'quota_usages'
op|'='
name|'Table'
op|'('
string|"'quota_usages'"
op|','
name|'meta'
op|','
name|'autoload'
op|'='
name|'True'
op|')'
newline|'\n'
name|'quota_usages'
op|'.'
name|'c'
op|'.'
name|'resource'
op|'.'
name|'alter'
op|'('
name|'nullable'
op|'='
name|'False'
op|')'
newline|'\n'
nl|'\n'
name|'pci_devices'
op|'='
name|'Table'
op|'('
string|"'pci_devices'"
op|','
name|'meta'
op|','
name|'autoload'
op|'='
name|'True'
op|')'
newline|'\n'
comment|'# NOTE(mriedem): The deleted column is in a UniqueConstraint so making'
nl|'\n'
comment|'# it nullable breaks DB2 with an SQL0542N error, so skip for DB2. There is'
nl|'\n'
comment|"# a FKey in 246 so we're kind of stuck with DB2 since we can't create the"
nl|'\n'
comment|"# FKey without the unique constraint and we can't have a unique constraint"
nl|'\n'
comment|'# on a nullable column.'
nl|'\n'
comment|'# TODO(mriedem): Revisit this once the deleted column (inherited from the'
nl|'\n'
comment|'# SoftDeleteMixin in oslo.db) is non-null on all tables, which is going'
nl|'\n'
comment|'# to be a non-trivial effort.'
nl|'\n'
name|'if'
name|'migrate_engine'
op|'.'
name|'name'
op|'!='
string|"'ibm_db_sa'"
op|':'
newline|'\n'
indent|'        '
name|'pci_devices'
op|'.'
name|'c'
op|'.'
name|'deleted'
op|'.'
name|'alter'
op|'('
name|'nullable'
op|'='
name|'True'
op|')'
newline|'\n'
dedent|''
name|'pci_devices'
op|'.'
name|'c'
op|'.'
name|'product_id'
op|'.'
name|'alter'
op|'('
name|'nullable'
op|'='
name|'False'
op|')'
newline|'\n'
name|'pci_devices'
op|'.'
name|'c'
op|'.'
name|'vendor_id'
op|'.'
name|'alter'
op|'('
name|'nullable'
op|'='
name|'False'
op|')'
newline|'\n'
name|'pci_devices'
op|'.'
name|'c'
op|'.'
name|'dev_type'
op|'.'
name|'alter'
op|'('
name|'nullable'
op|'='
name|'False'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
