begin_unit
comment|'# Copyright 2014 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
name|'from'
name|'sqlalchemy'
name|'import'
name|'MetaData'
op|','
name|'Table'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|INDEXES
name|'INDEXES'
op|'='
op|'['
nl|'\n'
comment|'# subset of instances_host_deleted_cleaned_idx'
nl|'\n'
op|'('
string|"'instances'"
op|','
string|"'instances_host_deleted_idx'"
op|')'
op|','
nl|'\n'
comment|'# subset of iscsi_targets_host_volume_id_deleted_idx'
nl|'\n'
op|'('
string|"'iscsi_targets'"
op|','
string|"'iscsi_targets_host_idx'"
op|')'
op|','
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Remove index that are subsets of other indexes."""'
newline|'\n'
nl|'\n'
name|'meta'
op|'='
name|'MetaData'
op|'('
name|'bind'
op|'='
name|'migrate_engine'
op|')'
newline|'\n'
nl|'\n'
name|'for'
name|'table_name'
op|','
name|'index_name'
name|'in'
name|'INDEXES'
op|':'
newline|'\n'
indent|'        '
name|'table'
op|'='
name|'Table'
op|'('
name|'table_name'
op|','
name|'meta'
op|','
name|'autoload'
op|'='
name|'True'
op|')'
newline|'\n'
name|'for'
name|'index'
name|'in'
name|'table'
op|'.'
name|'indexes'
op|':'
newline|'\n'
indent|'            '
name|'if'
name|'index'
op|'.'
name|'name'
op|'=='
name|'index_name'
op|':'
newline|'\n'
indent|'                '
name|'index'
op|'.'
name|'drop'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|downgrade
dedent|''
dedent|''
dedent|''
dedent|''
name|'def'
name|'downgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
comment|'# Unnecessary to re-add duplicated index when downgrading'
nl|'\n'
indent|'    '
name|'pass'
newline|'\n'
dedent|''
endmarker|''
end_unit
