begin_unit
comment|'# Copyright (c) 2015 Cloudbase Solutions SRL'
nl|'\n'
comment|'# All Rights Reserved'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
comment|'# NOTE(mikal): this migration number exists like this because change'
nl|'\n'
comment|'# I506dd1c8d0f0a877fdfc1a4ed11a8830d9600b98 needs to revert the hyper-v'
nl|'\n'
comment|'# keypair change, but we promise that we will never remove a schema migration'
nl|'\n'
comment|'# version. Instead, we replace this migration with a noop.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# It is hypothetically possible that a hyper-v continuous deployer exists who'
nl|'\n'
comment|'# will have a poor experience because of this code revert, if that deployer'
nl|'\n'
comment|'# is you, please contact the nova team at openstack-dev@lists.openstack.org'
nl|'\n'
comment|'# and we will walk you through the manual fix required for this problem.'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'pass'
newline|'\n'
dedent|''
endmarker|''
end_unit
