begin_unit
comment|'# Copyright 2015 Huawei.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_db'
op|'.'
name|'sqlalchemy'
name|'import'
name|'utils'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|INDEX_COLUMNS
name|'INDEX_COLUMNS'
op|'='
op|'['
string|"'instance_uuid'"
op|']'
newline|'\n'
comment|'# using the index name same with mysql'
nl|'\n'
DECL|variable|INDEX_NAME
name|'INDEX_NAME'
op|'='
string|"'instance_uuid'"
newline|'\n'
DECL|variable|SYS_META_TABLE_NAME
name|'SYS_META_TABLE_NAME'
op|'='
string|"'instance_system_metadata'"
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|upgrade
name|'def'
name|'upgrade'
op|'('
name|'migrate_engine'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Add instance_system_metadata indexes missing on PostgreSQL and other DB.\n    """'
newline|'\n'
nl|'\n'
comment|'# This index was already added by migration 216 for MySQL'
nl|'\n'
name|'if'
name|'migrate_engine'
op|'.'
name|'name'
op|'!='
string|"'mysql'"
op|':'
newline|'\n'
comment|'# Adds index for PostgreSQL and other DB'
nl|'\n'
indent|'        '
name|'if'
name|'not'
name|'utils'
op|'.'
name|'index_exists'
op|'('
name|'migrate_engine'
op|','
name|'SYS_META_TABLE_NAME'
op|','
nl|'\n'
name|'INDEX_NAME'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'utils'
op|'.'
name|'add_index'
op|'('
name|'migrate_engine'
op|','
name|'SYS_META_TABLE_NAME'
op|','
name|'INDEX_NAME'
op|','
nl|'\n'
name|'INDEX_COLUMNS'
op|')'
newline|'\n'
dedent|''
dedent|''
dedent|''
endmarker|''
end_unit
