begin_unit
comment|'#  Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#  not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#  a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#       http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#  Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#  License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#  under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_log'
name|'import'
name|'log'
name|'as'
name|'logging'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'i18n'
name|'import'
name|'_LW'
newline|'\n'
nl|'\n'
DECL|variable|LOG
name|'LOG'
op|'='
name|'logging'
op|'.'
name|'getLogger'
op|'('
name|'__name__'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_domain_info
name|'def'
name|'get_domain_info'
op|'('
name|'libvirt'
op|','
name|'host'
op|','
name|'virt_dom'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Method virDomain.info (libvirt version < 1.2.11) is\n    affected by a race condition. See bug #1372670 for more details.\n    This method detects it to perform a retry.\n    """'
newline|'\n'
DECL|function|is_race
name|'def'
name|'is_race'
op|'('
name|'e'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'code'
op|'='
name|'e'
op|'.'
name|'get_error_code'
op|'('
op|')'
newline|'\n'
name|'message'
op|'='
name|'e'
op|'.'
name|'get_error_message'
op|'('
op|')'
newline|'\n'
name|'return'
op|'('
name|'code'
op|'=='
name|'libvirt'
op|'.'
name|'VIR_ERR_OPERATION_FAILED'
name|'and'
nl|'\n'
string|"'cannot read cputime for domain'"
name|'in'
name|'message'
op|')'
newline|'\n'
nl|'\n'
dedent|''
name|'try'
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'virt_dom'
op|'.'
name|'info'
op|'('
op|')'
newline|'\n'
dedent|''
name|'except'
name|'libvirt'
op|'.'
name|'libvirtError'
name|'as'
name|'e'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'not'
name|'host'
op|'.'
name|'has_min_version'
op|'('
op|'('
number|'1'
op|','
number|'2'
op|','
number|'11'
op|')'
op|')'
name|'and'
name|'is_race'
op|'('
name|'e'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'LOG'
op|'.'
name|'warning'
op|'('
name|'_LW'
op|'('
string|"'Race detected in libvirt.virDomain.info, '"
nl|'\n'
string|"'trying one more time'"
op|')'
op|')'
newline|'\n'
name|'return'
name|'virt_dom'
op|'.'
name|'info'
op|'('
op|')'
newline|'\n'
dedent|''
name|'raise'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
