begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2012 NetApp, Inc.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Deprecated file, kept for back-compat only. To be removed in Hxxxx."""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
name|'import'
name|'log'
name|'as'
name|'logging'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'virt'
op|'.'
name|'libvirt'
name|'import'
name|'volume'
newline|'\n'
nl|'\n'
DECL|variable|LOG
name|'LOG'
op|'='
name|'logging'
op|'.'
name|'getLogger'
op|'('
name|'__name__'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NfsVolumeDriver
name|'class'
name|'NfsVolumeDriver'
op|'('
name|'volume'
op|'.'
name|'LibvirtNFSVolumeDriver'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Deprecated driver for NFS, renamed to LibvirtNFSVolumeDriver\n       and moved into the main volume.py module. Kept for backwards\n       compatibility in the Grizzly cycle to give users opportunity\n       to configure before its removal in the Hxxxx cycle."""'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'super'
op|'('
name|'NfsVolumeDriver'
op|','
nl|'\n'
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
newline|'\n'
name|'LOG'
op|'.'
name|'deprecated'
op|'('
nl|'\n'
name|'_'
op|'('
string|'"The nova.virt.libvirt.volume_nfs.NfsVolumeDriver "'
nl|'\n'
string|'"class is deprecated and will be removed in the "'
nl|'\n'
string|'"Hxxxx release. Please update nova.conf so that "'
nl|'\n'
string|'"the \'libvirt_volume_drivers\' parameter refers to "'
nl|'\n'
string|'"nova.virt.libvirt.volume.LibvirtNFSVolumeDriver."'
op|')'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
