begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2011 University of Southern California'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
comment|'#'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_baremetal_nodes
name|'def'
name|'get_baremetal_nodes'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'BareMetalNodes'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|BareMetalNodes
dedent|''
name|'class'
name|'BareMetalNodes'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""\n    This manages node information and implements singleton.\n\n    BareMetalNodes class handles machine architectures of interest to\n    technical computing users have either poor or non-existent support\n    for virtualization.\n    """'
newline|'\n'
nl|'\n'
DECL|member|get_hw_info
name|'def'
name|'get_hw_info'
op|'('
name|'self'
op|','
name|'field'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Returns hardware information of bare-metal node by the given field.\n\n        Given field can be vcpus, memory_mb, local_gb, memory_mb_used,\n        local_gb_used, hypervisor_type, hypervisor_version, and cpu_info.\n        """'
newline|'\n'
name|'return'
string|'"fake"'
newline|'\n'
nl|'\n'
DECL|member|set_status
dedent|''
name|'def'
name|'set_status'
op|'('
name|'self'
op|','
name|'node_id'
op|','
name|'status'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Sets status of the given node by the given status.\n\n        Returns 1 if the node is in the nodes list.\n        """'
newline|'\n'
name|'return'
name|'True'
newline|'\n'
nl|'\n'
DECL|member|get_status
dedent|''
name|'def'
name|'get_status'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Gets status of the given node.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|get_idle_node
dedent|''
name|'def'
name|'get_idle_node'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Gets an idle node, sets the status as 1 (RUNNING) and Returns node ID.\n        """'
newline|'\n'
name|'return'
name|'False'
newline|'\n'
nl|'\n'
DECL|member|get_ip_by_id
dedent|''
name|'def'
name|'get_ip_by_id'
op|'('
name|'self'
op|','
name|'id'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Returns default IP address of the given node.\n        """'
newline|'\n'
name|'return'
string|'"127.0.0.1"'
newline|'\n'
nl|'\n'
DECL|member|free_node
dedent|''
name|'def'
name|'free_node'
op|'('
name|'self'
op|','
name|'node_id'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Sets/frees status of the given node as 0 (IDLE).\n        """'
newline|'\n'
name|'return'
name|'False'
newline|'\n'
nl|'\n'
DECL|member|power_mgr
dedent|''
name|'def'
name|'power_mgr'
op|'('
name|'self'
op|','
name|'node_id'
op|','
name|'mode'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Changes power state of the given node.\n\n        According to the mode (1-ON, 2-OFF, 3-REBOOT), power state can be\n        changed. /tftpboot/pdu_mgr script handles power management of\n        PDU (Power Distribution Unit).\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|deactivate_node
dedent|''
name|'def'
name|'deactivate_node'
op|'('
name|'self'
op|','
name|'node_id'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Deactivates the given node by turnning it off.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|network_set
dedent|''
name|'def'
name|'network_set'
op|'('
name|'self'
op|','
name|'node_ip'
op|','
name|'mac_address'
op|','
name|'ip_address'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Sets network configuration based on the given ip and mac address.\n\n        User can access the bare-metal node using ssh.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|iptables_set
dedent|''
name|'def'
name|'iptables_set'
op|'('
name|'self'
op|','
name|'node_ip'
op|','
name|'user_data'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Sets security setting (iptables:port) if needed.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|check_activated
dedent|''
name|'def'
name|'check_activated'
op|'('
name|'self'
op|','
name|'node_id'
op|','
name|'node_ip'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Checks whether the given node is activated or not.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|vmlinux_set
dedent|''
name|'def'
name|'vmlinux_set'
op|'('
name|'self'
op|','
name|'node_id'
op|','
name|'mode'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Sets kernel into default path (/tftpboot) if needed.\n\n        From basepath to /tftpboot, kernel is set based on the given mode\n        such as 0-NoSet, 1-SetVmlinux, or 9-RemoveVmlinux.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|sleep_mgr
dedent|''
name|'def'
name|'sleep_mgr'
op|'('
name|'self'
op|','
name|'time'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Sleeps until the node is activated.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|ssh_set
dedent|''
name|'def'
name|'ssh_set'
op|'('
name|'self'
op|','
name|'node_ip'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Sets and Runs sshd in the node.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|activate_node
dedent|''
name|'def'
name|'activate_node'
op|'('
name|'self'
op|','
name|'node_id'
op|','
name|'node_ip'
op|','
name|'name'
op|','
name|'mac_address'
op|','
nl|'\n'
name|'ip_address'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Activates the given node using ID, IP, and MAC address.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|get_console_output
dedent|''
name|'def'
name|'get_console_output'
op|'('
name|'self'
op|','
name|'console_log'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Gets console output of the given node.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|get_image
dedent|''
name|'def'
name|'get_image'
op|'('
name|'self'
op|','
name|'bp'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Gets the bare-metal file system image into the instance path.\n\n        Noting to do for tilera nodes: actual image is used.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|set_image
dedent|''
name|'def'
name|'set_image'
op|'('
name|'self'
op|','
name|'bpath'
op|','
name|'node_id'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Sets the PXE bare-metal file system from the instance path.\n\n        This should be done after ssh key is injected.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
