begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2012 Hewlett-Packard Development Company, L.P.'
nl|'\n'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Virtual power driver commands'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|class|vbox
name|'class'
name|'vbox'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""set commands for basic Virtual Box control."""'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'base_cmd'
op|'='
string|"'/usr/bin/VBoxManage'"
newline|'\n'
name|'self'
op|'.'
name|'start_cmd'
op|'='
string|"'startvm {_NodeName_}'"
newline|'\n'
name|'self'
op|'.'
name|'stop_cmd'
op|'='
string|"'controlvm {_NodeName_} poweroff'"
newline|'\n'
name|'self'
op|'.'
name|'reboot_cmd'
op|'='
string|"'controlvm {_NodeName_} reset'"
newline|'\n'
name|'self'
op|'.'
name|'list_cmd'
op|'='
string|'"list vms|awk -F\'\\"\' \'{print $2}\'"'
newline|'\n'
name|'self'
op|'.'
name|'list_running_cmd'
op|'='
string|"'list runningvms'"
newline|'\n'
name|'self'
op|'.'
name|'get_node_macs'
op|'='
op|'('
string|'"showvminfo --machinereadable {_NodeName_} | "'
nl|'\n'
string|'"grep "'
nl|'\n'
string|'\'"macaddress" | awk -F \''
nl|'\n'
string|'"\'"'
nl|'\n'
string|'\'"\''
nl|'\n'
string|'"\' \'{print $2}\'"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|virsh
dedent|''
dedent|''
name|'class'
name|'virsh'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""set commands for basic Virsh control."""'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'base_cmd'
op|'='
string|"'/usr/bin/virsh'"
newline|'\n'
name|'self'
op|'.'
name|'start_cmd'
op|'='
string|"'start {_NodeName_}'"
newline|'\n'
name|'self'
op|'.'
name|'stop_cmd'
op|'='
string|"'destroy {_NodeName_}'"
newline|'\n'
name|'self'
op|'.'
name|'reboot_cmd'
op|'='
string|"'reset {_NodeName_}'"
newline|'\n'
name|'self'
op|'.'
name|'list_cmd'
op|'='
string|'"list --all | tail -n +2 | awk -F\\" \\" \'{print $2}\'"'
newline|'\n'
name|'self'
op|'.'
name|'list_running_cmd'
op|'='
string|'"list --all|grep running|awk -v qc=\'\\"\' -F\\" \\" \'{print qc$2qc}\'"'
newline|'\n'
name|'self'
op|'.'
name|'get_node_macs'
op|'='
op|'('
string|'"dumpxml {_NodeName_} | grep "'
nl|'\n'
string|'\'"mac address" | awk -F\''
nl|'\n'
string|'\'"\''
nl|'\n'
string|'"\'"'
nl|'\n'
string|'\'" \''
nl|'\n'
string|'"\'{print $2}\' | tr -d \':\'"'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
