begin_unit
comment|'# Copyright (c) 2014 IBM Corp.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Middleware that ensures x-compute-request-id\n\nUsing this middleware provides a convenient way to attach the\nx-compute-request-id to only v2 responses. Previously, this header was set in\napi/openstack/wsgi.py\n\nResponses for v2.1 API are taken care of by the request_id middleware provided\nin oslo.\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'oslo_context'
name|'import'
name|'context'
newline|'\n'
name|'from'
name|'oslo_middleware'
name|'import'
name|'base'
newline|'\n'
name|'import'
name|'webob'
op|'.'
name|'dec'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|ENV_REQUEST_ID
name|'ENV_REQUEST_ID'
op|'='
string|"'openstack.request_id'"
newline|'\n'
DECL|variable|HTTP_RESP_HEADER_REQUEST_ID
name|'HTTP_RESP_HEADER_REQUEST_ID'
op|'='
string|"'x-compute-request-id'"
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ComputeReqIdMiddleware
name|'class'
name|'ComputeReqIdMiddleware'
op|'('
name|'base'
op|'.'
name|'Middleware'
op|')'
op|':'
newline|'\n'
nl|'\n'
indent|'    '
op|'@'
name|'webob'
op|'.'
name|'dec'
op|'.'
name|'wsgify'
newline|'\n'
DECL|member|__call__
name|'def'
name|'__call__'
op|'('
name|'self'
op|','
name|'req'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'req_id'
op|'='
name|'context'
op|'.'
name|'generate_request_id'
op|'('
op|')'
newline|'\n'
name|'req'
op|'.'
name|'environ'
op|'['
name|'ENV_REQUEST_ID'
op|']'
op|'='
name|'req_id'
newline|'\n'
name|'response'
op|'='
name|'req'
op|'.'
name|'get_response'
op|'('
name|'self'
op|'.'
name|'application'
op|')'
newline|'\n'
name|'if'
name|'HTTP_RESP_HEADER_REQUEST_ID'
name|'not'
name|'in'
name|'response'
op|'.'
name|'headers'
op|':'
newline|'\n'
indent|'            '
name|'response'
op|'.'
name|'headers'
op|'.'
name|'add'
op|'('
name|'HTTP_RESP_HEADER_REQUEST_ID'
op|','
name|'req_id'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'response'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
