begin_unit
comment|'# Copyright (c) 2012 OpenStack Foundation'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
string|'"""\nRequest Body limiting middleware.\n\n"""'
newline|'\n'
name|'from'
name|'oslo'
op|'.'
name|'middleware'
name|'import'
name|'sizelimit'
newline|'\n'
nl|'\n'
nl|'\n'
comment|'# TODO(ekudryashova): Remove below aliases when grenade jobs'
nl|'\n'
comment|'# will start upgrading from juno'
nl|'\n'
DECL|variable|LimitingReader
name|'LimitingReader'
op|'='
name|'sizelimit'
op|'.'
name|'LimitingReader'
newline|'\n'
DECL|variable|RequestBodySizeLimiter
name|'RequestBodySizeLimiter'
op|'='
name|'sizelimit'
op|'.'
name|'RequestBodySizeLimiter'
newline|'\n'
endmarker|''
end_unit
