begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2012 IBM Corp.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""A connection to an IBM PowerVM Virtualization system.\n\nThe driver connects to an Integrated Virtualization Manager (IVM) to\nperform PowerVM Logical Partition (LPAR) deployment and management.\n\nFor more detailed information about PowerVM virtualization,\nrefer to the IBM Redbook[1] publication.\n\n[1] IBM Redbook. IBM PowerVM Virtualization Introduction and Configuration.\n    May 2011. <http://www.redbooks.ibm.com/abstracts/sg247940.html>\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'virt'
op|'.'
name|'powervm'
name|'import'
name|'driver'
newline|'\n'
nl|'\n'
DECL|variable|PowerVMDriver
name|'PowerVMDriver'
op|'='
name|'driver'
op|'.'
name|'PowerVMDriver'
newline|'\n'
endmarker|''
end_unit
