begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""DB related custom exceptions."""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
op|'.'
name|'gettextutils'
name|'import'
name|'_'
comment|'# noqa'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DBError
name|'class'
name|'DBError'
op|'('
name|'Exception'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Wraps an implementation specific exception."""'
newline|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'inner_exception'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'inner_exception'
op|'='
name|'inner_exception'
newline|'\n'
name|'super'
op|'('
name|'DBError'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'str'
op|'('
name|'inner_exception'
op|')'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DBDuplicateEntry
dedent|''
dedent|''
name|'class'
name|'DBDuplicateEntry'
op|'('
name|'DBError'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Wraps an implementation specific exception."""'
newline|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'columns'
op|'='
op|'['
op|']'
op|','
name|'inner_exception'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'columns'
op|'='
name|'columns'
newline|'\n'
name|'super'
op|'('
name|'DBDuplicateEntry'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'inner_exception'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DBDeadlock
dedent|''
dedent|''
name|'class'
name|'DBDeadlock'
op|'('
name|'DBError'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'inner_exception'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'super'
op|'('
name|'DBDeadlock'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'inner_exception'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DBInvalidUnicodeParameter
dedent|''
dedent|''
name|'class'
name|'DBInvalidUnicodeParameter'
op|'('
name|'Exception'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid Parameter: "'
nl|'\n'
string|'"Unicode is not supported by the current database."'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
