begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nProperties of an object stored within a bucket.\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'os'
newline|'\n'
nl|'\n'
name|'import'
name|'nova'
op|'.'
name|'crypto'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'exception'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|Object
name|'class'
name|'Object'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'bucket'
op|','
name|'key'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'""" wrapper class of an existing key """'
newline|'\n'
name|'self'
op|'.'
name|'bucket'
op|'='
name|'bucket'
newline|'\n'
name|'self'
op|'.'
name|'key'
op|'='
name|'key'
newline|'\n'
name|'self'
op|'.'
name|'path'
op|'='
name|'bucket'
op|'.'
name|'_object_path'
op|'('
name|'key'
op|')'
newline|'\n'
name|'if'
name|'not'
name|'os'
op|'.'
name|'path'
op|'.'
name|'isfile'
op|'('
name|'self'
op|'.'
name|'path'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'raise'
name|'exception'
op|'.'
name|'NotFound'
newline|'\n'
nl|'\n'
DECL|member|__repr__
dedent|''
dedent|''
name|'def'
name|'__repr__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
string|'"<Object %s/%s>"'
op|'%'
op|'('
name|'self'
op|'.'
name|'bucket'
op|','
name|'self'
op|'.'
name|'key'
op|')'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'property'
newline|'\n'
DECL|member|md5
name|'def'
name|'md5'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'""" computes the MD5 of the contents of file """'
newline|'\n'
name|'with'
name|'open'
op|'('
name|'self'
op|'.'
name|'path'
op|','
string|'"r"'
op|')'
name|'as'
name|'f'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'nova'
op|'.'
name|'crypto'
op|'.'
name|'compute_md5'
op|'('
name|'f'
op|')'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
op|'@'
name|'property'
newline|'\n'
DECL|member|mtime
name|'def'
name|'mtime'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'""" mtime of file """'
newline|'\n'
name|'return'
name|'os'
op|'.'
name|'path'
op|'.'
name|'getmtime'
op|'('
name|'self'
op|'.'
name|'path'
op|')'
newline|'\n'
nl|'\n'
DECL|member|read
dedent|''
name|'def'
name|'read'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'""" read all contents of key into memory and return """'
newline|'\n'
name|'return'
name|'self'
op|'.'
name|'file'
op|'.'
name|'read'
op|'('
op|')'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'property'
newline|'\n'
DECL|member|file
name|'def'
name|'file'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'""" return a file object for the key """'
newline|'\n'
name|'return'
name|'open'
op|'('
name|'self'
op|'.'
name|'path'
op|','
string|"'rb'"
op|')'
newline|'\n'
nl|'\n'
DECL|member|delete
dedent|''
name|'def'
name|'delete'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'""" deletes the file """'
newline|'\n'
name|'os'
op|'.'
name|'unlink'
op|'('
name|'self'
op|'.'
name|'path'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
