begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2012 Red Hat, Inc.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'api'
op|'.'
name|'openstack'
name|'import'
name|'common'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ViewBuilder
name|'class'
name|'ViewBuilder'
op|'('
name|'common'
op|'.'
name|'ViewBuilder'
op|')'
op|':'
newline|'\n'
nl|'\n'
DECL|member|show
indent|'    '
name|'def'
name|'show'
op|'('
name|'self'
op|','
name|'request'
op|','
name|'volume_type'
op|','
name|'brief'
op|'='
name|'False'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Trim away extraneous volume type attributes."""'
newline|'\n'
name|'trimmed'
op|'='
name|'dict'
op|'('
name|'id'
op|'='
name|'volume_type'
op|'.'
name|'get'
op|'('
string|"'id'"
op|')'
op|','
nl|'\n'
name|'name'
op|'='
name|'volume_type'
op|'.'
name|'get'
op|'('
string|"'name'"
op|')'
op|','
nl|'\n'
name|'extra_specs'
op|'='
name|'volume_type'
op|'.'
name|'get'
op|'('
string|"'extra_specs'"
op|')'
op|')'
newline|'\n'
name|'return'
name|'trimmed'
name|'if'
name|'brief'
name|'else'
name|'dict'
op|'('
name|'volume_type'
op|'='
name|'trimmed'
op|')'
newline|'\n'
nl|'\n'
DECL|member|index
dedent|''
name|'def'
name|'index'
op|'('
name|'self'
op|','
name|'request'
op|','
name|'volume_types'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Index over trimmed volume types"""'
newline|'\n'
name|'volume_types_list'
op|'='
op|'['
name|'self'
op|'.'
name|'show'
op|'('
name|'request'
op|','
name|'volume_type'
op|','
name|'True'
op|')'
nl|'\n'
name|'for'
name|'volume_type'
name|'in'
name|'volume_types'
op|']'
newline|'\n'
name|'return'
name|'dict'
op|'('
name|'volume_types'
op|'='
name|'volume_types_list'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
