begin_unit
comment|'# Copyright 2013 Red Hat, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Provides OpenStack config generators\n\nThis module defines a class for configuration\ngenerators for generating the model in\n:mod:`openstack.common.report.models.conf`.\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'oslo_config'
name|'import'
name|'cfg'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
op|'.'
name|'report'
op|'.'
name|'models'
name|'import'
name|'conf'
name|'as'
name|'cm'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConfigReportGenerator
name|'class'
name|'ConfigReportGenerator'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""A Configuration Data Generator\n\n    This generator returns\n    :class:`openstack.common.report.models.conf.ConfigModel`,\n    by default using the configuration options stored\n    in :attr:`oslo.config.cfg.CONF`, which is where\n    OpenStack stores everything.\n\n    :param cnf: the configuration option object\n    :type cnf: :class:`oslo.config.cfg.ConfigOpts`\n    """'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'cnf'
op|'='
name|'cfg'
op|'.'
name|'CONF'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'conf_obj'
op|'='
name|'cnf'
newline|'\n'
nl|'\n'
DECL|member|__call__
dedent|''
name|'def'
name|'__call__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'cm'
op|'.'
name|'ConfigModel'
op|'('
name|'self'
op|'.'
name|'conf_obj'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
