begin_unit
comment|'# Copyright 2013 Red Hat, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Provides OpenStack version generators\n\nThis module defines a class for OpenStack\nversion and package information\ngenerators for generating the model in\n:mod:`openstack.common.report.models.version`.\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
op|'.'
name|'report'
op|'.'
name|'models'
name|'import'
name|'version'
name|'as'
name|'vm'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|PackageReportGenerator
name|'class'
name|'PackageReportGenerator'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""A Package Information Data Generator\n\n    This generator returns\n    :class:`openstack.common.report.models.version.PackageModel`,\n    extracting data from the given version object, which should follow\n    the general format defined in Nova\'s version information (i.e. it\n    should contain the methods vendor_string, product_string, and\n    version_string_with_package).\n\n    :param version_object: the version information object\n    """'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'version_obj'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'version_obj'
op|'='
name|'version_obj'
newline|'\n'
nl|'\n'
DECL|member|__call__
dedent|''
name|'def'
name|'__call__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'hasattr'
op|'('
name|'self'
op|'.'
name|'version_obj'
op|','
string|'"vendor_string"'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'vendor_string'
op|'='
name|'self'
op|'.'
name|'version_obj'
op|'.'
name|'vendor_string'
op|'('
op|')'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'            '
name|'vendor_string'
op|'='
name|'None'
newline|'\n'
nl|'\n'
dedent|''
name|'if'
name|'hasattr'
op|'('
name|'self'
op|'.'
name|'version_obj'
op|','
string|'"product_string"'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'product_string'
op|'='
name|'self'
op|'.'
name|'version_obj'
op|'.'
name|'product_string'
op|'('
op|')'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'            '
name|'product_string'
op|'='
name|'None'
newline|'\n'
nl|'\n'
dedent|''
name|'if'
name|'hasattr'
op|'('
name|'self'
op|'.'
name|'version_obj'
op|','
string|'"version_string_with_package"'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'version_string_with_package'
op|'='
name|'self'
op|'.'
name|'version_obj'
op|'.'
name|'version_string_with_package'
op|'('
op|')'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'            '
name|'version_string_with_package'
op|'='
name|'None'
newline|'\n'
nl|'\n'
dedent|''
name|'return'
name|'vm'
op|'.'
name|'PackageModel'
op|'('
name|'vendor_string'
op|','
name|'product_string'
op|','
nl|'\n'
name|'version_string_with_package'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
