begin_unit
comment|'# Copyright (c) 2016 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'tests'
op|'.'
name|'unit'
op|'.'
name|'virt'
op|'.'
name|'xenapi'
op|'.'
name|'plugins'
name|'import'
name|'plugin_test'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NovaPluginVersion
name|'class'
name|'NovaPluginVersion'
op|'('
name|'plugin_test'
op|'.'
name|'PluginTestBase'
op|')'
op|':'
newline|'\n'
DECL|member|setUp
indent|'    '
name|'def'
name|'setUp'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'super'
op|'('
name|'NovaPluginVersion'
op|','
name|'self'
op|')'
op|'.'
name|'setUp'
op|'('
op|')'
newline|'\n'
name|'self'
op|'.'
name|'nova_plugin_version'
op|'='
name|'self'
op|'.'
name|'load_plugin'
op|'('
string|'"nova_plugin_version"'
op|')'
newline|'\n'
nl|'\n'
DECL|member|test_nova_plugin_version
dedent|''
name|'def'
name|'test_nova_plugin_version'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'session'
op|'='
string|"'fake_session'"
newline|'\n'
name|'expected_value'
op|'='
name|'self'
op|'.'
name|'nova_plugin_version'
op|'.'
name|'PLUGIN_VERSION'
newline|'\n'
name|'return_value'
op|'='
name|'self'
op|'.'
name|'nova_plugin_version'
op|'.'
name|'get_version'
op|'('
name|'session'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'assertEqual'
op|'('
name|'expected_value'
op|','
name|'return_value'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
