begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2011 OpenStack, LLC.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'rootwrap'
name|'import'
name|'filters'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|filterlist
name|'filterlist'
op|'='
op|'['
nl|'\n'
comment|"# nova/volume/iscsi.py: iscsi_helper '--op' ..."
nl|'\n'
name|'filters'
op|'.'
name|'CommandFilter'
op|'('
string|'"/usr/sbin/ietadm"'
op|','
string|'"root"'
op|')'
op|','
nl|'\n'
name|'filters'
op|'.'
name|'CommandFilter'
op|'('
string|'"/usr/sbin/tgtadm"'
op|','
string|'"root"'
op|')'
op|','
nl|'\n'
nl|'\n'
comment|"# nova/volume/driver.py: 'vgs', '--noheadings', '-o', 'name'"
nl|'\n'
name|'filters'
op|'.'
name|'CommandFilter'
op|'('
string|'"/sbin/vgs"'
op|','
string|'"root"'
op|')'
op|','
nl|'\n'
nl|'\n'
comment|"# nova/volume/driver.py: 'lvcreate', '-L', sizestr, '-n', volume_name,.."
nl|'\n'
comment|"# nova/volume/driver.py: 'lvcreate', '-L', ..."
nl|'\n'
name|'filters'
op|'.'
name|'CommandFilter'
op|'('
string|'"/sbin/lvcreate"'
op|','
string|'"root"'
op|')'
op|','
nl|'\n'
nl|'\n'
comment|"# nova/volume/driver.py: 'dd', 'if=%s' % srcstr, 'of=%s' % deststr,..."
nl|'\n'
name|'filters'
op|'.'
name|'CommandFilter'
op|'('
string|'"/bin/dd"'
op|','
string|'"root"'
op|')'
op|','
nl|'\n'
nl|'\n'
comment|'# nova/volume/driver.py: \'lvremove\', \'-f\', "%s/%s" % ...'
nl|'\n'
name|'filters'
op|'.'
name|'CommandFilter'
op|'('
string|'"/sbin/lvremove"'
op|','
string|'"root"'
op|')'
op|','
nl|'\n'
nl|'\n'
comment|"# nova/volume/driver.py: 'lvdisplay', '--noheading', '-C', '-o', 'Attr',.."
nl|'\n'
name|'filters'
op|'.'
name|'CommandFilter'
op|'('
string|'"/sbin/lvdisplay"'
op|','
string|'"root"'
op|')'
op|','
nl|'\n'
nl|'\n'
comment|"# nova/volume/driver.py: 'iscsiadm', '-m', 'discovery', '-t',..."
nl|'\n'
comment|"# nova/volume/driver.py: 'iscsiadm', '-m', 'node', '-T', ..."
nl|'\n'
name|'filters'
op|'.'
name|'CommandFilter'
op|'('
string|'"/sbin/iscsiadm"'
op|','
string|'"root"'
op|')'
op|','
nl|'\n'
op|']'
newline|'\n'
endmarker|''
end_unit
