begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2011 Openstack, LLC.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
name|'import'
name|'os'
newline|'\n'
name|'import'
name|'sys'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|FILTERS_MODULES
name|'FILTERS_MODULES'
op|'='
op|'['
string|"'nova.rootwrap.compute'"
op|','
nl|'\n'
string|"'nova.rootwrap.network'"
op|','
nl|'\n'
string|"'nova.rootwrap.volume'"
op|','
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|load_filters
name|'def'
name|'load_filters'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Load filters from modules present in nova.rootwrap."""'
newline|'\n'
name|'filters'
op|'='
op|'['
op|']'
newline|'\n'
name|'for'
name|'modulename'
name|'in'
name|'FILTERS_MODULES'
op|':'
newline|'\n'
indent|'        '
name|'try'
op|':'
newline|'\n'
indent|'            '
name|'__import__'
op|'('
name|'modulename'
op|')'
newline|'\n'
name|'module'
op|'='
name|'sys'
op|'.'
name|'modules'
op|'['
name|'modulename'
op|']'
newline|'\n'
name|'filters'
op|'='
name|'filters'
op|'+'
name|'module'
op|'.'
name|'filterlist'
newline|'\n'
dedent|''
name|'except'
name|'ImportError'
op|':'
newline|'\n'
comment|"# It's OK to have missing filters, since filter modules are"
nl|'\n'
comment|'# shipped with specific nodes rather than with python-nova'
nl|'\n'
indent|'            '
name|'pass'
newline|'\n'
dedent|''
dedent|''
name|'return'
name|'filters'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|match_filter
dedent|''
name|'def'
name|'match_filter'
op|'('
name|'filters'
op|','
name|'userargs'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""\n    Checks user command and arguments through command filters and\n    returns the first matching filter, or None is none matched.\n    """'
newline|'\n'
nl|'\n'
name|'for'
name|'f'
name|'in'
name|'filters'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'f'
op|'.'
name|'match'
op|'('
name|'userargs'
op|')'
op|':'
newline|'\n'
comment|'# Skip if executable is absent'
nl|'\n'
indent|'            '
name|'if'
name|'not'
name|'os'
op|'.'
name|'access'
op|'('
name|'f'
op|'.'
name|'exec_path'
op|','
name|'os'
op|'.'
name|'X_OK'
op|')'
op|':'
newline|'\n'
indent|'                '
name|'continue'
newline|'\n'
comment|'# Otherwise return matching filter for execution'
nl|'\n'
dedent|''
name|'return'
name|'f'
newline|'\n'
nl|'\n'
comment|'# No filter matched'
nl|'\n'
dedent|''
dedent|''
name|'return'
name|'None'
newline|'\n'
dedent|''
endmarker|''
end_unit
