begin_unit
comment|'# Copyright 2013 Red Hat, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Provides OpenStack Version Info Model\n\nThis module defines a class representing the data\nmodel for OpenStack package and version information\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
op|'.'
name|'report'
op|'.'
name|'models'
name|'import'
name|'with_default_views'
name|'as'
name|'mwdv'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
op|'.'
name|'report'
op|'.'
name|'views'
op|'.'
name|'text'
name|'import'
name|'generic'
name|'as'
name|'generic_text_views'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|PackageModel
name|'class'
name|'PackageModel'
op|'('
name|'mwdv'
op|'.'
name|'ModelWithDefaultViews'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""A Package Information Model\n\n    This model holds information about the current\n    package.  It contains vendor, product, and version\n    information.\n\n    :param str vendor: the product vendor\n    :param str product: the product name\n    :param str version: the product version\n    """'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'vendor'
op|','
name|'product'
op|','
name|'version'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'super'
op|'('
name|'PackageModel'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
nl|'\n'
name|'text_view'
op|'='
name|'generic_text_views'
op|'.'
name|'KeyValueView'
op|'('
op|')'
nl|'\n'
op|')'
newline|'\n'
nl|'\n'
name|'self'
op|'['
string|"'vendor'"
op|']'
op|'='
name|'vendor'
newline|'\n'
name|'self'
op|'['
string|"'product'"
op|']'
op|'='
name|'product'
newline|'\n'
name|'self'
op|'['
string|"'version'"
op|']'
op|'='
name|'version'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
