begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2012 OpenStack Foundation'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'api'
op|'.'
name|'openstack'
name|'import'
name|'extensions'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UserData
name|'class'
name|'UserData'
op|'('
name|'extensions'
op|'.'
name|'V3APIExtensionBase'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Add user_data to the Create Server v1.1 API."""'
newline|'\n'
nl|'\n'
DECL|variable|name
name|'name'
op|'='
string|'"UserData"'
newline|'\n'
DECL|variable|alias
name|'alias'
op|'='
string|'"os-user-data"'
newline|'\n'
DECL|variable|namespace
name|'namespace'
op|'='
op|'('
string|'"http://docs.openstack.org/compute/ext/"'
nl|'\n'
string|'"userdata/api/v3"'
op|')'
newline|'\n'
DECL|variable|version
name|'version'
op|'='
number|'1'
newline|'\n'
nl|'\n'
DECL|member|get_controller_extensions
name|'def'
name|'get_controller_extensions'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
op|'['
op|']'
newline|'\n'
nl|'\n'
DECL|member|get_resources
dedent|''
name|'def'
name|'get_resources'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
op|'['
op|']'
newline|'\n'
nl|'\n'
DECL|member|server_create
dedent|''
name|'def'
name|'server_create'
op|'('
name|'self'
op|','
name|'server_dict'
op|','
name|'create_kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'create_kwargs'
op|'['
string|"'user_data'"
op|']'
op|'='
name|'server_dict'
op|'.'
name|'get'
op|'('
string|"'user_data'"
op|')'
newline|'\n'
nl|'\n'
DECL|member|server_xml_extract_server_deserialize
dedent|''
name|'def'
name|'server_xml_extract_server_deserialize'
op|'('
name|'self'
op|','
name|'server_node'
op|','
name|'server_dict'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'user_data'
op|'='
name|'server_node'
op|'.'
name|'getAttribute'
op|'('
string|"'user_data'"
op|')'
newline|'\n'
name|'if'
name|'user_data'
op|':'
newline|'\n'
indent|'            '
name|'server_dict'
op|'['
string|"'user_data'"
op|']'
op|'='
name|'user_data'
newline|'\n'
dedent|''
dedent|''
dedent|''
endmarker|''
end_unit
