begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\r\n'
nl|'\r\n'
comment|'# Copyright (c) 2012 NTT.'
nl|'\r\n'
comment|'# Copyright (c) 2012 OpenStack, LLC.'
nl|'\r\n'
comment|'# All Rights Reserved.'
nl|'\r\n'
comment|'#'
nl|'\r\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\r\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\r\n'
comment|'#    a copy of the License at'
nl|'\r\n'
comment|'#'
nl|'\r\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\r\n'
comment|'#'
nl|'\r\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\r\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\r\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\r\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\r\n'
comment|'#    under the License.'
nl|'\r\n'
nl|'\r\n'
string|'"""The Create Volume from Image extension."""'
newline|'\r\n'
nl|'\r\n'
nl|'\r\n'
name|'from'
name|'nova'
op|'.'
name|'api'
op|'.'
name|'openstack'
name|'import'
name|'extensions'
newline|'\r\n'
nl|'\r\n'
nl|'\r\n'
DECL|class|Image_create
name|'class'
name|'Image_create'
op|'('
name|'extensions'
op|'.'
name|'ExtensionDescriptor'
op|')'
op|':'
newline|'\r\n'
indent|'    '
string|'"""Allow creating a volume from an image in the Create Volume v1 API"""'
newline|'\r\n'
nl|'\r\n'
DECL|variable|name
name|'name'
op|'='
string|'"CreateVolumeExtension"'
newline|'\r\n'
DECL|variable|alias
name|'alias'
op|'='
string|'"os-image-create"'
newline|'\r\n'
DECL|variable|namespace
name|'namespace'
op|'='
string|'"http://docs.openstack.org/volume/ext/image-create/api/v1"'
newline|'\r\n'
DECL|variable|updated
name|'updated'
op|'='
string|'"2012-08-13T00:00:00+00:00"'
newline|'\r\n'
dedent|''
endmarker|''
end_unit
