begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2012 Red Hat, Inc.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\ngettext for openstack-common modules.\n\nUsual usage in an openstack.common module:\n\n    from nova.openstack.common.gettextutils import _\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'gettext'
newline|'\n'
name|'import'
name|'os'
newline|'\n'
nl|'\n'
DECL|variable|_localedir
name|'_localedir'
op|'='
name|'os'
op|'.'
name|'environ'
op|'.'
name|'get'
op|'('
string|"'nova'"
op|'.'
name|'upper'
op|'('
op|')'
op|'+'
string|"'_LOCALEDIR'"
op|')'
newline|'\n'
DECL|variable|_t
name|'_t'
op|'='
name|'gettext'
op|'.'
name|'translation'
op|'('
string|"'nova'"
op|','
name|'localedir'
op|'='
name|'_localedir'
op|','
name|'fallback'
op|'='
name|'True'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|_
name|'def'
name|'_'
op|'('
name|'msg'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'_t'
op|'.'
name|'ugettext'
op|'('
name|'msg'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|install
dedent|''
name|'def'
name|'install'
op|'('
name|'domain'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Install a _() function using the given translation domain.\n\n    Given a translation domain, install a _() function using gettext\'s\n    install() function.\n\n    The main difference from gettext.install() is that we allow\n    overriding the default localedir (e.g. /usr/share/locale) using\n    a translation-domain-specific environment variable (e.g.\n    NOVA_LOCALEDIR).\n    """'
newline|'\n'
name|'gettext'
op|'.'
name|'install'
op|'('
name|'domain'
op|','
nl|'\n'
name|'localedir'
op|'='
name|'os'
op|'.'
name|'environ'
op|'.'
name|'get'
op|'('
name|'domain'
op|'.'
name|'upper'
op|'('
op|')'
op|'+'
string|"'_LOCALEDIR'"
op|')'
op|','
nl|'\n'
name|'unicode'
op|'='
name|'True'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
