begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2012 OpenStack Foundation.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nNetwork-related utilities and helper functions.\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
name|'import'
name|'log'
name|'as'
name|'logging'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|LOG
name|'LOG'
op|'='
name|'logging'
op|'.'
name|'getLogger'
op|'('
name|'__name__'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|parse_host_port
name|'def'
name|'parse_host_port'
op|'('
name|'address'
op|','
name|'default_port'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""\n    Interpret a string as a host:port pair.\n    An IPv6 address MUST be escaped if accompanied by a port,\n    because otherwise ambiguity ensues: 2001:db8:85a3::8a2e:370:7334\n    means both [2001:db8:85a3::8a2e:370:7334] and\n    [2001:db8:85a3::8a2e:370]:7334.\n\n    >>> parse_host_port(\'server01:80\')\n    (\'server01\', 80)\n    >>> parse_host_port(\'server01\')\n    (\'server01\', None)\n    >>> parse_host_port(\'server01\', default_port=1234)\n    (\'server01\', 1234)\n    >>> parse_host_port(\'[::1]:80\')\n    (\'::1\', 80)\n    >>> parse_host_port(\'[::1]\')\n    (\'::1\', None)\n    >>> parse_host_port(\'[::1]\', default_port=1234)\n    (\'::1\', 1234)\n    >>> parse_host_port(\'2001:db8:85a3::8a2e:370:7334\', default_port=1234)\n    (\'2001:db8:85a3::8a2e:370:7334\', 1234)\n\n    """'
newline|'\n'
name|'if'
name|'address'
op|'['
number|'0'
op|']'
op|'=='
string|"'['"
op|':'
newline|'\n'
comment|'# Escaped ipv6'
nl|'\n'
indent|'        '
name|'_host'
op|','
name|'_port'
op|'='
name|'address'
op|'['
number|'1'
op|':'
op|']'
op|'.'
name|'split'
op|'('
string|"']'"
op|')'
newline|'\n'
name|'host'
op|'='
name|'_host'
newline|'\n'
name|'if'
string|"':'"
name|'in'
name|'_port'
op|':'
newline|'\n'
indent|'            '
name|'port'
op|'='
name|'_port'
op|'.'
name|'split'
op|'('
string|"':'"
op|')'
op|'['
number|'1'
op|']'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'            '
name|'port'
op|'='
name|'default_port'
newline|'\n'
dedent|''
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'address'
op|'.'
name|'count'
op|'('
string|"':'"
op|')'
op|'=='
number|'1'
op|':'
newline|'\n'
indent|'            '
name|'host'
op|','
name|'port'
op|'='
name|'address'
op|'.'
name|'split'
op|'('
string|"':'"
op|')'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
comment|'# 0 means ipv4, >1 means ipv6.'
nl|'\n'
comment|'# We prohibit unescaped ipv6 addresses with port.'
nl|'\n'
indent|'            '
name|'host'
op|'='
name|'address'
newline|'\n'
name|'port'
op|'='
name|'default_port'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
name|'return'
op|'('
name|'host'
op|','
name|'None'
name|'if'
name|'port'
name|'is'
name|'None'
name|'else'
name|'int'
op|'('
name|'port'
op|')'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
