begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2013 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nHelpers for comparing version strings.\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'pkg_resources'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|is_compatible
name|'def'
name|'is_compatible'
op|'('
name|'requested_version'
op|','
name|'current_version'
op|','
name|'same_major'
op|'='
name|'True'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Determine whether `requested_version` is satisfied by\n    `current_version`; in other words, `current_version` is >=\n    `requested_version`.\n\n    :param requested_version: version to check for compatibility\n    :param current_version: version to check against\n    :param same_major: if True, the major version must be identical between\n        `requested_version` and `current_version`. This is used when a\n        major-version difference indicates incompatibility between the two\n        versions. Since this is the common-case in practice, the default is\n        True.\n    :returns: True if compatible, False if not\n    """'
newline|'\n'
name|'requested_parts'
op|'='
name|'pkg_resources'
op|'.'
name|'parse_version'
op|'('
name|'requested_version'
op|')'
newline|'\n'
name|'current_parts'
op|'='
name|'pkg_resources'
op|'.'
name|'parse_version'
op|'('
name|'current_version'
op|')'
newline|'\n'
nl|'\n'
name|'if'
name|'same_major'
name|'and'
op|'('
name|'requested_parts'
op|'['
number|'0'
op|']'
op|'!='
name|'current_parts'
op|'['
number|'0'
op|']'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'False'
newline|'\n'
nl|'\n'
dedent|''
name|'return'
name|'current_parts'
op|'>='
name|'requested_parts'
newline|'\n'
dedent|''
endmarker|''
end_unit
