begin_unit
comment|'# Copyright 2014 Hewlett-Packard Development Company, L.P.'
nl|'\n'
comment|'# Copyright 2012 University Of Minho'
nl|'\n'
comment|'# Copyright 2010 OpenStack Foundation'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
string|'"""\nTests for virt volumeutils.\n"""'
newline|'\n'
name|'import'
name|'mock'
newline|'\n'
name|'from'
name|'os_brick'
op|'.'
name|'initiator'
name|'import'
name|'connector'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'test'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'virt'
name|'import'
name|'volumeutils'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeUtilsTestCase
name|'class'
name|'VolumeUtilsTestCase'
op|'('
name|'test'
op|'.'
name|'NoDBTestCase'
op|')'
op|':'
newline|'\n'
nl|'\n'
indent|'    '
op|'@'
name|'mock'
op|'.'
name|'patch'
op|'.'
name|'object'
op|'('
name|'connector'
op|'.'
name|'ISCSIConnector'
op|','
string|"'get_initiator'"
op|','
nl|'\n'
DECL|variable|return_value
name|'return_value'
op|'='
string|"'fake.initiator.iqn'"
op|')'
newline|'\n'
DECL|member|test_get_iscsi_initiator
name|'def'
name|'test_get_iscsi_initiator'
op|'('
name|'self'
op|','
name|'fake_initiator'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'initiator'
op|'='
string|"'fake.initiator.iqn'"
newline|'\n'
comment|'# Start test'
nl|'\n'
name|'result'
op|'='
name|'volumeutils'
op|'.'
name|'get_iscsi_initiator'
op|'('
op|')'
newline|'\n'
name|'self'
op|'.'
name|'assertEqual'
op|'('
name|'initiator'
op|','
name|'result'
op|')'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'mock'
op|'.'
name|'patch'
op|'.'
name|'object'
op|'('
name|'connector'
op|'.'
name|'ISCSIConnector'
op|','
string|"'get_initiator'"
op|','
nl|'\n'
name|'return_value'
op|'='
name|'None'
op|')'
newline|'\n'
DECL|member|test_get_missing_iscsi_initiator
name|'def'
name|'test_get_missing_iscsi_initiator'
op|'('
name|'self'
op|','
name|'fake_initiator'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'result'
op|'='
name|'volumeutils'
op|'.'
name|'get_iscsi_initiator'
op|'('
op|')'
newline|'\n'
name|'self'
op|'.'
name|'assertIsNone'
op|'('
name|'result'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
