begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
comment|'# Copyright [2010] [Anso Labs, LLC]'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License");'
nl|'\n'
comment|'#    you may not use this file except in compliance with the License.'
nl|'\n'
comment|'#    You may obtain a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#        http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS,'
nl|'\n'
comment|'#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
nl|'\n'
comment|'#    See the License for the specific language governing permissions and'
nl|'\n'
comment|'#    limitations under the License.'
nl|'\n'
nl|'\n'
string|'"""\n:mod:`nova.cloudpipe` -- VPN Server Management\n=====================================================\n\n.. automodule:: nova.cloudpipe\n   :platform: Unix\n   :synopsis: An OpenVPN server for every nova user.\n.. moduleauthor:: Devin Carlen <devin.carlen@gmail.com>\n.. moduleauthor:: Vishvananda Ishaya <vishvananda@yahoo.com>\n.. moduleauthor:: Joshua McKenty <jmckenty@gmail.com>\n"""'
newline|'\n'
endmarker|''
end_unit
