begin_unit
comment|'# Copyright 2013 Intel Corporation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Tests for resource monitors."""'
newline|'\n'
nl|'\n'
name|'import'
name|'mock'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'compute'
name|'import'
name|'monitors'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'test'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MonitorsTestCase
name|'class'
name|'MonitorsTestCase'
op|'('
name|'test'
op|'.'
name|'NoDBTestCase'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Test case for monitors."""'
newline|'\n'
nl|'\n'
op|'@'
name|'mock'
op|'.'
name|'patch'
op|'('
string|"'stevedore.enabled.EnabledExtensionManager'"
op|')'
newline|'\n'
DECL|member|test_check_enabled_cpu_monitor
name|'def'
name|'test_check_enabled_cpu_monitor'
op|'('
name|'self'
op|','
name|'_mock_ext_manager'
op|')'
op|':'
newline|'\n'
DECL|class|FakeExt
indent|'        '
name|'class'
name|'FakeExt'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'            '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'name'
op|')'
op|':'
newline|'\n'
indent|'                '
name|'self'
op|'.'
name|'name'
op|'='
name|'name'
newline|'\n'
nl|'\n'
comment|'# We check to ensure only one CPU monitor is loaded...'
nl|'\n'
dedent|''
dedent|''
name|'self'
op|'.'
name|'flags'
op|'('
name|'compute_monitors'
op|'='
op|'['
string|"'cpu_mon1'"
op|','
string|"'cpu_mon2'"
op|']'
op|')'
newline|'\n'
name|'handler'
op|'='
name|'monitors'
op|'.'
name|'MonitorHandler'
op|'('
name|'None'
op|')'
newline|'\n'
name|'ext_cpu_mon1'
op|'='
name|'FakeExt'
op|'('
string|"'cpu_mon1'"
op|')'
newline|'\n'
name|'ext_cpu_mon2'
op|'='
name|'FakeExt'
op|'('
string|"'cpu_mon2'"
op|')'
newline|'\n'
name|'self'
op|'.'
name|'assertTrue'
op|'('
name|'handler'
op|'.'
name|'check_enabled_cpu_monitor'
op|'('
name|'ext_cpu_mon1'
op|')'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'assertFalse'
op|'('
name|'handler'
op|'.'
name|'check_enabled_cpu_monitor'
op|'('
name|'ext_cpu_mon2'
op|')'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
