begin_unit
comment|'# Copyright (c) 2014 VMware, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nShared constants across the VMware driver\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'network'
name|'import'
name|'model'
name|'as'
name|'network_model'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|DEFAULT_VIF_MODEL
name|'DEFAULT_VIF_MODEL'
op|'='
name|'network_model'
op|'.'
name|'VIF_MODEL_E1000'
newline|'\n'
DECL|variable|DEFAULT_OS_TYPE
name|'DEFAULT_OS_TYPE'
op|'='
string|'"otherGuest"'
newline|'\n'
DECL|variable|DEFAULT_ADAPTER_TYPE
name|'DEFAULT_ADAPTER_TYPE'
op|'='
string|'"lsiLogic"'
newline|'\n'
DECL|variable|DEFAULT_DISK_TYPE
name|'DEFAULT_DISK_TYPE'
op|'='
string|'"preallocated"'
newline|'\n'
endmarker|''
end_unit
