begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2011 Citrix Systems, Inc.'
nl|'\n'
comment|'# Copyright 2011 OpenStack Foundation'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nException classes and SOAP response error checking module.\n"""'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'exception'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
op|'.'
name|'gettextutils'
name|'import'
name|'_'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|FAULT_NOT_AUTHENTICATED
name|'FAULT_NOT_AUTHENTICATED'
op|'='
string|'"NotAuthenticated"'
newline|'\n'
DECL|variable|FAULT_ALREADY_EXISTS
name|'FAULT_ALREADY_EXISTS'
op|'='
string|'"AlreadyExists"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VimException
name|'class'
name|'VimException'
op|'('
name|'Exception'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""The VIM Exception class."""'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'exception_summary'
op|','
name|'excep'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'Exception'
op|'.'
name|'__init__'
op|'('
name|'self'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'exception_summary'
op|'='
name|'exception_summary'
newline|'\n'
name|'self'
op|'.'
name|'exception_obj'
op|'='
name|'excep'
newline|'\n'
nl|'\n'
DECL|member|__str__
dedent|''
name|'def'
name|'__str__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'self'
op|'.'
name|'exception_summary'
op|'+'
name|'str'
op|'('
name|'self'
op|'.'
name|'exception_obj'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SessionOverLoadException
dedent|''
dedent|''
name|'class'
name|'SessionOverLoadException'
op|'('
name|'VimException'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Session Overload Exception."""'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VimAttributeError
dedent|''
name|'class'
name|'VimAttributeError'
op|'('
name|'VimException'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""VI Attribute Error."""'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VimFaultException
dedent|''
name|'class'
name|'VimFaultException'
op|'('
name|'Exception'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""The VIM Fault exception class."""'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'fault_list'
op|','
name|'excep'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'Exception'
op|'.'
name|'__init__'
op|'('
name|'self'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'fault_list'
op|'='
name|'fault_list'
newline|'\n'
name|'self'
op|'.'
name|'exception_obj'
op|'='
name|'excep'
newline|'\n'
nl|'\n'
DECL|member|__str__
dedent|''
name|'def'
name|'__str__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'str'
op|'('
name|'self'
op|'.'
name|'exception_obj'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FaultCheckers
dedent|''
dedent|''
name|'class'
name|'FaultCheckers'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""\n    Methods for fault checking of SOAP response. Per Method error handlers\n    for which we desire error checking are defined. SOAP faults are\n    embedded in the SOAP messages as properties and not as SOAP faults.\n    """'
newline|'\n'
nl|'\n'
op|'@'
name|'staticmethod'
newline|'\n'
DECL|member|retrievepropertiesex_fault_checker
name|'def'
name|'retrievepropertiesex_fault_checker'
op|'('
name|'resp_obj'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Checks the RetrievePropertiesEx response for errors. Certain faults\n        are sent as part of the SOAP body as property of missingSet.\n        For example NotAuthenticated fault.\n        """'
newline|'\n'
name|'fault_list'
op|'='
op|'['
op|']'
newline|'\n'
name|'if'
name|'not'
name|'resp_obj'
op|':'
newline|'\n'
comment|'# This is the case when the session has timed out. ESX SOAP server'
nl|'\n'
comment|'# sends an empty RetrievePropertiesResponse. Normally missingSet in'
nl|'\n'
comment|"# the returnval field has the specifics about the error, but that's"
nl|'\n'
comment|'# not the case with a timed out idle session. It is as bad as a'
nl|'\n'
comment|'# terminated session for we cannot use the session. So setting'
nl|'\n'
comment|'# fault to NotAuthenticated fault.'
nl|'\n'
indent|'            '
name|'fault_list'
op|'='
op|'['
string|'"NotAuthenticated"'
op|']'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'            '
name|'for'
name|'obj_cont'
name|'in'
name|'resp_obj'
op|':'
newline|'\n'
indent|'                '
name|'if'
name|'hasattr'
op|'('
name|'obj_cont'
op|','
string|'"missingSet"'
op|')'
op|':'
newline|'\n'
indent|'                    '
name|'for'
name|'missing_elem'
name|'in'
name|'obj_cont'
op|'.'
name|'missingSet'
op|':'
newline|'\n'
indent|'                        '
name|'fault_type'
op|'='
name|'missing_elem'
op|'.'
name|'fault'
op|'.'
name|'fault'
op|'.'
name|'__class__'
newline|'\n'
comment|'# Fault needs to be added to the type of fault for'
nl|'\n'
comment|'# uniformity in error checking as SOAP faults define'
nl|'\n'
name|'fault_list'
op|'.'
name|'append'
op|'('
name|'fault_type'
op|'.'
name|'__name__'
op|')'
newline|'\n'
dedent|''
dedent|''
dedent|''
dedent|''
name|'if'
name|'fault_list'
op|':'
newline|'\n'
indent|'            '
name|'exc_msg_list'
op|'='
string|"', '"
op|'.'
name|'join'
op|'('
name|'fault_list'
op|')'
newline|'\n'
name|'raise'
name|'VimFaultException'
op|'('
name|'fault_list'
op|','
name|'Exception'
op|'('
name|'_'
op|'('
string|'"Error(s) %s "'
nl|'\n'
string|'"occurred in the call to RetrievePropertiesEx"'
op|')'
op|'%'
nl|'\n'
name|'exc_msg_list'
op|')'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VMwareDriverException
dedent|''
dedent|''
dedent|''
name|'class'
name|'VMwareDriverException'
op|'('
name|'exception'
op|'.'
name|'NovaException'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Base class for all exceptions raised by the VMware Driver.\n\n    All exceptions raised by the VMwareAPI drivers should raise\n    an exception descended from this class as a root. This will\n    allow the driver to potentially trap problems related to its\n    own internal configuration before halting the nova-compute\n    node.\n    """'
newline|'\n'
DECL|variable|msg_fmt
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"VMware Driver fault."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VMwareDriverConfigurationException
dedent|''
name|'class'
name|'VMwareDriverConfigurationException'
op|'('
name|'VMwareDriverException'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Base class for all configuration exceptions.\n    """'
newline|'\n'
DECL|variable|msg_fmt
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"VMware Driver configuration fault."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UseLinkedCloneConfigurationFault
dedent|''
name|'class'
name|'UseLinkedCloneConfigurationFault'
op|'('
name|'VMwareDriverConfigurationException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"No default value for use_linked_clone found."'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
