begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'# Copyright (c) 2010 Citrix Systems, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nHandling of VM disk images.\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'os'
op|'.'
name|'path'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'flags'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'process'
newline|'\n'
nl|'\n'
DECL|variable|FLAGS
name|'FLAGS'
op|'='
name|'flags'
op|'.'
name|'FLAGS'
newline|'\n'
nl|'\n'
name|'flags'
op|'.'
name|'DEFINE_bool'
op|'('
string|"'use_s3'"
op|','
name|'True'
op|','
nl|'\n'
string|"'whether to get images from s3 or use local copy'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|fetch
name|'def'
name|'fetch'
op|'('
name|'image'
op|','
name|'path'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'if'
name|'FLAGS'
op|'.'
name|'use_s3'
op|':'
newline|'\n'
indent|'        '
name|'f'
op|'='
name|'_fetch_s3_image'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'        '
name|'f'
op|'='
name|'_fetch_local_image'
newline|'\n'
dedent|''
name|'return'
name|'f'
op|'('
name|'image'
op|','
name|'path'
op|')'
newline|'\n'
nl|'\n'
DECL|function|_fetch_s3_image
dedent|''
name|'def'
name|'_fetch_s3_image'
op|'('
name|'image'
op|','
name|'path'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'url'
op|'='
name|'_image_url'
op|'('
string|"'%s/image'"
op|'%'
name|'image'
op|')'
newline|'\n'
name|'return'
name|'process'
op|'.'
name|'simple_execute'
op|'('
string|"'curl --silent %s -o %s'"
op|'%'
op|'('
name|'url'
op|','
name|'path'
op|')'
op|')'
newline|'\n'
nl|'\n'
DECL|function|_fetch_local_image
dedent|''
name|'def'
name|'_fetch_local_image'
op|'('
name|'image'
op|','
name|'path'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'source'
op|'='
name|'_image_path'
op|'('
string|"'%s/image'"
op|'%'
name|'image'
op|')'
newline|'\n'
name|'return'
name|'process'
op|'.'
name|'simple_execute'
op|'('
string|"'cp %s %s'"
op|'%'
op|'('
name|'source'
op|','
name|'path'
op|')'
op|')'
newline|'\n'
nl|'\n'
DECL|function|_image_path
dedent|''
name|'def'
name|'_image_path'
op|'('
name|'path'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'os'
op|'.'
name|'path'
op|'.'
name|'join'
op|'('
name|'FLAGS'
op|'.'
name|'images_path'
op|','
name|'path'
op|')'
newline|'\n'
nl|'\n'
DECL|function|_image_url
dedent|''
name|'def'
name|'_image_url'
op|'('
name|'path'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
string|'"%s:%s/_images/%s"'
op|'%'
op|'('
name|'FLAGS'
op|'.'
name|'s3_host'
op|','
name|'FLAGS'
op|'.'
name|'s3_port'
op|','
name|'path'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
