begin_unit
comment|'# Copyright 2014 Hewlett-Packard Development Company, L.P.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
string|'"""\nVolume utilities for virt drivers.\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'exception'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'utils'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_iscsi_initiator
name|'def'
name|'get_iscsi_initiator'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Get iscsi initiator name for this machine."""'
newline|'\n'
comment|'# NOTE(vish) openiscsi stores initiator name in a file that'
nl|'\n'
comment|'#            needs root permission to read.'
nl|'\n'
name|'try'
op|':'
newline|'\n'
indent|'        '
name|'contents'
op|'='
name|'utils'
op|'.'
name|'read_file_as_root'
op|'('
string|"'/etc/iscsi/initiatorname.iscsi'"
op|')'
newline|'\n'
dedent|''
name|'except'
name|'exception'
op|'.'
name|'FileNotFound'
op|':'
newline|'\n'
indent|'        '
name|'return'
string|"''"
newline|'\n'
nl|'\n'
dedent|''
name|'for'
name|'l'
name|'in'
name|'contents'
op|'.'
name|'split'
op|'('
string|"'\\n'"
op|')'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'l'
op|'.'
name|'startswith'
op|'('
string|"'InitiatorName='"
op|')'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'l'
op|'['
name|'l'
op|'.'
name|'index'
op|'('
string|"'='"
op|')'
op|'+'
number|'1'
op|':'
op|']'
op|'.'
name|'strip'
op|'('
op|')'
newline|'\n'
dedent|''
dedent|''
name|'return'
string|"''"
newline|'\n'
dedent|''
endmarker|''
end_unit
