begin_unit
comment|'# Copyright 2014 Hewlett-Packard Development Company, L.P.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
string|'"""\nVolume utilities for virt drivers.\n"""'
newline|'\n'
name|'from'
name|'os_brick'
op|'.'
name|'initiator'
name|'import'
name|'connector'
newline|'\n'
name|'from'
name|'oslo_concurrency'
name|'import'
name|'processutils'
name|'as'
name|'putils'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'utils'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_iscsi_initiator
name|'def'
name|'get_iscsi_initiator'
op|'('
name|'execute'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Get iscsi initiator name for this machine."""'
newline|'\n'
nl|'\n'
name|'root_helper'
op|'='
name|'utils'
op|'.'
name|'get_root_helper'
op|'('
op|')'
newline|'\n'
comment|'# so we can mock out the execute itself'
nl|'\n'
comment|'# in unit tests.'
nl|'\n'
name|'if'
name|'not'
name|'execute'
op|':'
newline|'\n'
indent|'        '
name|'execute'
op|'='
name|'putils'
op|'.'
name|'execute'
newline|'\n'
dedent|''
name|'iscsi'
op|'='
name|'connector'
op|'.'
name|'ISCSIConnector'
op|'('
name|'root_helper'
op|'='
name|'root_helper'
op|','
nl|'\n'
name|'execute'
op|'='
name|'execute'
op|')'
newline|'\n'
name|'return'
name|'iscsi'
op|'.'
name|'get_initiator'
op|'('
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
