begin_unit
comment|'# Copyright (c) 2012-2013 Rackspace Hosting'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nCell Scheduler weights\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'weights'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|WeightedCell
name|'class'
name|'WeightedCell'
op|'('
name|'weights'
op|'.'
name|'WeighedObject'
op|')'
op|':'
newline|'\n'
DECL|member|__repr__
indent|'    '
name|'def'
name|'__repr__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
string|'"WeightedCell [cell: %s, weight: %s]"'
op|'%'
op|'('
nl|'\n'
name|'self'
op|'.'
name|'obj'
op|'.'
name|'name'
op|','
name|'self'
op|'.'
name|'weight'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|BaseCellWeigher
dedent|''
dedent|''
name|'class'
name|'BaseCellWeigher'
op|'('
name|'weights'
op|'.'
name|'BaseWeigher'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Base class for cell weights."""'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CellWeightHandler
dedent|''
name|'class'
name|'CellWeightHandler'
op|'('
name|'weights'
op|'.'
name|'BaseWeightHandler'
op|')'
op|':'
newline|'\n'
DECL|variable|object_class
indent|'    '
name|'object_class'
op|'='
name|'WeightedCell'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'super'
op|'('
name|'CellWeightHandler'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'BaseCellWeigher'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|all_weighers
dedent|''
dedent|''
name|'def'
name|'all_weighers'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Return a list of weight plugin classes found in this directory."""'
newline|'\n'
name|'return'
name|'CellWeightHandler'
op|'('
op|')'
op|'.'
name|'get_all_classes'
op|'('
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
