begin_unit
comment|'# Copyright (c) 2011 Openstack, LLC.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Decorator for limiting extensions that should be admin-only."""'
newline|'\n'
nl|'\n'
name|'from'
name|'functools'
name|'import'
name|'wraps'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'flags'
newline|'\n'
DECL|variable|FLAGS
name|'FLAGS'
op|'='
name|'flags'
op|'.'
name|'FLAGS'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|admin_only
name|'def'
name|'admin_only'
op|'('
name|'fnc'
op|')'
op|':'
newline|'\n'
indent|'    '
op|'@'
name|'wraps'
op|'('
name|'fnc'
op|')'
newline|'\n'
DECL|function|_wrapped
name|'def'
name|'_wrapped'
op|'('
name|'self'
op|','
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'FLAGS'
op|'.'
name|'allow_admin_api'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'fnc'
op|'('
name|'self'
op|','
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
newline|'\n'
dedent|''
name|'return'
op|'['
op|']'
newline|'\n'
dedent|''
name|'_wrapped'
op|'.'
name|'func_name'
op|'='
name|'fnc'
op|'.'
name|'func_name'
newline|'\n'
name|'return'
name|'_wrapped'
newline|'\n'
dedent|''
endmarker|''
end_unit
