begin_unit
comment|'# Copyright 2015 HPE, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'# not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'# a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'# License for the specific language governing permissions and limitations'
nl|'\n'
comment|'# under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'mock'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'cmd'
name|'import'
name|'api'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'config'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'test'
newline|'\n'
nl|'\n'
nl|'\n'
comment|'# required because otherwise oslo early parse_args dies'
nl|'\n'
op|'@'
name|'mock'
op|'.'
name|'patch'
op|'.'
name|'object'
op|'('
name|'config'
op|','
string|"'parse_args'"
op|','
name|'new'
op|'='
name|'lambda'
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|':'
name|'None'
op|')'
newline|'\n'
DECL|class|TestNovaAPI
name|'class'
name|'TestNovaAPI'
op|'('
name|'test'
op|'.'
name|'NoDBTestCase'
op|')'
op|':'
newline|'\n'
nl|'\n'
indent|'    '
op|'@'
name|'mock'
op|'.'
name|'patch'
op|'('
string|"'nova.service.process_launcher'"
op|')'
newline|'\n'
DECL|member|test_with_ec2
name|'def'
name|'test_with_ec2'
op|'('
name|'self'
op|','
name|'launcher'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Ensure that we don\'t explode if enabled_apis is wrong.\n\n        If the end user hasn\'t updated their config, an ec2 entry\n        might accidentally kill them in starting up their server. This\n        tests that our new safety filter will prevent that.\n\n        The metadata api is excluded because it loads a bunch of the\n        network stack, which requires other mocking.\n        """'
newline|'\n'
name|'self'
op|'.'
name|'flags'
op|'('
name|'enabled_apis'
op|'='
op|'['
string|"'ec2'"
op|','
string|"'osapi_compute'"
op|']'
op|')'
newline|'\n'
comment|'# required because of where the portbind happens, so that we'
nl|'\n'
comment|'# collide on ports.'
nl|'\n'
name|'self'
op|'.'
name|'flags'
op|'('
name|'osapi_compute_listen_port'
op|'='
number|'0'
op|')'
newline|'\n'
name|'api'
op|'.'
name|'main'
op|'('
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
