begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Nova base exception handling.\n\nIncludes decorator for re-raising Nova-type exceptions.\n\nSHOULD include dedicated exception logging.\n\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'functools'
newline|'\n'
name|'import'
name|'sys'
newline|'\n'
nl|'\n'
name|'import'
name|'novaclient'
op|'.'
name|'exceptions'
newline|'\n'
name|'import'
name|'webob'
op|'.'
name|'exc'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'log'
name|'as'
name|'logging'
newline|'\n'
nl|'\n'
DECL|variable|LOG
name|'LOG'
op|'='
name|'logging'
op|'.'
name|'getLogger'
op|'('
string|"'nova.exception'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConvertedException
name|'class'
name|'ConvertedException'
op|'('
name|'webob'
op|'.'
name|'exc'
op|'.'
name|'WSGIHTTPException'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'code'
op|'='
number|'0'
op|','
name|'title'
op|'='
string|'""'
op|','
name|'explanation'
op|'='
string|'""'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'code'
op|'='
name|'code'
newline|'\n'
name|'self'
op|'.'
name|'title'
op|'='
name|'title'
newline|'\n'
name|'self'
op|'.'
name|'explanation'
op|'='
name|'explanation'
newline|'\n'
name|'super'
op|'('
name|'ConvertedException'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|novaclient_converter
dedent|''
dedent|''
name|'def'
name|'novaclient_converter'
op|'('
name|'f'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Convert novaclient ClientException HTTP codes to webob exceptions.\n    Has to be the outer-most decorator.\n    """'
newline|'\n'
DECL|function|new_f
name|'def'
name|'new_f'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'try'
op|':'
newline|'\n'
indent|'            '
name|'ret'
op|'='
name|'f'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
newline|'\n'
name|'return'
name|'ret'
newline|'\n'
dedent|''
name|'except'
name|'novaclient'
op|'.'
name|'exceptions'
op|'.'
name|'ClientException'
op|','
name|'e'
op|':'
newline|'\n'
indent|'            '
name|'raise'
name|'ConvertedException'
op|'('
name|'e'
op|'.'
name|'code'
op|','
name|'e'
op|'.'
name|'message'
op|','
name|'e'
op|'.'
name|'details'
op|')'
newline|'\n'
dedent|''
dedent|''
name|'return'
name|'new_f'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ProcessExecutionError
dedent|''
name|'class'
name|'ProcessExecutionError'
op|'('
name|'IOError'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'stdout'
op|'='
name|'None'
op|','
name|'stderr'
op|'='
name|'None'
op|','
name|'exit_code'
op|'='
name|'None'
op|','
name|'cmd'
op|'='
name|'None'
op|','
nl|'\n'
name|'description'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'exit_code'
op|'='
name|'exit_code'
newline|'\n'
name|'self'
op|'.'
name|'stderr'
op|'='
name|'stderr'
newline|'\n'
name|'self'
op|'.'
name|'stdout'
op|'='
name|'stdout'
newline|'\n'
name|'self'
op|'.'
name|'cmd'
op|'='
name|'cmd'
newline|'\n'
name|'self'
op|'.'
name|'description'
op|'='
name|'description'
newline|'\n'
nl|'\n'
name|'if'
name|'description'
name|'is'
name|'None'
op|':'
newline|'\n'
indent|'            '
name|'description'
op|'='
name|'_'
op|'('
string|"'Unexpected error while running command.'"
op|')'
newline|'\n'
dedent|''
name|'if'
name|'exit_code'
name|'is'
name|'None'
op|':'
newline|'\n'
indent|'            '
name|'exit_code'
op|'='
string|"'-'"
newline|'\n'
dedent|''
name|'message'
op|'='
name|'_'
op|'('
string|"'%(description)s\\nCommand: %(cmd)s\\n'"
nl|'\n'
string|"'Exit code: %(exit_code)s\\nStdout: %(stdout)r\\n'"
nl|'\n'
string|"'Stderr: %(stderr)r'"
op|')'
op|'%'
name|'locals'
op|'('
op|')'
newline|'\n'
name|'IOError'
op|'.'
name|'__init__'
op|'('
name|'self'
op|','
name|'message'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|Error
dedent|''
dedent|''
name|'class'
name|'Error'
op|'('
name|'Exception'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'message'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'super'
op|'('
name|'Error'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'message'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ApiError
dedent|''
dedent|''
name|'class'
name|'ApiError'
op|'('
name|'Error'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'message'
op|'='
string|"'Unknown'"
op|','
name|'code'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'msg'
op|'='
name|'message'
newline|'\n'
name|'self'
op|'.'
name|'code'
op|'='
name|'code'
newline|'\n'
name|'if'
name|'code'
op|':'
newline|'\n'
indent|'            '
name|'outstr'
op|'='
string|"'%s: %s'"
op|'%'
op|'('
name|'code'
op|','
name|'message'
op|')'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'            '
name|'outstr'
op|'='
string|"'%s'"
op|'%'
name|'message'
newline|'\n'
dedent|''
name|'super'
op|'('
name|'ApiError'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'outstr'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DBError
dedent|''
dedent|''
name|'class'
name|'DBError'
op|'('
name|'Error'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Wraps an implementation specific exception."""'
newline|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'inner_exception'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'inner_exception'
op|'='
name|'inner_exception'
newline|'\n'
name|'super'
op|'('
name|'DBError'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'str'
op|'('
name|'inner_exception'
op|')'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|wrap_db_error
dedent|''
dedent|''
name|'def'
name|'wrap_db_error'
op|'('
name|'f'
op|')'
op|':'
newline|'\n'
DECL|function|_wrap
indent|'    '
name|'def'
name|'_wrap'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'try'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'f'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
newline|'\n'
dedent|''
name|'except'
name|'Exception'
op|','
name|'e'
op|':'
newline|'\n'
indent|'            '
name|'LOG'
op|'.'
name|'exception'
op|'('
name|'_'
op|'('
string|"'DB exception wrapped.'"
op|')'
op|')'
newline|'\n'
name|'raise'
name|'DBError'
op|'('
name|'e'
op|')'
newline|'\n'
dedent|''
dedent|''
name|'_wrap'
op|'.'
name|'func_name'
op|'='
name|'f'
op|'.'
name|'func_name'
newline|'\n'
name|'return'
name|'_wrap'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|wrap_exception
dedent|''
name|'def'
name|'wrap_exception'
op|'('
name|'notifier'
op|'='
name|'None'
op|','
name|'publisher_id'
op|'='
name|'None'
op|','
name|'event_type'
op|'='
name|'None'
op|','
nl|'\n'
name|'level'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""This decorator wraps a method to catch any exceptions that may\n    get thrown. It logs the exception as well as optionally sending\n    it to the notification system.\n    """'
newline|'\n'
comment|"# TODO(sandy): Find a way to import nova.notifier.api so we don't have"
nl|'\n'
comment|'# to pass it in as a parameter. Otherwise we get a cyclic import of'
nl|'\n'
comment|'# nova.notifier.api -> nova.utils -> nova.exception :('
nl|'\n'
comment|'# TODO(johannes): Also, it would be nice to use'
nl|'\n'
comment|'# utils.save_and_reraise_exception() without an import loop'
nl|'\n'
DECL|function|inner
name|'def'
name|'inner'
op|'('
name|'f'
op|')'
op|':'
newline|'\n'
DECL|function|wrapped
indent|'        '
name|'def'
name|'wrapped'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kw'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'try'
op|':'
newline|'\n'
indent|'                '
name|'return'
name|'f'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kw'
op|')'
newline|'\n'
dedent|''
name|'except'
name|'Exception'
op|','
name|'e'
op|':'
newline|'\n'
comment|'# Save exception since it can be clobbered during processing'
nl|'\n'
comment|'# below before we can re-raise'
nl|'\n'
indent|'                '
name|'exc_info'
op|'='
name|'sys'
op|'.'
name|'exc_info'
op|'('
op|')'
newline|'\n'
nl|'\n'
name|'if'
name|'notifier'
op|':'
newline|'\n'
indent|'                    '
name|'payload'
op|'='
name|'dict'
op|'('
name|'args'
op|'='
name|'args'
op|','
name|'exception'
op|'='
name|'e'
op|')'
newline|'\n'
name|'payload'
op|'.'
name|'update'
op|'('
name|'kw'
op|')'
newline|'\n'
nl|'\n'
comment|"# Use a temp vars so we don't shadow"
nl|'\n'
comment|'# our outer definitions.'
nl|'\n'
name|'temp_level'
op|'='
name|'level'
newline|'\n'
name|'if'
name|'not'
name|'temp_level'
op|':'
newline|'\n'
indent|'                        '
name|'temp_level'
op|'='
name|'notifier'
op|'.'
name|'ERROR'
newline|'\n'
nl|'\n'
dedent|''
name|'temp_type'
op|'='
name|'event_type'
newline|'\n'
name|'if'
name|'not'
name|'temp_type'
op|':'
newline|'\n'
comment|'# If f has multiple decorators, they must use'
nl|'\n'
comment|'# functools.wraps to ensure the name is'
nl|'\n'
comment|'# propagated.'
nl|'\n'
indent|'                        '
name|'temp_type'
op|'='
name|'f'
op|'.'
name|'__name__'
newline|'\n'
nl|'\n'
dedent|''
name|'notifier'
op|'.'
name|'notify'
op|'('
name|'publisher_id'
op|','
name|'temp_type'
op|','
name|'temp_level'
op|','
nl|'\n'
name|'payload'
op|')'
newline|'\n'
nl|'\n'
comment|'# re-raise original exception since it may have been clobbered'
nl|'\n'
dedent|''
name|'raise'
name|'exc_info'
op|'['
number|'0'
op|']'
op|','
name|'exc_info'
op|'['
number|'1'
op|']'
op|','
name|'exc_info'
op|'['
number|'2'
op|']'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
name|'return'
name|'functools'
op|'.'
name|'wraps'
op|'('
name|'f'
op|')'
op|'('
name|'wrapped'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'inner'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NovaException
dedent|''
name|'class'
name|'NovaException'
op|'('
name|'Exception'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Base Nova Exception\n\n    To correctly use this class, inherit from it and define\n    a \'message\' property. That message will get printf\'d\n    with the keyword arguments provided to the constructor.\n\n    """'
newline|'\n'
DECL|variable|message
name|'message'
op|'='
name|'_'
op|'('
string|'"An unknown exception occurred."'
op|')'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'message'
op|'='
name|'None'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'kwargs'
op|'='
name|'kwargs'
newline|'\n'
name|'if'
name|'not'
name|'message'
op|':'
newline|'\n'
indent|'            '
name|'try'
op|':'
newline|'\n'
indent|'                '
name|'message'
op|'='
name|'self'
op|'.'
name|'message'
op|'%'
name|'kwargs'
newline|'\n'
nl|'\n'
dedent|''
name|'except'
name|'Exception'
name|'as'
name|'e'
op|':'
newline|'\n'
comment|'# at least get the core message out if something happened'
nl|'\n'
indent|'                '
name|'message'
op|'='
name|'self'
op|'.'
name|'message'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
name|'super'
op|'('
name|'NovaException'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'message'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DecryptionFailure
dedent|''
dedent|''
name|'class'
name|'DecryptionFailure'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Failed to decrypt text"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImagePaginationFailed
dedent|''
name|'class'
name|'ImagePaginationFailed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Failed to paginate through images from image service"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VirtualInterfaceCreateException
dedent|''
name|'class'
name|'VirtualInterfaceCreateException'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Virtual Interface creation failed"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VirtualInterfaceMacAddressException
dedent|''
name|'class'
name|'VirtualInterfaceMacAddressException'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"5 attempts to create virtual interface"'
nl|'\n'
string|'"with unique mac address failed"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NotAuthorized
dedent|''
name|'class'
name|'NotAuthorized'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Not authorized."'
op|')'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'super'
op|'('
name|'NotAuthorized'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AdminRequired
dedent|''
dedent|''
name|'class'
name|'AdminRequired'
op|'('
name|'NotAuthorized'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"User does not have admin privileges"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|PolicyNotAuthorized
dedent|''
name|'class'
name|'PolicyNotAuthorized'
op|'('
name|'NotAuthorized'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Policy doesn\'t allow %(action)s to be performed."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|Invalid
dedent|''
name|'class'
name|'Invalid'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Unacceptable parameters."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidKeypair
dedent|''
name|'class'
name|'InvalidKeypair'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Keypair data is invalid"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SfJsonEncodeFailure
dedent|''
name|'class'
name|'SfJsonEncodeFailure'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Failed to load data into json format"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidRequest
dedent|''
name|'class'
name|'InvalidRequest'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"The request is invalid."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidSignature
dedent|''
name|'class'
name|'InvalidSignature'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid signature %(signature)s for user %(user)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidInput
dedent|''
name|'class'
name|'InvalidInput'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid input received"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidInstanceType
dedent|''
name|'class'
name|'InvalidInstanceType'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid instance type %(instance_type)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidVolumeType
dedent|''
name|'class'
name|'InvalidVolumeType'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid volume type %(volume_type)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidPortRange
dedent|''
name|'class'
name|'InvalidPortRange'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid port range %(from_port)s:%(to_port)s. %(msg)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidIpProtocol
dedent|''
name|'class'
name|'InvalidIpProtocol'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid IP protocol %(protocol)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidContentType
dedent|''
name|'class'
name|'InvalidContentType'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid content type %(content_type)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidCidr
dedent|''
name|'class'
name|'InvalidCidr'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid cidr %(cidr)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidRPCConnectionReuse
dedent|''
name|'class'
name|'InvalidRPCConnectionReuse'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid reuse of an RPC connection."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
comment|'# Cannot be templated as the error syntax varies.'
nl|'\n'
comment|'# msg needs to be constructed when raised.'
nl|'\n'
DECL|class|InvalidParameterValue
dedent|''
name|'class'
name|'InvalidParameterValue'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"%(err)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidAggregateAction
dedent|''
name|'class'
name|'InvalidAggregateAction'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Cannot perform action \'%(action)s\' on aggregate "'
nl|'\n'
string|'"%(aggregate_id)s. Reason: %(reason)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceInvalidState
dedent|''
name|'class'
name|'InstanceInvalidState'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot "'
nl|'\n'
string|'"%(method)s while the instance is in this state."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceNotRunning
dedent|''
name|'class'
name|'InstanceNotRunning'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s is not running."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceNotSuspended
dedent|''
name|'class'
name|'InstanceNotSuspended'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s is not suspended."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceNotInRescueMode
dedent|''
name|'class'
name|'InstanceNotInRescueMode'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s is not in rescue mode"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceSuspendFailure
dedent|''
name|'class'
name|'InstanceSuspendFailure'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Failed to suspend instance"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceResumeFailure
dedent|''
name|'class'
name|'InstanceResumeFailure'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Failed to resume server"'
op|')'
op|'+'
string|'": %(reason)s."'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceRebootFailure
dedent|''
name|'class'
name|'InstanceRebootFailure'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Failed to reboot instance"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ServiceUnavailable
dedent|''
name|'class'
name|'ServiceUnavailable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Service is unavailable at this time."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeServiceUnavailable
dedent|''
name|'class'
name|'VolumeServiceUnavailable'
op|'('
name|'ServiceUnavailable'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Volume service is unavailable at this time."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ComputeServiceUnavailable
dedent|''
name|'class'
name|'ComputeServiceUnavailable'
op|'('
name|'ServiceUnavailable'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Compute service is unavailable at this time."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UnableToMigrateToSelf
dedent|''
name|'class'
name|'UnableToMigrateToSelf'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Unable to migrate instance (%(instance_id)s) "'
nl|'\n'
string|'"to current host (%(host)s)."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DestinationHostUnavailable
dedent|''
name|'class'
name|'DestinationHostUnavailable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Destination compute host is unavailable at this time."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SourceHostUnavailable
dedent|''
name|'class'
name|'SourceHostUnavailable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Original compute host is unavailable at this time."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidHypervisorType
dedent|''
name|'class'
name|'InvalidHypervisorType'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"The supplied hypervisor type of is invalid."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DestinationHypervisorTooOld
dedent|''
name|'class'
name|'DestinationHypervisorTooOld'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"The instance requires a newer hypervisor version than "'
nl|'\n'
string|'"has been provided."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DestinationDiskExists
dedent|''
name|'class'
name|'DestinationDiskExists'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"The supplied disk path (%(path)s) already exists, "'
nl|'\n'
string|'"it is expected not to exist."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidDevicePath
dedent|''
name|'class'
name|'InvalidDevicePath'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"The supplied device path (%(path)s) is invalid."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidCPUInfo
dedent|''
name|'class'
name|'InvalidCPUInfo'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Unacceptable CPU info"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidIpAddressError
dedent|''
name|'class'
name|'InvalidIpAddressError'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"%(address)s is not a valid IP v4/6 address."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidVLANTag
dedent|''
name|'class'
name|'InvalidVLANTag'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"VLAN tag is not appropriate for the port group "'
nl|'\n'
string|'"%(bridge)s. Expected VLAN tag is %(tag)s, "'
nl|'\n'
string|'"but the one associated with the port group is %(pgroup)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidVLANPortGroup
dedent|''
name|'class'
name|'InvalidVLANPortGroup'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"vSwitch which contains the port group %(bridge)s is "'
nl|'\n'
string|'"not associated with the desired physical adapter. "'
nl|'\n'
string|'"Expected vSwitch is %(expected)s, but the one associated "'
nl|'\n'
string|'"is %(actual)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidDiskFormat
dedent|''
name|'class'
name|'InvalidDiskFormat'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Disk format %(disk_format)s is not acceptable"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImageUnacceptable
dedent|''
name|'class'
name|'ImageUnacceptable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Image %(image_id)s is unacceptable"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceUnacceptable
dedent|''
name|'class'
name|'InstanceUnacceptable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s is unacceptable"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidEc2Id
dedent|''
name|'class'
name|'InvalidEc2Id'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Ec2 id %(ec2_id)s is unacceptable."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NotFound
dedent|''
name|'class'
name|'NotFound'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Resource could not be found."'
op|')'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'super'
op|'('
name|'NotFound'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FlagNotSet
dedent|''
dedent|''
name|'class'
name|'FlagNotSet'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Required flag %(flag)s not set."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceNotFound
dedent|''
name|'class'
name|'InstanceNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeNotFound
dedent|''
name|'class'
name|'VolumeNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Volume %(volume_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SfAccountNotFound
dedent|''
name|'class'
name|'SfAccountNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Unable to locate account %(account_name) on Solidfire device"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeNotFoundForInstance
dedent|''
name|'class'
name|'VolumeNotFoundForInstance'
op|'('
name|'VolumeNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Volume not found for instance %(instance_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeMetadataNotFound
dedent|''
name|'class'
name|'VolumeMetadataNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Volume %(volume_id)s has no metadata with "'
nl|'\n'
string|'"key %(metadata_key)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoVolumeTypesFound
dedent|''
name|'class'
name|'NoVolumeTypesFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Zero volume types found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeTypeNotFound
dedent|''
name|'class'
name|'VolumeTypeNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Volume type %(volume_type_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeTypeNotFoundByName
dedent|''
name|'class'
name|'VolumeTypeNotFoundByName'
op|'('
name|'VolumeTypeNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Volume type with name %(volume_type_name)s "'
nl|'\n'
string|'"could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeTypeExtraSpecsNotFound
dedent|''
name|'class'
name|'VolumeTypeExtraSpecsNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Volume Type %(volume_type_id)s has no extra specs with "'
nl|'\n'
string|'"key %(extra_specs_key)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SnapshotNotFound
dedent|''
name|'class'
name|'SnapshotNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Snapshot %(snapshot_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeIsBusy
dedent|''
name|'class'
name|'VolumeIsBusy'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"deleting volume %(volume_name)s that has snapshot"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ISCSITargetNotFoundForVolume
dedent|''
name|'class'
name|'ISCSITargetNotFoundForVolume'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"No target id found for volume %(volume_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DiskNotFound
dedent|''
name|'class'
name|'DiskNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"No disk at %(location)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeDriverNotFound
dedent|''
name|'class'
name|'VolumeDriverNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Could not find a handler for %(driver_type)s volume."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidImageRef
dedent|''
name|'class'
name|'InvalidImageRef'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid image href %(image_href)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ListingImageRefsNotSupported
dedent|''
name|'class'
name|'ListingImageRefsNotSupported'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Some images have been stored via hrefs."'
nl|'\n'
op|'+'
string|'" This version of the api does not support displaying image hrefs."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImageNotFound
dedent|''
name|'class'
name|'ImageNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Image %(image_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|KernelNotFoundForImage
dedent|''
name|'class'
name|'KernelNotFoundForImage'
op|'('
name|'ImageNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Kernel not found for image %(image_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UserNotFound
dedent|''
name|'class'
name|'UserNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"User %(user_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ProjectNotFound
dedent|''
name|'class'
name|'ProjectNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Project %(project_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ProjectMembershipNotFound
dedent|''
name|'class'
name|'ProjectMembershipNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"User %(user_id)s is not a member of project %(project_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UserRoleNotFound
dedent|''
name|'class'
name|'UserRoleNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Role %(role_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|StorageRepositoryNotFound
dedent|''
name|'class'
name|'StorageRepositoryNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Cannot find SR to read/write VDI."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotCreated
dedent|''
name|'class'
name|'NetworkNotCreated'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"%(req)s is required to create a network."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFound
dedent|''
name|'class'
name|'NetworkNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Network %(network_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFoundForBridge
dedent|''
name|'class'
name|'NetworkNotFoundForBridge'
op|'('
name|'NetworkNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Network could not be found for bridge %(bridge)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFoundForUUID
dedent|''
name|'class'
name|'NetworkNotFoundForUUID'
op|'('
name|'NetworkNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Network could not be found for uuid %(uuid)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFoundForCidr
dedent|''
name|'class'
name|'NetworkNotFoundForCidr'
op|'('
name|'NetworkNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Network could not be found with cidr %(cidr)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFoundForInstance
dedent|''
name|'class'
name|'NetworkNotFoundForInstance'
op|'('
name|'NetworkNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Network could not be found for instance %(instance_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoNetworksFound
dedent|''
name|'class'
name|'NoNetworksFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"No networks defined."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFoundForProject
dedent|''
name|'class'
name|'NetworkNotFoundForProject'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Either Network uuid %(network_uuid)s is not present or "'
nl|'\n'
string|'"is not assigned to the project %(project_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkHostNotSet
dedent|''
name|'class'
name|'NetworkHostNotSet'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Host is not set to the network (%(network_id)s)."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DatastoreNotFound
dedent|''
name|'class'
name|'DatastoreNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Could not find the datastore reference(s) which the VM uses."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFound
dedent|''
name|'class'
name|'FixedIpNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"No fixed IP associated with id %(id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForAddress
dedent|''
name|'class'
name|'FixedIpNotFoundForAddress'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Fixed ip not found for address %(address)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForInstance
dedent|''
name|'class'
name|'FixedIpNotFoundForInstance'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s has zero fixed ips."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForNetworkHost
dedent|''
name|'class'
name|'FixedIpNotFoundForNetworkHost'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Network host %(host)s has zero fixed ips "'
nl|'\n'
string|'"in network %(network_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForSpecificInstance
dedent|''
name|'class'
name|'FixedIpNotFoundForSpecificInstance'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s doesn\'t have fixed ip \'%(ip)s\'."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForHost
dedent|''
name|'class'
name|'FixedIpNotFoundForHost'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Host %(host)s has zero fixed ips."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForNetwork
dedent|''
name|'class'
name|'FixedIpNotFoundForNetwork'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Fixed IP address (%(address)s) does not exist in "'
nl|'\n'
string|'"network (%(network_uuid)s)."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpAlreadyInUse
dedent|''
name|'class'
name|'FixedIpAlreadyInUse'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Fixed IP address %(address)s is already in use."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpInvalid
dedent|''
name|'class'
name|'FixedIpInvalid'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Fixed IP address %(address)s is invalid."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoMoreFixedIps
dedent|''
name|'class'
name|'NoMoreFixedIps'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Zero fixed ips available."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoFixedIpsDefined
dedent|''
name|'class'
name|'NoFixedIpsDefined'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Zero fixed ips could be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpNotFound
dedent|''
name|'class'
name|'FloatingIpNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Floating ip not found for id %(id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpDNSExists
dedent|''
name|'class'
name|'FloatingIpDNSExists'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"The DNS entry %(name)s already exists in domain %(domain)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpNotFoundForAddress
dedent|''
name|'class'
name|'FloatingIpNotFoundForAddress'
op|'('
name|'FloatingIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Floating ip not found for address %(address)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpNotFoundForHost
dedent|''
name|'class'
name|'FloatingIpNotFoundForHost'
op|'('
name|'FloatingIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Floating ip not found for host %(host)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoMoreFloatingIps
dedent|''
name|'class'
name|'NoMoreFloatingIps'
op|'('
name|'FloatingIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Zero floating ips available."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpAssociated
dedent|''
name|'class'
name|'FloatingIpAssociated'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Floating ip %(address)s is associated."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpNotAssociated
dedent|''
name|'class'
name|'FloatingIpNotAssociated'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Floating ip %(address)s is not associated."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoFloatingIpsDefined
dedent|''
name|'class'
name|'NoFloatingIpsDefined'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Zero floating ips exist."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoFloatingIpInterface
dedent|''
name|'class'
name|'NoFloatingIpInterface'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Interface %(interface)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|KeypairNotFound
dedent|''
name|'class'
name|'KeypairNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Keypair %(name)s not found for user %(user_id)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CertificateNotFound
dedent|''
name|'class'
name|'CertificateNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Certificate %(certificate_id)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ServiceNotFound
dedent|''
name|'class'
name|'ServiceNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Service %(service_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|HostNotFound
dedent|''
name|'class'
name|'HostNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Host %(host)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ComputeHostNotFound
dedent|''
name|'class'
name|'ComputeHostNotFound'
op|'('
name|'HostNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Compute host %(host)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|HostBinaryNotFound
dedent|''
name|'class'
name|'HostBinaryNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Could not find binary %(binary)s on host %(host)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AuthTokenNotFound
dedent|''
name|'class'
name|'AuthTokenNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Auth token %(token)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AccessKeyNotFound
dedent|''
name|'class'
name|'AccessKeyNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Access Key %(access_key)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|QuotaNotFound
dedent|''
name|'class'
name|'QuotaNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Quota could not be found"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ProjectQuotaNotFound
dedent|''
name|'class'
name|'ProjectQuotaNotFound'
op|'('
name|'QuotaNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Quota for project %(project_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupNotFound
dedent|''
name|'class'
name|'SecurityGroupNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Security group %(security_group_id)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupNotFoundForProject
dedent|''
name|'class'
name|'SecurityGroupNotFoundForProject'
op|'('
name|'SecurityGroupNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Security group %(security_group_id)s not found "'
nl|'\n'
string|'"for project %(project_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupNotFoundForRule
dedent|''
name|'class'
name|'SecurityGroupNotFoundForRule'
op|'('
name|'SecurityGroupNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Security group with rule %(rule_id)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupExistsForInstance
dedent|''
name|'class'
name|'SecurityGroupExistsForInstance'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Security group %(security_group_id)s is already associated"'
nl|'\n'
string|'" with the instance %(instance_id)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupNotExistsForInstance
dedent|''
name|'class'
name|'SecurityGroupNotExistsForInstance'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Security group %(security_group_id)s is not associated with"'
nl|'\n'
string|'" the instance %(instance_id)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MigrationNotFound
dedent|''
name|'class'
name|'MigrationNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Migration %(migration_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MigrationNotFoundByStatus
dedent|''
name|'class'
name|'MigrationNotFoundByStatus'
op|'('
name|'MigrationNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Migration not found for instance %(instance_id)s "'
nl|'\n'
string|'"with status %(status)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsolePoolNotFound
dedent|''
name|'class'
name|'ConsolePoolNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Console pool %(pool_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsolePoolNotFoundForHostType
dedent|''
name|'class'
name|'ConsolePoolNotFoundForHostType'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Console pool of type %(console_type)s "'
nl|'\n'
string|'"for compute host %(compute_host)s "'
nl|'\n'
string|'"on proxy host %(host)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsoleNotFound
dedent|''
name|'class'
name|'ConsoleNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Console %(console_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsoleNotFoundForInstance
dedent|''
name|'class'
name|'ConsoleNotFoundForInstance'
op|'('
name|'ConsoleNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Console for instance %(instance_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsoleNotFoundInPoolForInstance
dedent|''
name|'class'
name|'ConsoleNotFoundInPoolForInstance'
op|'('
name|'ConsoleNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Console for instance %(instance_id)s "'
nl|'\n'
string|'"in pool %(pool_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsoleTypeInvalid
dedent|''
name|'class'
name|'ConsoleTypeInvalid'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Invalid console type %(console_type)s "'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoInstanceTypesFound
dedent|''
name|'class'
name|'NoInstanceTypesFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Zero instance types found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeNotFound
dedent|''
name|'class'
name|'InstanceTypeNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance type %(instance_type_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeNotFoundByName
dedent|''
name|'class'
name|'InstanceTypeNotFoundByName'
op|'('
name|'InstanceTypeNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance type with name %(instance_type_name)s "'
nl|'\n'
string|'"could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FlavorNotFound
dedent|''
name|'class'
name|'FlavorNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Flavor %(flavor_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ZoneNotFound
dedent|''
name|'class'
name|'ZoneNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Zone %(zone_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SchedulerHostFilterNotFound
dedent|''
name|'class'
name|'SchedulerHostFilterNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Scheduler Host Filter %(filter_name)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SchedulerCostFunctionNotFound
dedent|''
name|'class'
name|'SchedulerCostFunctionNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Scheduler cost function %(cost_fn_str)s could"'
nl|'\n'
string|'" not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SchedulerWeightFlagNotFound
dedent|''
name|'class'
name|'SchedulerWeightFlagNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Scheduler weight flag not found: %(flag_name)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceMetadataNotFound
dedent|''
name|'class'
name|'InstanceMetadataNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s has no metadata with "'
nl|'\n'
string|'"key %(metadata_key)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeExtraSpecsNotFound
dedent|''
name|'class'
name|'InstanceTypeExtraSpecsNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance Type %(instance_type_id)s has no extra specs with "'
nl|'\n'
string|'"key %(extra_specs_key)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|LDAPObjectNotFound
dedent|''
name|'class'
name|'LDAPObjectNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"LDAP object could not be found"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|LDAPUserNotFound
dedent|''
name|'class'
name|'LDAPUserNotFound'
op|'('
name|'LDAPObjectNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"LDAP user %(user_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|LDAPGroupNotFound
dedent|''
name|'class'
name|'LDAPGroupNotFound'
op|'('
name|'LDAPObjectNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"LDAP group %(group_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|LDAPGroupMembershipNotFound
dedent|''
name|'class'
name|'LDAPGroupMembershipNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"LDAP user %(user_id)s is not a member of group %(group_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FileNotFound
dedent|''
name|'class'
name|'FileNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"File %(file_path)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoFilesFound
dedent|''
name|'class'
name|'NoFilesFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Zero files could be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SwitchNotFoundForNetworkAdapter
dedent|''
name|'class'
name|'SwitchNotFoundForNetworkAdapter'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Virtual switch associated with the "'
nl|'\n'
string|'"network adapter %(adapter)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkAdapterNotFound
dedent|''
name|'class'
name|'NetworkAdapterNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Network adapter %(adapter)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ClassNotFound
dedent|''
name|'class'
name|'ClassNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Class %(class_name)s could not be found: %(exception)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NotAllowed
dedent|''
name|'class'
name|'NotAllowed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Action not allowed."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|GlobalRoleNotAllowed
dedent|''
name|'class'
name|'GlobalRoleNotAllowed'
op|'('
name|'NotAllowed'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Unable to use global role %(role_id)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImageRotationNotAllowed
dedent|''
name|'class'
name|'ImageRotationNotAllowed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Rotation is not allowed for snapshots"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|RotationRequiredForBackup
dedent|''
name|'class'
name|'RotationRequiredForBackup'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Rotation param is required for backup image_type"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
comment|'#TODO(bcwaldon): EOL this exception!'
nl|'\n'
DECL|class|Duplicate
dedent|''
name|'class'
name|'Duplicate'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'pass'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|KeyPairExists
dedent|''
name|'class'
name|'KeyPairExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Key pair %(key_name)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UserExists
dedent|''
name|'class'
name|'UserExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"User %(user)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|LDAPUserExists
dedent|''
name|'class'
name|'LDAPUserExists'
op|'('
name|'UserExists'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"LDAP user %(user)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|LDAPGroupExists
dedent|''
name|'class'
name|'LDAPGroupExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"LDAP group %(group)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|LDAPMembershipExists
dedent|''
name|'class'
name|'LDAPMembershipExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"User %(uid)s is already a member of "'
nl|'\n'
string|'"the group %(group_dn)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ProjectExists
dedent|''
name|'class'
name|'ProjectExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Project %(project)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceExists
dedent|''
name|'class'
name|'InstanceExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance %(name)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeExists
dedent|''
name|'class'
name|'InstanceTypeExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance Type %(name)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeTypeExists
dedent|''
name|'class'
name|'VolumeTypeExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Volume Type %(name)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidSharedStorage
dedent|''
name|'class'
name|'InvalidSharedStorage'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"%(path)s is on shared storage: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MigrationError
dedent|''
name|'class'
name|'MigrationError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Migration error"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MalformedRequestBody
dedent|''
name|'class'
name|'MalformedRequestBody'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Malformed message body: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConfigNotFound
dedent|''
name|'class'
name|'ConfigNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Could not find config at %(path)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|PasteAppNotFound
dedent|''
name|'class'
name|'PasteAppNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Could not load paste app \'%(name)s\' from %(path)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VSANovaAccessParamNotFound
dedent|''
name|'class'
name|'VSANovaAccessParamNotFound'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Nova access parameters were not specified."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VirtualStorageArrayNotFound
dedent|''
name|'class'
name|'VirtualStorageArrayNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Virtual Storage Array %(id)d could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VirtualStorageArrayNotFoundByName
dedent|''
name|'class'
name|'VirtualStorageArrayNotFoundByName'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Virtual Storage Array %(name)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CannotResizeToSameSize
dedent|''
name|'class'
name|'CannotResizeToSameSize'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"When resizing, instances must change size!"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImageTooLarge
dedent|''
name|'class'
name|'ImageTooLarge'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Image is larger than instance type allows"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ZoneRequestError
dedent|''
name|'class'
name|'ZoneRequestError'
op|'('
name|'Error'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'message'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'message'
name|'is'
name|'None'
op|':'
newline|'\n'
indent|'            '
name|'message'
op|'='
name|'_'
op|'('
string|'"1 or more Zones could not complete the request"'
op|')'
newline|'\n'
dedent|''
name|'super'
op|'('
name|'ZoneRequestError'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'message'
op|'='
name|'message'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeMemoryTooSmall
dedent|''
dedent|''
name|'class'
name|'InstanceTypeMemoryTooSmall'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance type\'s memory is too small for requested image."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeDiskTooSmall
dedent|''
name|'class'
name|'InstanceTypeDiskTooSmall'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance type\'s disk is too small for requested image."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InsufficientFreeMemory
dedent|''
name|'class'
name|'InsufficientFreeMemory'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Insufficient free memory on compute node to start %(uuid)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CouldNotFetchMetrics
dedent|''
name|'class'
name|'CouldNotFetchMetrics'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Could not fetch bandwidth/cpu/disk metrics for this host."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoValidHost
dedent|''
name|'class'
name|'NoValidHost'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"No valid host was found. %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|WillNotSchedule
dedent|''
name|'class'
name|'WillNotSchedule'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Host %(host)s is not up or doesn\'t exist."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|QuotaError
dedent|''
name|'class'
name|'QuotaError'
op|'('
name|'ApiError'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Quota Exceeded."""'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateNotFound
dedent|''
name|'class'
name|'AggregateNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateNameExists
dedent|''
name|'class'
name|'AggregateNameExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_name)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateHostNotFound
dedent|''
name|'class'
name|'AggregateHostNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_id)s has no host %(host)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateMetadataNotFound
dedent|''
name|'class'
name|'AggregateMetadataNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_id)s has no metadata with "'
nl|'\n'
string|'"key %(metadata_key)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateHostConflict
dedent|''
name|'class'
name|'AggregateHostConflict'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Host %(host)s already member of another aggregate."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateHostExists
dedent|''
name|'class'
name|'AggregateHostExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_id)s already has host %(host)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DuplicateSfVolumeNames
dedent|''
name|'class'
name|'DuplicateSfVolumeNames'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Detected more than one volume with name %(vol_name)"'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
