begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Nova base exception handling.\n\nIncludes decorator for re-raising Nova-type exceptions.\n\nSHOULD include dedicated exception logging.\n\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'functools'
newline|'\n'
name|'import'
name|'sys'
newline|'\n'
nl|'\n'
name|'from'
name|'oslo'
op|'.'
name|'config'
name|'import'
name|'cfg'
newline|'\n'
name|'import'
name|'webob'
op|'.'
name|'exc'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
name|'import'
name|'excutils'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
op|'.'
name|'gettextutils'
name|'import'
name|'_'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'openstack'
op|'.'
name|'common'
name|'import'
name|'log'
name|'as'
name|'logging'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'safe_utils'
newline|'\n'
nl|'\n'
DECL|variable|LOG
name|'LOG'
op|'='
name|'logging'
op|'.'
name|'getLogger'
op|'('
name|'__name__'
op|')'
newline|'\n'
nl|'\n'
DECL|variable|exc_log_opts
name|'exc_log_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'BoolOpt'
op|'('
string|"'fatal_exception_format_errors'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
name|'False'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'make exception message format errors fatal'"
op|')'
op|','
nl|'\n'
op|']'
newline|'\n'
nl|'\n'
DECL|variable|CONF
name|'CONF'
op|'='
name|'cfg'
op|'.'
name|'CONF'
newline|'\n'
name|'CONF'
op|'.'
name|'register_opts'
op|'('
name|'exc_log_opts'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConvertedException
name|'class'
name|'ConvertedException'
op|'('
name|'webob'
op|'.'
name|'exc'
op|'.'
name|'WSGIHTTPException'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'code'
op|'='
number|'0'
op|','
name|'title'
op|'='
string|'""'
op|','
name|'explanation'
op|'='
string|'""'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'code'
op|'='
name|'code'
newline|'\n'
name|'self'
op|'.'
name|'title'
op|'='
name|'title'
newline|'\n'
name|'self'
op|'.'
name|'explanation'
op|'='
name|'explanation'
newline|'\n'
name|'super'
op|'('
name|'ConvertedException'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|_cleanse_dict
dedent|''
dedent|''
name|'def'
name|'_cleanse_dict'
op|'('
name|'original'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Strip all admin_password, new_pass, rescue_pass keys from a dict."""'
newline|'\n'
name|'return'
name|'dict'
op|'('
op|'('
name|'k'
op|','
name|'v'
op|')'
name|'for'
name|'k'
op|','
name|'v'
name|'in'
name|'original'
op|'.'
name|'iteritems'
op|'('
op|')'
name|'if'
name|'not'
string|'"_pass"'
name|'in'
name|'k'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|wrap_exception
dedent|''
name|'def'
name|'wrap_exception'
op|'('
name|'notifier'
op|'='
name|'None'
op|','
name|'publisher_id'
op|'='
name|'None'
op|','
name|'event_type'
op|'='
name|'None'
op|','
nl|'\n'
name|'level'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""This decorator wraps a method to catch any exceptions that may\n    get thrown. It logs the exception as well as optionally sending\n    it to the notification system.\n    """'
newline|'\n'
comment|"# TODO(sandy): Find a way to import nova.notifier.api so we don't have"
nl|'\n'
comment|'# to pass it in as a parameter. Otherwise we get a cyclic import of'
nl|'\n'
comment|'# nova.notifier.api -> nova.utils -> nova.exception :('
nl|'\n'
DECL|function|inner
name|'def'
name|'inner'
op|'('
name|'f'
op|')'
op|':'
newline|'\n'
DECL|function|wrapped
indent|'        '
name|'def'
name|'wrapped'
op|'('
name|'self'
op|','
name|'context'
op|','
op|'*'
name|'args'
op|','
op|'**'
name|'kw'
op|')'
op|':'
newline|'\n'
comment|"# Don't store self or context in the payload, it now seems to"
nl|'\n'
comment|'# contain confidential information.'
nl|'\n'
indent|'            '
name|'try'
op|':'
newline|'\n'
indent|'                '
name|'return'
name|'f'
op|'('
name|'self'
op|','
name|'context'
op|','
op|'*'
name|'args'
op|','
op|'**'
name|'kw'
op|')'
newline|'\n'
dedent|''
name|'except'
name|'Exception'
name|'as'
name|'e'
op|':'
newline|'\n'
indent|'                '
name|'with'
name|'excutils'
op|'.'
name|'save_and_reraise_exception'
op|'('
op|')'
op|':'
newline|'\n'
indent|'                    '
name|'if'
name|'notifier'
op|':'
newline|'\n'
indent|'                        '
name|'payload'
op|'='
name|'dict'
op|'('
name|'exception'
op|'='
name|'e'
op|')'
newline|'\n'
name|'call_dict'
op|'='
name|'safe_utils'
op|'.'
name|'getcallargs'
op|'('
name|'f'
op|','
op|'*'
name|'args'
op|','
op|'**'
name|'kw'
op|')'
newline|'\n'
name|'cleansed'
op|'='
name|'_cleanse_dict'
op|'('
name|'call_dict'
op|')'
newline|'\n'
name|'payload'
op|'.'
name|'update'
op|'('
op|'{'
string|"'args'"
op|':'
name|'cleansed'
op|'}'
op|')'
newline|'\n'
nl|'\n'
comment|"# Use a temp vars so we don't shadow"
nl|'\n'
comment|'# our outer definitions.'
nl|'\n'
name|'temp_level'
op|'='
name|'level'
newline|'\n'
name|'if'
name|'not'
name|'temp_level'
op|':'
newline|'\n'
indent|'                            '
name|'temp_level'
op|'='
name|'notifier'
op|'.'
name|'ERROR'
newline|'\n'
nl|'\n'
dedent|''
name|'temp_type'
op|'='
name|'event_type'
newline|'\n'
name|'if'
name|'not'
name|'temp_type'
op|':'
newline|'\n'
comment|'# If f has multiple decorators, they must use'
nl|'\n'
comment|'# functools.wraps to ensure the name is'
nl|'\n'
comment|'# propagated.'
nl|'\n'
indent|'                            '
name|'temp_type'
op|'='
name|'f'
op|'.'
name|'__name__'
newline|'\n'
nl|'\n'
dedent|''
name|'notifier'
op|'.'
name|'notify'
op|'('
name|'context'
op|','
name|'publisher_id'
op|','
name|'temp_type'
op|','
nl|'\n'
name|'temp_level'
op|','
name|'payload'
op|')'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
dedent|''
dedent|''
name|'return'
name|'functools'
op|'.'
name|'wraps'
op|'('
name|'f'
op|')'
op|'('
name|'wrapped'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'inner'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NovaException
dedent|''
name|'class'
name|'NovaException'
op|'('
name|'Exception'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Base Nova Exception\n\n    To correctly use this class, inherit from it and define\n    a \'msg_fmt\' property. That msg_fmt will get printf\'d\n    with the keyword arguments provided to the constructor.\n\n    """'
newline|'\n'
DECL|variable|msg_fmt
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"An unknown exception occurred."'
op|')'
newline|'\n'
DECL|variable|code
name|'code'
op|'='
number|'500'
newline|'\n'
DECL|variable|headers
name|'headers'
op|'='
op|'{'
op|'}'
newline|'\n'
DECL|variable|safe
name|'safe'
op|'='
name|'False'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'message'
op|'='
name|'None'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'kwargs'
op|'='
name|'kwargs'
newline|'\n'
nl|'\n'
name|'if'
string|"'code'"
name|'not'
name|'in'
name|'self'
op|'.'
name|'kwargs'
op|':'
newline|'\n'
indent|'            '
name|'try'
op|':'
newline|'\n'
indent|'                '
name|'self'
op|'.'
name|'kwargs'
op|'['
string|"'code'"
op|']'
op|'='
name|'self'
op|'.'
name|'code'
newline|'\n'
dedent|''
name|'except'
name|'AttributeError'
op|':'
newline|'\n'
indent|'                '
name|'pass'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
name|'if'
name|'not'
name|'message'
op|':'
newline|'\n'
indent|'            '
name|'try'
op|':'
newline|'\n'
indent|'                '
name|'message'
op|'='
name|'self'
op|'.'
name|'msg_fmt'
op|'%'
name|'kwargs'
newline|'\n'
nl|'\n'
dedent|''
name|'except'
name|'Exception'
op|':'
newline|'\n'
indent|'                '
name|'exc_info'
op|'='
name|'sys'
op|'.'
name|'exc_info'
op|'('
op|')'
newline|'\n'
comment|"# kwargs doesn't match a variable in the message"
nl|'\n'
comment|'# log the issue and the kwargs'
nl|'\n'
name|'LOG'
op|'.'
name|'exception'
op|'('
name|'_'
op|'('
string|"'Exception in string format operation'"
op|')'
op|')'
newline|'\n'
name|'for'
name|'name'
op|','
name|'value'
name|'in'
name|'kwargs'
op|'.'
name|'iteritems'
op|'('
op|')'
op|':'
newline|'\n'
indent|'                    '
name|'LOG'
op|'.'
name|'error'
op|'('
string|'"%s: %s"'
op|'%'
op|'('
name|'name'
op|','
name|'value'
op|')'
op|')'
newline|'\n'
nl|'\n'
dedent|''
name|'if'
name|'CONF'
op|'.'
name|'fatal_exception_format_errors'
op|':'
newline|'\n'
indent|'                    '
name|'raise'
name|'exc_info'
op|'['
number|'0'
op|']'
op|','
name|'exc_info'
op|'['
number|'1'
op|']'
op|','
name|'exc_info'
op|'['
number|'2'
op|']'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
comment|'# at least get the core message out if something happened'
nl|'\n'
indent|'                    '
name|'message'
op|'='
name|'self'
op|'.'
name|'msg_fmt'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
dedent|''
name|'super'
op|'('
name|'NovaException'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'message'
op|')'
newline|'\n'
nl|'\n'
DECL|member|format_message
dedent|''
name|'def'
name|'format_message'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'self'
op|'.'
name|'__class__'
op|'.'
name|'__name__'
op|'.'
name|'endswith'
op|'('
string|"'_Remote'"
op|')'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'self'
op|'.'
name|'args'
op|'['
number|'0'
op|']'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'unicode'
op|'('
name|'self'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|EC2APIError
dedent|''
dedent|''
dedent|''
name|'class'
name|'EC2APIError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Unknown"'
op|')'
newline|'\n'
nl|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'message'
op|'='
name|'None'
op|','
name|'code'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'msg'
op|'='
name|'message'
newline|'\n'
name|'self'
op|'.'
name|'code'
op|'='
name|'code'
newline|'\n'
name|'outstr'
op|'='
string|"'%s'"
op|'%'
name|'message'
newline|'\n'
name|'super'
op|'('
name|'EC2APIError'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'outstr'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
comment|'#TODO(bcwaldon): EOL this exception!'
nl|'\n'
DECL|class|Duplicate
dedent|''
dedent|''
name|'class'
name|'Duplicate'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'pass'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|EncryptionFailure
dedent|''
name|'class'
name|'EncryptionFailure'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to encrypt text: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DecryptionFailure
dedent|''
name|'class'
name|'DecryptionFailure'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to decrypt text: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VirtualInterfaceCreateException
dedent|''
name|'class'
name|'VirtualInterfaceCreateException'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Virtual Interface creation failed"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VirtualInterfaceMacAddressException
dedent|''
name|'class'
name|'VirtualInterfaceMacAddressException'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"5 attempts to create virtual interface"'
nl|'\n'
string|'"with unique mac address failed"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|GlanceConnectionFailed
dedent|''
name|'class'
name|'GlanceConnectionFailed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Connection to glance host %(host)s:%(port)s failed: "'
nl|'\n'
string|'"%(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NotAuthorized
dedent|''
name|'class'
name|'NotAuthorized'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Not authorized."'
op|')'
newline|'\n'
DECL|variable|code
name|'code'
op|'='
number|'403'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AdminRequired
dedent|''
name|'class'
name|'AdminRequired'
op|'('
name|'NotAuthorized'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"User does not have admin privileges"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|PolicyNotAuthorized
dedent|''
name|'class'
name|'PolicyNotAuthorized'
op|'('
name|'NotAuthorized'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Policy doesn\'t allow %(action)s to be performed."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImageNotActive
dedent|''
name|'class'
name|'ImageNotActive'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Image %(image_id)s is not active."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImageNotAuthorized
dedent|''
name|'class'
name|'ImageNotAuthorized'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Not authorized for image %(image_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|Invalid
dedent|''
name|'class'
name|'Invalid'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Unacceptable parameters."'
op|')'
newline|'\n'
DECL|variable|code
name|'code'
op|'='
number|'400'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidBDM
dedent|''
name|'class'
name|'InvalidBDM'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Block Device Mapping is Invalid."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidBDMSnapshot
dedent|''
name|'class'
name|'InvalidBDMSnapshot'
op|'('
name|'InvalidBDM'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Block Device Mapping is Invalid: "'
nl|'\n'
string|'"failed to get snapshot %(id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidBDMVolume
dedent|''
name|'class'
name|'InvalidBDMVolume'
op|'('
name|'InvalidBDM'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Block Device Mapping is Invalid: "'
nl|'\n'
string|'"failed to get volume %(id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidBDMFormat
dedent|''
name|'class'
name|'InvalidBDMFormat'
op|'('
name|'InvalidBDM'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Block Device Mapping is Invalid: "'
nl|'\n'
string|'"%(details)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidBDMForLegacy
dedent|''
name|'class'
name|'InvalidBDMForLegacy'
op|'('
name|'InvalidBDM'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Block Device Mapping cannot "'
nl|'\n'
string|'"be converted to legacy format. "'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeUnattached
dedent|''
name|'class'
name|'VolumeUnattached'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Volume %(volume_id)s is not attached to anything"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeNotCreated
dedent|''
name|'class'
name|'VolumeNotCreated'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Volume %(volume_id)s did not finish being created"'
nl|'\n'
string|'" even after we waited %(seconds)s seconds or %(attempts)s"'
nl|'\n'
string|'" attempts."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidKeypair
dedent|''
name|'class'
name|'InvalidKeypair'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Keypair data is invalid"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidRequest
dedent|''
name|'class'
name|'InvalidRequest'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The request is invalid."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidInput
dedent|''
name|'class'
name|'InvalidInput'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid input received"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidVolume
dedent|''
name|'class'
name|'InvalidVolume'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid volume"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidMetadata
dedent|''
name|'class'
name|'InvalidMetadata'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid metadata"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidMetadataSize
dedent|''
name|'class'
name|'InvalidMetadataSize'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid metadata size"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidPortRange
dedent|''
name|'class'
name|'InvalidPortRange'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid port range %(from_port)s:%(to_port)s. %(msg)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidIpProtocol
dedent|''
name|'class'
name|'InvalidIpProtocol'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid IP protocol %(protocol)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidContentType
dedent|''
name|'class'
name|'InvalidContentType'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid content type %(content_type)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidCidr
dedent|''
name|'class'
name|'InvalidCidr'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid cidr %(cidr)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidUnicodeParameter
dedent|''
name|'class'
name|'InvalidUnicodeParameter'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid Parameter: "'
nl|'\n'
string|'"Unicode is not supported by the current database."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
comment|'# Cannot be templated as the error syntax varies.'
nl|'\n'
comment|'# msg needs to be constructed when raised.'
nl|'\n'
DECL|class|InvalidParameterValue
dedent|''
name|'class'
name|'InvalidParameterValue'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"%(err)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidAggregateAction
dedent|''
name|'class'
name|'InvalidAggregateAction'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Cannot perform action \'%(action)s\' on aggregate "'
nl|'\n'
string|'"%(aggregate_id)s. Reason: %(reason)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidGroup
dedent|''
name|'class'
name|'InvalidGroup'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Group not valid. Reason: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidSortKey
dedent|''
name|'class'
name|'InvalidSortKey'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Sort key supplied was not valid."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceInvalidState
dedent|''
name|'class'
name|'InstanceInvalidState'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot "'
nl|'\n'
string|'"%(method)s while the instance is in this state."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceNotRunning
dedent|''
name|'class'
name|'InstanceNotRunning'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s is not running."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceNotInRescueMode
dedent|''
name|'class'
name|'InstanceNotInRescueMode'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s is not in rescue mode"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceNotRescuable
dedent|''
name|'class'
name|'InstanceNotRescuable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s cannot be rescued: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceNotReady
dedent|''
name|'class'
name|'InstanceNotReady'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s is not ready"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceSuspendFailure
dedent|''
name|'class'
name|'InstanceSuspendFailure'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to suspend instance"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceResumeFailure
dedent|''
name|'class'
name|'InstanceResumeFailure'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to resume instance: %(reason)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstancePowerOnFailure
dedent|''
name|'class'
name|'InstancePowerOnFailure'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to power on instance: %(reason)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstancePowerOffFailure
dedent|''
name|'class'
name|'InstancePowerOffFailure'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to power off instance: %(reason)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceRebootFailure
dedent|''
name|'class'
name|'InstanceRebootFailure'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to reboot instance"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTerminationFailure
dedent|''
name|'class'
name|'InstanceTerminationFailure'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to terminate instance"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceDeployFailure
dedent|''
name|'class'
name|'InstanceDeployFailure'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to deploy instance"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ServiceUnavailable
dedent|''
name|'class'
name|'ServiceUnavailable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Service is unavailable at this time."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ComputeResourcesUnavailable
dedent|''
name|'class'
name|'ComputeResourcesUnavailable'
op|'('
name|'ServiceUnavailable'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Insufficient compute resources."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ComputeServiceUnavailable
dedent|''
name|'class'
name|'ComputeServiceUnavailable'
op|'('
name|'ServiceUnavailable'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Compute service of %(host)s is unavailable at this time."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UnableToMigrateToSelf
dedent|''
name|'class'
name|'UnableToMigrateToSelf'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Unable to migrate instance (%(instance_id)s) "'
nl|'\n'
string|'"to current host (%(host)s)."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidHypervisorType
dedent|''
name|'class'
name|'InvalidHypervisorType'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The supplied hypervisor type of is invalid."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DestinationHypervisorTooOld
dedent|''
name|'class'
name|'DestinationHypervisorTooOld'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The instance requires a newer hypervisor version than "'
nl|'\n'
string|'"has been provided."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DestinationDiskExists
dedent|''
name|'class'
name|'DestinationDiskExists'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The supplied disk path (%(path)s) already exists, "'
nl|'\n'
string|'"it is expected not to exist."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidDevicePath
dedent|''
name|'class'
name|'InvalidDevicePath'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The supplied device path (%(path)s) is invalid."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DevicePathInUse
dedent|''
name|'class'
name|'DevicePathInUse'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The supplied device path (%(path)s) is in use."'
op|')'
newline|'\n'
DECL|variable|code
name|'code'
op|'='
number|'409'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DeviceIsBusy
dedent|''
name|'class'
name|'DeviceIsBusy'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The supplied device (%(device)s) is busy."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidCPUInfo
dedent|''
name|'class'
name|'InvalidCPUInfo'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Unacceptable CPU info"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidIpAddressError
dedent|''
name|'class'
name|'InvalidIpAddressError'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"%(address)s is not a valid IP v4/6 address."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidVLANTag
dedent|''
name|'class'
name|'InvalidVLANTag'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"VLAN tag is not appropriate for the port group "'
nl|'\n'
string|'"%(bridge)s. Expected VLAN tag is %(tag)s, "'
nl|'\n'
string|'"but the one associated with the port group is %(pgroup)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidVLANPortGroup
dedent|''
name|'class'
name|'InvalidVLANPortGroup'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"vSwitch which contains the port group %(bridge)s is "'
nl|'\n'
string|'"not associated with the desired physical adapter. "'
nl|'\n'
string|'"Expected vSwitch is %(expected)s, but the one associated "'
nl|'\n'
string|'"is %(actual)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidDiskFormat
dedent|''
name|'class'
name|'InvalidDiskFormat'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Disk format %(disk_format)s is not acceptable"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImageUnacceptable
dedent|''
name|'class'
name|'ImageUnacceptable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Image %(image_id)s is unacceptable: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceUnacceptable
dedent|''
name|'class'
name|'InstanceUnacceptable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s is unacceptable: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidEc2Id
dedent|''
name|'class'
name|'InvalidEc2Id'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Ec2 id %(ec2_id)s is unacceptable."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidUUID
dedent|''
name|'class'
name|'InvalidUUID'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Expected a uuid but received %(uuid)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidID
dedent|''
name|'class'
name|'InvalidID'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid ID received %(id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConstraintNotMet
dedent|''
name|'class'
name|'ConstraintNotMet'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Constraint not met."'
op|')'
newline|'\n'
DECL|variable|code
name|'code'
op|'='
number|'412'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NotFound
dedent|''
name|'class'
name|'NotFound'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Resource could not be found."'
op|')'
newline|'\n'
DECL|variable|code
name|'code'
op|'='
number|'404'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AgentBuildNotFound
dedent|''
name|'class'
name|'AgentBuildNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"No agent-build associated with id %(id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AgentBuildExists
dedent|''
name|'class'
name|'AgentBuildExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Agent-build with hypervisor %(hypervisor)s os %(os)s "'
nl|'\n'
string|'"architecture %(architecture)s exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeNotFound
dedent|''
name|'class'
name|'VolumeNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Volume %(volume_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SnapshotNotFound
dedent|''
name|'class'
name|'SnapshotNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Snapshot %(snapshot_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ISCSITargetNotFoundForVolume
dedent|''
name|'class'
name|'ISCSITargetNotFoundForVolume'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"No target id found for volume %(volume_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DiskNotFound
dedent|''
name|'class'
name|'DiskNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"No disk at %(location)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|VolumeDriverNotFound
dedent|''
name|'class'
name|'VolumeDriverNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Could not find a handler for %(driver_type)s volume."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidImageRef
dedent|''
name|'class'
name|'InvalidImageRef'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid image href %(image_href)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImageNotFound
dedent|''
name|'class'
name|'ImageNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Image %(image_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImageNotFoundEC2
dedent|''
name|'class'
name|'ImageNotFoundEC2'
op|'('
name|'ImageNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Image %(image_id)s could not be found. The nova EC2 API "'
nl|'\n'
string|'"assigns image ids dynamically when they are listed for the "'
nl|'\n'
string|'"first time. Have you listed image ids since adding this "'
nl|'\n'
string|'"image?"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ProjectNotFound
dedent|''
name|'class'
name|'ProjectNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Project %(project_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|StorageRepositoryNotFound
dedent|''
name|'class'
name|'StorageRepositoryNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Cannot find SR to read/write VDI."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkDuplicated
dedent|''
name|'class'
name|'NetworkDuplicated'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Network %(network_id)s is duplicated."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkInUse
dedent|''
name|'class'
name|'NetworkInUse'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Network %(network_id)s is still in use."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotCreated
dedent|''
name|'class'
name|'NetworkNotCreated'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"%(req)s is required to create a network."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFound
dedent|''
name|'class'
name|'NetworkNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Network %(network_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|PortNotFound
dedent|''
name|'class'
name|'PortNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Port id %(port_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFoundForBridge
dedent|''
name|'class'
name|'NetworkNotFoundForBridge'
op|'('
name|'NetworkNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Network could not be found for bridge %(bridge)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFoundForUUID
dedent|''
name|'class'
name|'NetworkNotFoundForUUID'
op|'('
name|'NetworkNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Network could not be found for uuid %(uuid)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFoundForCidr
dedent|''
name|'class'
name|'NetworkNotFoundForCidr'
op|'('
name|'NetworkNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Network could not be found with cidr %(cidr)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFoundForInstance
dedent|''
name|'class'
name|'NetworkNotFoundForInstance'
op|'('
name|'NetworkNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Network could not be found for instance %(instance_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoNetworksFound
dedent|''
name|'class'
name|'NoNetworksFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"No networks defined."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkNotFoundForProject
dedent|''
name|'class'
name|'NetworkNotFoundForProject'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Either Network uuid %(network_uuid)s is not present or "'
nl|'\n'
string|'"is not assigned to the project %(project_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkAmbiguous
dedent|''
name|'class'
name|'NetworkAmbiguous'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"More than one possible network found. Specify "'
nl|'\n'
string|'"network ID(s) to select which one(s) to connect to,"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DatastoreNotFound
dedent|''
name|'class'
name|'DatastoreNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Could not find the datastore reference(s) which the VM uses."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|PortInUse
dedent|''
name|'class'
name|'PortInUse'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Port %(port_id)s is still in use."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|PortNotUsable
dedent|''
name|'class'
name|'PortNotUsable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Port %(port_id)s not usable for instance %(instance)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|PortNotFree
dedent|''
name|'class'
name|'PortNotFree'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"No free port available for instance %(instance)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpExists
dedent|''
name|'class'
name|'FixedIpExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Fixed ip %(address)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFound
dedent|''
name|'class'
name|'FixedIpNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"No fixed IP associated with id %(id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForAddress
dedent|''
name|'class'
name|'FixedIpNotFoundForAddress'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Fixed ip not found for address %(address)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForInstance
dedent|''
name|'class'
name|'FixedIpNotFoundForInstance'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_uuid)s has zero fixed ips."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForNetworkHost
dedent|''
name|'class'
name|'FixedIpNotFoundForNetworkHost'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Network host %(host)s has zero fixed ips "'
nl|'\n'
string|'"in network %(network_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForSpecificInstance
dedent|''
name|'class'
name|'FixedIpNotFoundForSpecificInstance'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_uuid)s doesn\'t have fixed ip \'%(ip)s\'."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpNotFoundForNetwork
dedent|''
name|'class'
name|'FixedIpNotFoundForNetwork'
op|'('
name|'FixedIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Fixed IP address (%(address)s) does not exist in "'
nl|'\n'
string|'"network (%(network_uuid)s)."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpAlreadyInUse
dedent|''
name|'class'
name|'FixedIpAlreadyInUse'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Fixed IP address %(address)s is already in use on instance "'
nl|'\n'
string|'"%(instance_uuid)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpAssociatedWithMultipleInstances
dedent|''
name|'class'
name|'FixedIpAssociatedWithMultipleInstances'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"More than one instance is associated with fixed ip address "'
nl|'\n'
string|'"\'%(address)s\'."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpInvalid
dedent|''
name|'class'
name|'FixedIpInvalid'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Fixed IP address %(address)s is invalid."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoMoreFixedIps
dedent|''
name|'class'
name|'NoMoreFixedIps'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Zero fixed ips available."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoFixedIpsDefined
dedent|''
name|'class'
name|'NoFixedIpsDefined'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Zero fixed ips could be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpExists
dedent|''
name|'class'
name|'FloatingIpExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Floating ip %(address)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpNotFound
dedent|''
name|'class'
name|'FloatingIpNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Floating ip not found for id %(id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpDNSExists
dedent|''
name|'class'
name|'FloatingIpDNSExists'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The DNS entry %(name)s already exists in domain %(domain)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpNotFoundForAddress
dedent|''
name|'class'
name|'FloatingIpNotFoundForAddress'
op|'('
name|'FloatingIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Floating ip not found for address %(address)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpNotFoundForHost
dedent|''
name|'class'
name|'FloatingIpNotFoundForHost'
op|'('
name|'FloatingIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Floating ip not found for host %(host)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpMultipleFoundForAddress
dedent|''
name|'class'
name|'FloatingIpMultipleFoundForAddress'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Multiple floating ips are found for address %(address)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpPoolNotFound
dedent|''
name|'class'
name|'FloatingIpPoolNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Floating ip pool not found."'
op|')'
newline|'\n'
DECL|variable|safe
name|'safe'
op|'='
name|'True'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoMoreFloatingIps
dedent|''
name|'class'
name|'NoMoreFloatingIps'
op|'('
name|'FloatingIpNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Zero floating ips available."'
op|')'
newline|'\n'
DECL|variable|safe
name|'safe'
op|'='
name|'True'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpAssociated
dedent|''
name|'class'
name|'FloatingIpAssociated'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Floating ip %(address)s is associated."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpNotAssociated
dedent|''
name|'class'
name|'FloatingIpNotAssociated'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Floating ip %(address)s is not associated."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoFloatingIpsDefined
dedent|''
name|'class'
name|'NoFloatingIpsDefined'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Zero floating ips exist."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoFloatingIpInterface
dedent|''
name|'class'
name|'NoFloatingIpInterface'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Interface %(interface)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CannotDisassociateAutoAssignedFloatingIP
dedent|''
name|'class'
name|'CannotDisassociateAutoAssignedFloatingIP'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Cannot disassociate auto assigned floating ip"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|KeypairNotFound
dedent|''
name|'class'
name|'KeypairNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Keypair %(name)s not found for user %(user_id)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ServiceNotFound
dedent|''
name|'class'
name|'ServiceNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Service %(service_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ServiceBinaryExists
dedent|''
name|'class'
name|'ServiceBinaryExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Service with host %(host)s binary %(binary)s exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ServiceTopicExists
dedent|''
name|'class'
name|'ServiceTopicExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Service with host %(host)s topic %(topic)s exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|HostNotFound
dedent|''
name|'class'
name|'HostNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Host %(host)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ComputeHostNotFound
dedent|''
name|'class'
name|'ComputeHostNotFound'
op|'('
name|'HostNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Compute host %(host)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|HostBinaryNotFound
dedent|''
name|'class'
name|'HostBinaryNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Could not find binary %(binary)s on host %(host)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidReservationExpiration
dedent|''
name|'class'
name|'InvalidReservationExpiration'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid reservation expiration %(expire)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidQuotaValue
dedent|''
name|'class'
name|'InvalidQuotaValue'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Change would make usage less than 0 for the following "'
nl|'\n'
string|'"resources: %(unders)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|QuotaNotFound
dedent|''
name|'class'
name|'QuotaNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Quota could not be found"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|QuotaExists
dedent|''
name|'class'
name|'QuotaExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Quota exists for project %(project_id)s, "'
nl|'\n'
string|'"resource %(resource)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|QuotaResourceUnknown
dedent|''
name|'class'
name|'QuotaResourceUnknown'
op|'('
name|'QuotaNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Unknown quota resources %(unknown)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ProjectUserQuotaNotFound
dedent|''
name|'class'
name|'ProjectUserQuotaNotFound'
op|'('
name|'QuotaNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Quota for user %(user_id)s in project %(project_id)s "'
nl|'\n'
string|'"could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ProjectQuotaNotFound
dedent|''
name|'class'
name|'ProjectQuotaNotFound'
op|'('
name|'QuotaNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Quota for project %(project_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|QuotaClassNotFound
dedent|''
name|'class'
name|'QuotaClassNotFound'
op|'('
name|'QuotaNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Quota class %(class_name)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|QuotaUsageNotFound
dedent|''
name|'class'
name|'QuotaUsageNotFound'
op|'('
name|'QuotaNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Quota usage for project %(project_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ReservationNotFound
dedent|''
name|'class'
name|'ReservationNotFound'
op|'('
name|'QuotaNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Quota reservation %(uuid)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|OverQuota
dedent|''
name|'class'
name|'OverQuota'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Quota exceeded for resources: %(overs)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupNotFound
dedent|''
name|'class'
name|'SecurityGroupNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Security group %(security_group_id)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupNotFoundForProject
dedent|''
name|'class'
name|'SecurityGroupNotFoundForProject'
op|'('
name|'SecurityGroupNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Security group %(security_group_id)s not found "'
nl|'\n'
string|'"for project %(project_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupNotFoundForRule
dedent|''
name|'class'
name|'SecurityGroupNotFoundForRule'
op|'('
name|'SecurityGroupNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Security group with rule %(rule_id)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupExists
dedent|''
name|'class'
name|'SecurityGroupExists'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Security group %(security_group_name)s already exists "'
nl|'\n'
string|'"for project %(project_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupExistsForInstance
dedent|''
name|'class'
name|'SecurityGroupExistsForInstance'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Security group %(security_group_id)s is already associated"'
nl|'\n'
string|'" with the instance %(instance_id)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupNotExistsForInstance
dedent|''
name|'class'
name|'SecurityGroupNotExistsForInstance'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Security group %(security_group_id)s is not associated with"'
nl|'\n'
string|'" the instance %(instance_id)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupDefaultRuleNotFound
dedent|''
name|'class'
name|'SecurityGroupDefaultRuleNotFound'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Security group default rule (%rule_id)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupCannotBeApplied
dedent|''
name|'class'
name|'SecurityGroupCannotBeApplied'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Network requires port_security_enabled and subnet associated"'
nl|'\n'
string|'" in order to apply security groups."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoUniqueMatch
dedent|''
name|'class'
name|'NoUniqueMatch'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"No Unique Match Found."'
op|')'
newline|'\n'
DECL|variable|code
name|'code'
op|'='
number|'409'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MigrationNotFound
dedent|''
name|'class'
name|'MigrationNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Migration %(migration_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MigrationNotFoundByStatus
dedent|''
name|'class'
name|'MigrationNotFoundByStatus'
op|'('
name|'MigrationNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Migration not found for instance %(instance_id)s "'
nl|'\n'
string|'"with status %(status)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsolePoolNotFound
dedent|''
name|'class'
name|'ConsolePoolNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Console pool %(pool_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsolePoolExists
dedent|''
name|'class'
name|'ConsolePoolExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Console pool with host %(host)s, console_type "'
nl|'\n'
string|'"%(console_type)s and compute_host %(compute_host)s "'
nl|'\n'
string|'"already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsolePoolNotFoundForHostType
dedent|''
name|'class'
name|'ConsolePoolNotFoundForHostType'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Console pool of type %(console_type)s "'
nl|'\n'
string|'"for compute host %(compute_host)s "'
nl|'\n'
string|'"on proxy host %(host)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsoleNotFound
dedent|''
name|'class'
name|'ConsoleNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Console %(console_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsoleNotFoundForInstance
dedent|''
name|'class'
name|'ConsoleNotFoundForInstance'
op|'('
name|'ConsoleNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Console for instance %(instance_uuid)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsoleNotFoundInPoolForInstance
dedent|''
name|'class'
name|'ConsoleNotFoundInPoolForInstance'
op|'('
name|'ConsoleNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Console for instance %(instance_uuid)s "'
nl|'\n'
string|'"in pool %(pool_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsoleTypeInvalid
dedent|''
name|'class'
name|'ConsoleTypeInvalid'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid console type %(console_type)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConsoleTypeUnavailable
dedent|''
name|'class'
name|'ConsoleTypeUnavailable'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|message
indent|'    '
name|'message'
op|'='
name|'_'
op|'('
string|'"Unavailable console type %(console_type)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeNotFound
dedent|''
name|'class'
name|'InstanceTypeNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance type %(instance_type_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeNotFoundByName
dedent|''
name|'class'
name|'InstanceTypeNotFoundByName'
op|'('
name|'InstanceTypeNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance type with name %(instance_type_name)s "'
nl|'\n'
string|'"could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FlavorNotFound
dedent|''
name|'class'
name|'FlavorNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Flavor %(flavor_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FlavorAccessNotFound
dedent|''
name|'class'
name|'FlavorAccessNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Flavor access not found for %(flavor_id)s / "'
nl|'\n'
string|'"%(project_id)s combination."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CellNotFound
dedent|''
name|'class'
name|'CellNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Cell %(cell_name)s doesn\'t exist."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CellExists
dedent|''
name|'class'
name|'CellExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Cell with name %(name)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CellRoutingInconsistency
dedent|''
name|'class'
name|'CellRoutingInconsistency'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Inconsistency in cell routing: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CellServiceAPIMethodNotFound
dedent|''
name|'class'
name|'CellServiceAPIMethodNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Service API method not found: %(detail)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CellTimeout
dedent|''
name|'class'
name|'CellTimeout'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Timeout waiting for response from cell"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CellMaxHopCountReached
dedent|''
name|'class'
name|'CellMaxHopCountReached'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Cell message has reached maximum hop count: %(hop_count)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoCellsAvailable
dedent|''
name|'class'
name|'NoCellsAvailable'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"No cells available matching scheduling criteria."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CellError
dedent|''
name|'class'
name|'CellError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Exception received during cell processing: %(exc_name)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CellsUpdateUnsupported
dedent|''
name|'class'
name|'CellsUpdateUnsupported'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Cannot update cells configuration file."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceUnknownCell
dedent|''
name|'class'
name|'InstanceUnknownCell'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Cell is not known for instance %(instance_uuid)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SchedulerHostFilterNotFound
dedent|''
name|'class'
name|'SchedulerHostFilterNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Scheduler Host Filter %(filter_name)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceMetadataNotFound
dedent|''
name|'class'
name|'InstanceMetadataNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_uuid)s has no metadata with "'
nl|'\n'
string|'"key %(metadata_key)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceSystemMetadataNotFound
dedent|''
name|'class'
name|'InstanceSystemMetadataNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_uuid)s has no system metadata with "'
nl|'\n'
string|'"key %(metadata_key)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeExtraSpecsNotFound
dedent|''
name|'class'
name|'InstanceTypeExtraSpecsNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance Type %(instance_type_id)s has no extra specs with "'
nl|'\n'
string|'"key %(extra_specs_key)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FileNotFound
dedent|''
name|'class'
name|'FileNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"File %(file_path)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoFilesFound
dedent|''
name|'class'
name|'NoFilesFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Zero files could be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SwitchNotFoundForNetworkAdapter
dedent|''
name|'class'
name|'SwitchNotFoundForNetworkAdapter'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Virtual switch associated with the "'
nl|'\n'
string|'"network adapter %(adapter)s not found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NetworkAdapterNotFound
dedent|''
name|'class'
name|'NetworkAdapterNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Network adapter %(adapter)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ClassNotFound
dedent|''
name|'class'
name|'ClassNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Class %(class_name)s could not be found: %(exception)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NotAllowed
dedent|''
name|'class'
name|'NotAllowed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Action not allowed."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ImageRotationNotAllowed
dedent|''
name|'class'
name|'ImageRotationNotAllowed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Rotation is not allowed for snapshots"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|RotationRequiredForBackup
dedent|''
name|'class'
name|'RotationRequiredForBackup'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Rotation param is required for backup image_type"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|KeyPairExists
dedent|''
name|'class'
name|'KeyPairExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Key pair \'%(key_name)s\' already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceExists
dedent|''
name|'class'
name|'InstanceExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(name)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeExists
dedent|''
name|'class'
name|'InstanceTypeExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance Type with name %(name)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeIdExists
dedent|''
name|'class'
name|'InstanceTypeIdExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance Type with ID %(flavor_id)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FlavorAccessExists
dedent|''
name|'class'
name|'FlavorAccessExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Flavor access already exists for flavor %(flavor_id)s "'
nl|'\n'
string|'"and project %(project_id)s combination."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidSharedStorage
dedent|''
name|'class'
name|'InvalidSharedStorage'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"%(path)s is not on shared storage: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidLocalStorage
dedent|''
name|'class'
name|'InvalidLocalStorage'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"%(path)s is not on local storage: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MigrationError
dedent|''
name|'class'
name|'MigrationError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Migration error"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MigrationPreCheckError
dedent|''
name|'class'
name|'MigrationPreCheckError'
op|'('
name|'MigrationError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Migration pre-check error"'
op|')'
op|'+'
string|'": %(reason)s"'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MalformedRequestBody
dedent|''
name|'class'
name|'MalformedRequestBody'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Malformed message body: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
comment|'# NOTE(johannes): NotFound should only be used when a 404 error is'
nl|'\n'
comment|'# appropriate to be returned'
nl|'\n'
DECL|class|ConfigNotFound
dedent|''
name|'class'
name|'ConfigNotFound'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Could not find config at %(path)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|PasteAppNotFound
dedent|''
name|'class'
name|'PasteAppNotFound'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Could not load paste app \'%(name)s\' from %(path)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CannotResizeToSameFlavor
dedent|''
name|'class'
name|'CannotResizeToSameFlavor'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"When resizing, instances must change flavor!"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ResizeError
dedent|''
name|'class'
name|'ResizeError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Resize error: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CannotResizeDisk
dedent|''
name|'class'
name|'CannotResizeDisk'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Server disk was unable to be resized because: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeMemoryTooSmall
dedent|''
name|'class'
name|'InstanceTypeMemoryTooSmall'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance type\'s memory is too small for requested image."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeDiskTooSmall
dedent|''
name|'class'
name|'InstanceTypeDiskTooSmall'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance type\'s disk is too small for requested image."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InsufficientFreeMemory
dedent|''
name|'class'
name|'InsufficientFreeMemory'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Insufficient free memory on compute node to start %(uuid)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NoValidHost
dedent|''
name|'class'
name|'NoValidHost'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"No valid host was found. %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|QuotaError
dedent|''
name|'class'
name|'QuotaError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Quota exceeded"'
op|')'
op|'+'
string|'": code=%(code)s"'
newline|'\n'
DECL|variable|code
name|'code'
op|'='
number|'413'
newline|'\n'
DECL|variable|headers
name|'headers'
op|'='
op|'{'
string|"'Retry-After'"
op|':'
number|'0'
op|'}'
newline|'\n'
DECL|variable|safe
name|'safe'
op|'='
name|'True'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|TooManyInstances
dedent|''
name|'class'
name|'TooManyInstances'
op|'('
name|'QuotaError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Quota exceeded for %(overs)s: Requested %(req)s,"'
nl|'\n'
string|'" but already used %(used)d of %(allowed)d %(resource)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FloatingIpLimitExceeded
dedent|''
name|'class'
name|'FloatingIpLimitExceeded'
op|'('
name|'QuotaError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Maximum number of floating ips exceeded"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FixedIpLimitExceeded
dedent|''
name|'class'
name|'FixedIpLimitExceeded'
op|'('
name|'QuotaError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Maximum number of fixed ips exceeded"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MetadataLimitExceeded
dedent|''
name|'class'
name|'MetadataLimitExceeded'
op|'('
name|'QuotaError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Maximum number of metadata items exceeds %(allowed)d"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|OnsetFileLimitExceeded
dedent|''
name|'class'
name|'OnsetFileLimitExceeded'
op|'('
name|'QuotaError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Personality file limit exceeded"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|OnsetFilePathLimitExceeded
dedent|''
name|'class'
name|'OnsetFilePathLimitExceeded'
op|'('
name|'QuotaError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Personality file path too long"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|OnsetFileContentLimitExceeded
dedent|''
name|'class'
name|'OnsetFileContentLimitExceeded'
op|'('
name|'QuotaError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Personality file content too long"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|KeypairLimitExceeded
dedent|''
name|'class'
name|'KeypairLimitExceeded'
op|'('
name|'QuotaError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Maximum number of key pairs exceeded"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|SecurityGroupLimitExceeded
dedent|''
name|'class'
name|'SecurityGroupLimitExceeded'
op|'('
name|'QuotaError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Maximum number of security groups or rules exceeded"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateError
dedent|''
name|'class'
name|'AggregateError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_id)s: action \'%(action)s\' "'
nl|'\n'
string|'"caused an error: %(reason)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateNotFound
dedent|''
name|'class'
name|'AggregateNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateNameExists
dedent|''
name|'class'
name|'AggregateNameExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_name)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateHostNotFound
dedent|''
name|'class'
name|'AggregateHostNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_id)s has no host %(host)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateMetadataNotFound
dedent|''
name|'class'
name|'AggregateMetadataNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_id)s has no metadata with "'
nl|'\n'
string|'"key %(metadata_key)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AggregateHostExists
dedent|''
name|'class'
name|'AggregateHostExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Aggregate %(aggregate_id)s already has host %(host)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeCreateFailed
dedent|''
name|'class'
name|'InstanceTypeCreateFailed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Unable to create instance type"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstancePasswordSetFailed
dedent|''
name|'class'
name|'InstancePasswordSetFailed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to set admin password on %(instance)s "'
nl|'\n'
string|'"because %(reason)s"'
op|')'
newline|'\n'
DECL|variable|safe
name|'safe'
op|'='
name|'True'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DuplicateVlan
dedent|''
name|'class'
name|'DuplicateVlan'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Detected existing vlan with id %(vlan)d"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CidrConflict
dedent|''
name|'class'
name|'CidrConflict'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"There was a conflict when trying to complete your request."'
op|')'
newline|'\n'
DECL|variable|code
name|'code'
op|'='
number|'409'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceNotFound
dedent|''
name|'class'
name|'InstanceNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceInfoCacheNotFound
dedent|''
name|'class'
name|'InstanceInfoCacheNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Info cache for instance %(instance_uuid)s could not be "'
nl|'\n'
string|'"found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NodeNotFound
dedent|''
name|'class'
name|'NodeNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Node %(node_id)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|NodeNotFoundByUUID
dedent|''
name|'class'
name|'NodeNotFoundByUUID'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Node with UUID %(node_uuid)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|MarkerNotFound
dedent|''
name|'class'
name|'MarkerNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Marker %(marker)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InvalidInstanceIDMalformed
dedent|''
name|'class'
name|'InvalidInstanceIDMalformed'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid id: %(val)s (expecting \\"i-...\\")."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CouldNotFetchImage
dedent|''
name|'class'
name|'CouldNotFetchImage'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Could not fetch image %(image_id)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CouldNotUploadImage
dedent|''
name|'class'
name|'CouldNotUploadImage'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Could not upload image %(image_id)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|TaskAlreadyRunning
dedent|''
name|'class'
name|'TaskAlreadyRunning'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Task %(task_name)s is already running on host %(host)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|TaskNotRunning
dedent|''
name|'class'
name|'TaskNotRunning'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Task %(task_name)s is not running on host %(host)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceIsLocked
dedent|''
name|'class'
name|'InstanceIsLocked'
op|'('
name|'InstanceInvalidState'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance %(instance_uuid)s is locked"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConfigDriveInvalidValue
dedent|''
name|'class'
name|'ConfigDriveInvalidValue'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid value for Config Drive option: %(option)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConfigDriveMountFailed
dedent|''
name|'class'
name|'ConfigDriveMountFailed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Could not mount vfat config drive. %(operation)s failed. "'
nl|'\n'
string|'"Error: %(error)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ConfigDriveUnknownFormat
dedent|''
name|'class'
name|'ConfigDriveUnknownFormat'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Unknown config drive format %(format)s. Select one of "'
nl|'\n'
string|'"iso9660 or vfat."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InterfaceAttachFailed
dedent|''
name|'class'
name|'InterfaceAttachFailed'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to attach network adapter device to %(instance)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InterfaceDetachFailed
dedent|''
name|'class'
name|'InterfaceDetachFailed'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Failed to detach network adapter device from  %(instance)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceUserDataTooLarge
dedent|''
name|'class'
name|'InstanceUserDataTooLarge'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"User data too large. User data must be no larger than "'
nl|'\n'
string|'"%(maxsize)s bytes once base64 encoded. Your data is "'
nl|'\n'
string|'"%(length)d bytes"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceUserDataMalformed
dedent|''
name|'class'
name|'InstanceUserDataMalformed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"User data needs to be valid base 64."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UnexpectedTaskStateError
dedent|''
name|'class'
name|'UnexpectedTaskStateError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"unexpected task state: expecting %(expected)s but "'
nl|'\n'
string|'"the actual state is %(actual)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceActionNotFound
dedent|''
name|'class'
name|'InstanceActionNotFound'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Action for request_id %(request_id)s on instance"'
nl|'\n'
string|'" %(instance_uuid)s not found"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceActionEventNotFound
dedent|''
name|'class'
name|'InstanceActionEventNotFound'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Event %(event)s not found for action id %(action_id)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UnexpectedVMStateError
dedent|''
name|'class'
name|'UnexpectedVMStateError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"unexpected VM state: expecting %(expected)s but "'
nl|'\n'
string|'"the actual state is %(actual)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CryptoCAFileNotFound
dedent|''
name|'class'
name|'CryptoCAFileNotFound'
op|'('
name|'FileNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The CA file for %(project)s could not be found"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CryptoCRLFileNotFound
dedent|''
name|'class'
name|'CryptoCRLFileNotFound'
op|'('
name|'FileNotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The CRL file for %(project)s could not be found"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceRecreateNotSupported
dedent|''
name|'class'
name|'InstanceRecreateNotSupported'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|"'Instance recreate is not implemented by this virt driver.'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ServiceGroupUnavailable
dedent|''
name|'class'
name|'ServiceGroupUnavailable'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"The service from servicegroup driver %(driver)s is "'
nl|'\n'
string|'"temporarily unavailable."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DBNotAllowed
dedent|''
name|'class'
name|'DBNotAllowed'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|"'%(binary)s attempted direct database access which is '"
nl|'\n'
string|"'not allowed by policy'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UnsupportedVirtType
dedent|''
name|'class'
name|'UnsupportedVirtType'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Virtualization type \'%(virt)s\' is not supported by "'
nl|'\n'
string|'"this compute driver"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UnsupportedHardware
dedent|''
name|'class'
name|'UnsupportedHardware'
op|'('
name|'Invalid'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Requested hardware \'%(model)s\' is not supported by "'
nl|'\n'
string|'"the \'%(virt)s\' virt driver"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|Base64Exception
dedent|''
name|'class'
name|'Base64Exception'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Invalid Base 64 data for file %(path)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|BuildAbortException
dedent|''
name|'class'
name|'BuildAbortException'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Build of instance %(instance_uuid)s aborted: %(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|RescheduledException
dedent|''
name|'class'
name|'RescheduledException'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Build of instance %(instance_uuid)s was re-scheduled: "'
nl|'\n'
string|'"%(reason)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ShadowTableExists
dedent|''
name|'class'
name|'ShadowTableExists'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Shadow table with name %(name)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceFaultRollback
dedent|''
name|'class'
name|'InstanceFaultRollback'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'inner_exception'
op|'='
name|'None'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'message'
op|'='
name|'_'
op|'('
string|'"Instance rollback performed due to: %s"'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'inner_exception'
op|'='
name|'inner_exception'
newline|'\n'
name|'super'
op|'('
name|'InstanceFaultRollback'
op|','
name|'self'
op|')'
op|'.'
name|'__init__'
op|'('
name|'message'
op|'%'
name|'inner_exception'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UnsupportedObjectError
dedent|''
dedent|''
name|'class'
name|'UnsupportedObjectError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|"'Unsupported object type %(objtype)s'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|OrphanedObjectError
dedent|''
name|'class'
name|'OrphanedObjectError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|"'Cannot call %(method)s on orphaned %(objtype)s object'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|IncompatibleObjectVersion
dedent|''
name|'class'
name|'IncompatibleObjectVersion'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|"'Version %(objver)s of %(objname)s is not supported'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|CoreAPIMissing
dedent|''
name|'class'
name|'CoreAPIMissing'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Core API extensions are missing: %(missing_apis)s"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AgentError
dedent|''
name|'class'
name|'AgentError'
op|'('
name|'NovaException'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|"'Error during following call to agent: %(method)s'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AgentTimeout
dedent|''
name|'class'
name|'AgentTimeout'
op|'('
name|'AgentError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|"'Unable to contact guest agent. '"
nl|'\n'
string|"'The following call timed out: %(method)s'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|AgentNotImplemented
dedent|''
name|'class'
name|'AgentNotImplemented'
op|'('
name|'AgentError'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|"'Agent does not support the call: %(method)s'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceGroupNotFound
dedent|''
name|'class'
name|'InstanceGroupNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance group %(group_uuid)s could not be found."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceGroupIdExists
dedent|''
name|'class'
name|'InstanceGroupIdExists'
op|'('
name|'Duplicate'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance group %(group_uuid)s already exists."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceGroupMetadataNotFound
dedent|''
name|'class'
name|'InstanceGroupMetadataNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance group %(group_uuid)s has no metadata with "'
nl|'\n'
string|'"key %(metadata_key)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceGroupMemberNotFound
dedent|''
name|'class'
name|'InstanceGroupMemberNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance group %(group_uuid)s has no member with "'
nl|'\n'
string|'"id %(instance_id)s."'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceGroupPolicyNotFound
dedent|''
name|'class'
name|'InstanceGroupPolicyNotFound'
op|'('
name|'NotFound'
op|')'
op|':'
newline|'\n'
DECL|variable|msg_fmt
indent|'    '
name|'msg_fmt'
op|'='
name|'_'
op|'('
string|'"Instance group %(group_uuid)s has no policy %(policy)s."'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
