begin_unit
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# Copyright 2011 Justin Santa Barbara'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Utilities and helper functions that won\'t produce circular imports."""'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_wrapped_function
name|'def'
name|'get_wrapped_function'
op|'('
name|'function'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Get the method at the bottom of a stack of decorators."""'
newline|'\n'
name|'if'
name|'not'
name|'hasattr'
op|'('
name|'function'
op|','
string|"'__closure__'"
op|')'
name|'or'
name|'not'
name|'function'
op|'.'
name|'__closure__'
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'function'
newline|'\n'
nl|'\n'
DECL|function|_get_wrapped_function
dedent|''
name|'def'
name|'_get_wrapped_function'
op|'('
name|'function'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'not'
name|'hasattr'
op|'('
name|'function'
op|','
string|"'__closure__'"
op|')'
name|'or'
name|'not'
name|'function'
op|'.'
name|'__closure__'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'None'
newline|'\n'
nl|'\n'
dedent|''
name|'for'
name|'closure'
name|'in'
name|'function'
op|'.'
name|'__closure__'
op|':'
newline|'\n'
indent|'            '
name|'func'
op|'='
name|'closure'
op|'.'
name|'cell_contents'
newline|'\n'
nl|'\n'
name|'deeper_func'
op|'='
name|'_get_wrapped_function'
op|'('
name|'func'
op|')'
newline|'\n'
name|'if'
name|'deeper_func'
op|':'
newline|'\n'
indent|'                '
name|'return'
name|'deeper_func'
newline|'\n'
dedent|''
name|'elif'
name|'hasattr'
op|'('
name|'closure'
op|'.'
name|'cell_contents'
op|','
string|"'__call__'"
op|')'
op|':'
newline|'\n'
indent|'                '
name|'return'
name|'closure'
op|'.'
name|'cell_contents'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
dedent|''
name|'return'
name|'_get_wrapped_function'
op|'('
name|'function'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
