begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2013 IBM Corp'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nUnit constants\n"""'
newline|'\n'
nl|'\n'
comment|'#Byte unit constant.'
nl|'\n'
DECL|variable|Ki
name|'Ki'
op|'='
number|'1024'
newline|'\n'
DECL|variable|Mi
name|'Mi'
op|'='
number|'1024'
op|'**'
number|'2'
newline|'\n'
DECL|variable|Gi
name|'Gi'
op|'='
number|'1024'
op|'**'
number|'3'
newline|'\n'
DECL|variable|Ti
name|'Ti'
op|'='
number|'1024'
op|'**'
number|'4'
newline|'\n'
DECL|variable|Pi
name|'Pi'
op|'='
number|'1024'
op|'**'
number|'5'
newline|'\n'
DECL|variable|Ei
name|'Ei'
op|'='
number|'1024'
op|'**'
number|'6'
newline|'\n'
DECL|variable|Zi
name|'Zi'
op|'='
number|'1024'
op|'**'
number|'7'
newline|'\n'
DECL|variable|Yi
name|'Yi'
op|'='
number|'1024'
op|'**'
number|'8'
newline|'\n'
endmarker|''
end_unit
