begin_unit
comment|'# Copyright (c) 2011-2012 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nPluggable Weighing support\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'loadables'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|WeighedObject
name|'class'
name|'WeighedObject'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Object with weight information."""'
newline|'\n'
DECL|member|__init__
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'obj'
op|','
name|'weight'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'obj'
op|'='
name|'obj'
newline|'\n'
name|'self'
op|'.'
name|'weight'
op|'='
name|'weight'
newline|'\n'
nl|'\n'
DECL|member|__repr__
dedent|''
name|'def'
name|'__repr__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
string|'"<WeighedObject \'%s\': %s>"'
op|'%'
op|'('
name|'self'
op|'.'
name|'obj'
op|','
name|'self'
op|'.'
name|'weight'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|BaseWeigher
dedent|''
dedent|''
name|'class'
name|'BaseWeigher'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Base class for pluggable weighers."""'
newline|'\n'
DECL|member|_weight_multiplier
name|'def'
name|'_weight_multiplier'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""How weighted this weigher should be.  Normally this would\n        be overridden in a subclass based on a config value.\n        """'
newline|'\n'
name|'return'
number|'1.0'
newline|'\n'
nl|'\n'
DECL|member|_weigh_object
dedent|''
name|'def'
name|'_weigh_object'
op|'('
name|'self'
op|','
name|'obj'
op|','
name|'weight_properties'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Override in a subclass to specify a weight for a specific\n        object.\n        """'
newline|'\n'
name|'return'
number|'0.0'
newline|'\n'
nl|'\n'
DECL|member|weigh_objects
dedent|''
name|'def'
name|'weigh_objects'
op|'('
name|'self'
op|','
name|'weighed_obj_list'
op|','
name|'weight_properties'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Weigh multiple objects.  Override in a subclass if you need\n        need access to all objects in order to manipulate weights.\n        """'
newline|'\n'
name|'for'
name|'obj'
name|'in'
name|'weighed_obj_list'
op|':'
newline|'\n'
indent|'            '
name|'obj'
op|'.'
name|'weight'
op|'+='
op|'('
name|'self'
op|'.'
name|'_weight_multiplier'
op|'('
op|')'
op|'*'
nl|'\n'
name|'self'
op|'.'
name|'_weigh_object'
op|'('
name|'obj'
op|'.'
name|'obj'
op|','
name|'weight_properties'
op|')'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|BaseWeightHandler
dedent|''
dedent|''
dedent|''
name|'class'
name|'BaseWeightHandler'
op|'('
name|'loadables'
op|'.'
name|'BaseLoader'
op|')'
op|':'
newline|'\n'
DECL|variable|object_class
indent|'    '
name|'object_class'
op|'='
name|'WeighedObject'
newline|'\n'
nl|'\n'
DECL|member|get_weighed_objects
name|'def'
name|'get_weighed_objects'
op|'('
name|'self'
op|','
name|'weigher_classes'
op|','
name|'obj_list'
op|','
nl|'\n'
name|'weighing_properties'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return a sorted (highest score first) list of WeighedObjects."""'
newline|'\n'
nl|'\n'
name|'if'
name|'not'
name|'obj_list'
op|':'
newline|'\n'
indent|'            '
name|'return'
op|'['
op|']'
newline|'\n'
nl|'\n'
dedent|''
name|'weighed_objs'
op|'='
op|'['
name|'self'
op|'.'
name|'object_class'
op|'('
name|'obj'
op|','
number|'0.0'
op|')'
name|'for'
name|'obj'
name|'in'
name|'obj_list'
op|']'
newline|'\n'
name|'for'
name|'weigher_cls'
name|'in'
name|'weigher_classes'
op|':'
newline|'\n'
indent|'            '
name|'weigher'
op|'='
name|'weigher_cls'
op|'('
op|')'
newline|'\n'
name|'weigher'
op|'.'
name|'weigh_objects'
op|'('
name|'weighed_objs'
op|','
name|'weighing_properties'
op|')'
newline|'\n'
nl|'\n'
dedent|''
name|'return'
name|'sorted'
op|'('
name|'weighed_objs'
op|','
name|'key'
op|'='
name|'lambda'
name|'x'
op|':'
name|'x'
op|'.'
name|'weight'
op|','
name|'reverse'
op|'='
name|'True'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
