begin_unit
comment|'# Copyright (c) 2012 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nWebsocket proxy that is compatible with OpenStack Nova\nnoVNC consoles. Leverages websockify.py by Joel Martin\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'sys'
newline|'\n'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'cmd'
name|'import'
name|'baseproxy'
newline|'\n'
name|'import'
name|'nova'
op|'.'
name|'conf'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'conf'
name|'import'
name|'vnc'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'config'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|CONF
name|'CONF'
op|'='
name|'nova'
op|'.'
name|'conf'
op|'.'
name|'CONF'
newline|'\n'
name|'vnc'
op|'.'
name|'register_cli_opts'
op|'('
name|'CONF'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|main
name|'def'
name|'main'
op|'('
op|')'
op|':'
newline|'\n'
comment|'# set default web flag option'
nl|'\n'
indent|'    '
name|'CONF'
op|'.'
name|'set_default'
op|'('
string|"'web'"
op|','
string|"'/usr/share/novnc'"
op|')'
newline|'\n'
name|'config'
op|'.'
name|'parse_args'
op|'('
name|'sys'
op|'.'
name|'argv'
op|')'
newline|'\n'
nl|'\n'
name|'baseproxy'
op|'.'
name|'proxy'
op|'('
nl|'\n'
name|'host'
op|'='
name|'CONF'
op|'.'
name|'vnc'
op|'.'
name|'novncproxy_host'
op|','
nl|'\n'
name|'port'
op|'='
name|'CONF'
op|'.'
name|'vnc'
op|'.'
name|'novncproxy_port'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
