begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
comment|'# Copyright (c) 2013 The Johns Hopkins University/Applied Physics Laboratory'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nKey manager API\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'abc'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|KeyManager
name|'class'
name|'KeyManager'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Base Key Manager Interface\n\n    A Key Manager is responsible for managing encryption keys for volumes. A\n    Key Manager is responsible for creating, reading, and deleting keys.\n    """'
newline|'\n'
nl|'\n'
DECL|variable|__metaclass__
name|'__metaclass__'
op|'='
name|'abc'
op|'.'
name|'ABCMeta'
newline|'\n'
nl|'\n'
op|'@'
name|'abc'
op|'.'
name|'abstractmethod'
newline|'\n'
DECL|member|create_key
name|'def'
name|'create_key'
op|'('
name|'self'
op|','
name|'ctxt'
op|','
name|'algorithm'
op|'='
string|"'AES'"
op|','
name|'length'
op|'='
number|'256'
op|','
name|'expiration'
op|'='
name|'None'
op|','
nl|'\n'
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Creates a key.\n\n        This method creates a key and returns the key\'s UUID. If the specified\n        context does not permit the creation of keys, then a NotAuthorized\n        exception should be raised.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'abc'
op|'.'
name|'abstractmethod'
newline|'\n'
DECL|member|store_key
name|'def'
name|'store_key'
op|'('
name|'self'
op|','
name|'ctxt'
op|','
name|'key'
op|','
name|'expiration'
op|'='
name|'None'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Stores (i.e., registers) a key with the key manager.\n\n        This method stores the specified key and returns its UUID that\n        identifies it within the key manager. If the specified context does\n        not permit the creation of keys, then a NotAuthorized exception should\n        be raised.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'abc'
op|'.'
name|'abstractmethod'
newline|'\n'
DECL|member|copy_key
name|'def'
name|'copy_key'
op|'('
name|'self'
op|','
name|'ctxt'
op|','
name|'key_id'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Copies (i.e., clones) a key stored by the key manager.\n\n        This method copies the specified key and returns the copy\'s UUID. If\n        the specified context does not permit copying keys, then a\n        NotAuthorized error should be raised.\n\n        Implementation note: This method should behave identically to\n            store_key(context, get_key(context, <encryption key UUID>))\n        although it is preferable to perform this operation within the key\n        manager to avoid unnecessary handling of the key material.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'abc'
op|'.'
name|'abstractmethod'
newline|'\n'
DECL|member|get_key
name|'def'
name|'get_key'
op|'('
name|'self'
op|','
name|'ctxt'
op|','
name|'key_id'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Retrieves the specified key.\n\n        Implementations should verify that the caller has permissions to\n        retrieve the key by checking the context object passed in as ctxt. If\n        the user lacks permission then a NotAuthorized exception is raised.\n\n        If the specified key does not exist, then a KeyError should be raised.\n        Implementations should preclude users from discerning the UUIDs of\n        keys that belong to other users by repeatedly calling this method.\n        That is, keys that belong to other users should be considered "non-\n        existent" and completely invisible.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'abc'
op|'.'
name|'abstractmethod'
newline|'\n'
DECL|member|delete_key
name|'def'
name|'delete_key'
op|'('
name|'self'
op|','
name|'ctxt'
op|','
name|'key_id'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Deletes the specified key.\n\n        Implementations should verify that the caller has permission to delete\n        the key by checking the context object (ctxt). A NotAuthorized\n        exception should be raised if the caller lacks permission.\n\n        If the specified key does not exist, then a KeyError should be raised.\n        Implementations should preclude users from discerning the UUIDs of\n        keys that belong to other users by repeatedly calling this method.\n        That is, keys that belong to other users should be considered "non-\n        existent" and completely invisible.\n        """'
newline|'\n'
name|'pass'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
