begin_unit
comment|'# Copyright 2012 Nebula, Inc.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'webob'
name|'import'
name|'exc'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'context'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'db'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|MAX_SIZE
name|'MAX_SIZE'
op|'='
number|'256'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|handle_password
name|'def'
name|'handle_password'
op|'('
name|'req'
op|','
name|'meta_data'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'ctxt'
op|'='
name|'context'
op|'.'
name|'get_admin_context'
op|'('
op|')'
newline|'\n'
name|'password'
op|'='
name|'meta_data'
op|'.'
name|'password'
newline|'\n'
name|'if'
name|'req'
op|'.'
name|'method'
op|'=='
string|"'GET'"
op|':'
newline|'\n'
indent|'        '
name|'return'
name|'meta_data'
op|'.'
name|'password'
newline|'\n'
dedent|''
name|'elif'
name|'req'
op|'.'
name|'method'
op|'=='
string|"'POST'"
op|':'
newline|'\n'
comment|'# NOTE(vish): The conflict will only happen once the metadata cache'
nl|'\n'
comment|"#             updates, but it isn't a huge issue if it can be set for"
nl|'\n'
comment|'#             a short window.'
nl|'\n'
indent|'        '
name|'if'
name|'meta_data'
op|'.'
name|'password'
op|':'
newline|'\n'
indent|'            '
name|'raise'
name|'exc'
op|'.'
name|'HTTPConflict'
op|'('
op|')'
newline|'\n'
dedent|''
name|'if'
op|'('
name|'req'
op|'.'
name|'content_length'
op|'>'
name|'MAX_SIZE'
name|'or'
name|'len'
op|'('
name|'req'
op|'.'
name|'body'
op|')'
op|'>'
name|'MAX_SIZE'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'msg'
op|'='
name|'_'
op|'('
string|'"Request is too large."'
op|')'
newline|'\n'
name|'raise'
name|'exc'
op|'.'
name|'HTTPBadRequest'
op|'('
name|'explanation'
op|'='
name|'msg'
op|')'
newline|'\n'
dedent|''
name|'db'
op|'.'
name|'instance_system_metadata_update'
op|'('
name|'ctxt'
op|','
nl|'\n'
name|'meta_data'
op|'.'
name|'uuid'
op|','
nl|'\n'
op|'{'
string|"'password'"
op|':'
name|'req'
op|'.'
name|'body'
op|'}'
op|','
nl|'\n'
name|'False'
op|')'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'        '
name|'raise'
name|'exc'
op|'.'
name|'HTTPBadRequest'
op|'('
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
