begin_unit
comment|'# Copyright [2010] [Anso Labs, LLC]'
nl|'\n'
comment|'# '
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License");'
nl|'\n'
comment|'#    you may not use this file except in compliance with the License.'
nl|'\n'
comment|'#    You may obtain a copy of the License at'
nl|'\n'
comment|'# '
nl|'\n'
comment|'#        http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'# '
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS,'
nl|'\n'
comment|'#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
nl|'\n'
comment|'#    See the License for the specific language governing permissions and'
nl|'\n'
comment|'#    limitations under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'unittest'
newline|'\n'
nl|'\n'
name|'import'
name|'boto'
newline|'\n'
name|'from'
name|'boto'
op|'.'
name|'ec2'
op|'.'
name|'regioninfo'
name|'import'
name|'RegionInfo'
newline|'\n'
nl|'\n'
DECL|variable|ACCESS_KEY
name|'ACCESS_KEY'
op|'='
string|"'fake'"
newline|'\n'
DECL|variable|SECRET_KEY
name|'SECRET_KEY'
op|'='
string|"'fake'"
newline|'\n'
DECL|variable|CLC_IP
name|'CLC_IP'
op|'='
string|"'127.0.0.1'"
newline|'\n'
DECL|variable|CLC_PORT
name|'CLC_PORT'
op|'='
number|'8773'
newline|'\n'
DECL|variable|REGION
name|'REGION'
op|'='
string|"'test'"
newline|'\n'
nl|'\n'
DECL|function|get_connection
name|'def'
name|'get_connection'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'boto'
op|'.'
name|'connect_ec2'
op|'('
nl|'\n'
name|'aws_access_key_id'
op|'='
name|'ACCESS_KEY'
op|','
nl|'\n'
name|'aws_secret_access_key'
op|'='
name|'SECRET_KEY'
op|','
nl|'\n'
name|'is_secure'
op|'='
name|'False'
op|','
nl|'\n'
name|'region'
op|'='
name|'RegionInfo'
op|'('
name|'None'
op|','
name|'REGION'
op|','
name|'CLC_IP'
op|')'
op|','
nl|'\n'
name|'port'
op|'='
name|'CLC_PORT'
op|','
nl|'\n'
name|'path'
op|'='
string|"'/services/Cloud'"
op|','
nl|'\n'
name|'debug'
op|'='
number|'99'
nl|'\n'
op|')'
newline|'\n'
nl|'\n'
DECL|class|APIIntegrationTests
dedent|''
name|'class'
name|'APIIntegrationTests'
op|'('
name|'unittest'
op|'.'
name|'TestCase'
op|')'
op|':'
newline|'\n'
DECL|member|test_001_get_all_images
indent|'    '
name|'def'
name|'test_001_get_all_images'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'conn'
op|'='
name|'get_connection'
op|'('
op|')'
newline|'\n'
name|'res'
op|'='
name|'conn'
op|'.'
name|'get_all_images'
op|'('
op|')'
newline|'\n'
name|'print'
name|'res'
newline|'\n'
nl|'\n'
nl|'\n'
dedent|''
dedent|''
name|'if'
name|'__name__'
op|'=='
string|"'__main__'"
op|':'
newline|'\n'
indent|'    '
name|'unittest'
op|'.'
name|'main'
op|'('
op|')'
newline|'\n'
nl|'\n'
comment|'#print conn.get_all_key_pairs()'
nl|'\n'
comment|'#print conn.create_key_pair'
nl|'\n'
comment|"#print conn.create_security_group('name', 'description')"
nl|'\n'
nl|'\n'
dedent|''
endmarker|''
end_unit
