begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2011 Rackspace'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'# not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'# a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#      http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'# License for the specific language governing permissions and limitations'
nl|'\n'
comment|'# under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'flags'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'log'
name|'as'
name|'logging'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'tests'
op|'.'
name|'network'
name|'import'
name|'base'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|FLAGS
name|'FLAGS'
op|'='
name|'flags'
op|'.'
name|'FLAGS'
newline|'\n'
DECL|variable|LOG
name|'LOG'
op|'='
name|'logging'
op|'.'
name|'getLogger'
op|'('
string|"'nova.tests.network'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FlatNetworkTestCase
name|'class'
name|'FlatNetworkTestCase'
op|'('
name|'base'
op|'.'
name|'NetworkTestCase'
op|','
name|'base'
op|'.'
name|'TestFuncs'
op|')'
op|':'
newline|'\n'
DECL|variable|network_manager
indent|'    '
name|'network_manager'
op|'='
string|"'nova.network.manager.FlatManager'"
newline|'\n'
nl|'\n'
nl|'\n'
comment|'#class FlatDHCPNetworkTestCase(base.NetworkTestCase, base.TestFuncs):'
nl|'\n'
comment|"#    network_manager = 'nova.network.manager.FlatDHCPManager'"
nl|'\n'
nl|'\n'
nl|'\n'
DECL|class|VlanNetworkTestCase
dedent|''
name|'class'
name|'VlanNetworkTestCase'
op|'('
name|'base'
op|'.'
name|'NetworkTestCase'
op|','
name|'base'
op|'.'
name|'TestFuncs'
op|')'
op|':'
newline|'\n'
DECL|variable|network_manager
indent|'    '
name|'network_manager'
op|'='
string|"'nova.network.manager.VlanManager'"
newline|'\n'
dedent|''
endmarker|''
end_unit
