begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (C) 2013, Red Hat, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nUnit Tests for nova.manager\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'manager'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'test'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ManagerTestCase
name|'class'
name|'ManagerTestCase'
op|'('
name|'test'
op|'.'
name|'TestCase'
op|')'
op|':'
newline|'\n'
DECL|member|test_additional_apis_for_dispatcher
indent|'    '
name|'def'
name|'test_additional_apis_for_dispatcher'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
DECL|class|MyAPI
indent|'        '
name|'class'
name|'MyAPI'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'pass'
newline|'\n'
nl|'\n'
dedent|''
name|'m'
op|'='
name|'manager'
op|'.'
name|'Manager'
op|'('
op|')'
newline|'\n'
name|'api'
op|'='
name|'MyAPI'
op|'('
op|')'
newline|'\n'
name|'dispatch'
op|'='
name|'m'
op|'.'
name|'create_rpc_dispatcher'
op|'('
name|'additional_apis'
op|'='
op|'['
name|'api'
op|']'
op|')'
newline|'\n'
nl|'\n'
name|'self'
op|'.'
name|'assertEqual'
op|'('
name|'len'
op|'('
name|'dispatch'
op|'.'
name|'callbacks'
op|')'
op|','
number|'3'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'assertTrue'
op|'('
name|'api'
name|'in'
name|'dispatch'
op|'.'
name|'callbacks'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
