begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'test'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ExampleSkipTestCase
name|'class'
name|'ExampleSkipTestCase'
op|'('
name|'test'
op|'.'
name|'TestCase'
op|')'
op|':'
newline|'\n'
DECL|variable|test_counter
indent|'    '
name|'test_counter'
op|'='
number|'0'
newline|'\n'
nl|'\n'
op|'@'
name|'test'
op|'.'
name|'skip_test'
op|'('
string|'"Example usage of @test.skip_test()"'
op|')'
newline|'\n'
DECL|member|test_skip_test_example
name|'def'
name|'test_skip_test_example'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'fail'
op|'('
string|'"skip_test failed to work properly."'
op|')'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'test'
op|'.'
name|'skip_if'
op|'('
name|'True'
op|','
string|'"Example usage of @test.skip_if()"'
op|')'
newline|'\n'
DECL|member|test_skip_if_example
name|'def'
name|'test_skip_if_example'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'fail'
op|'('
string|'"skip_if failed to work properly."'
op|')'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'test'
op|'.'
name|'skip_unless'
op|'('
name|'False'
op|','
string|'"Example usage of @test.skip_unless()"'
op|')'
newline|'\n'
DECL|member|test_skip_unless_example
name|'def'
name|'test_skip_unless_example'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'fail'
op|'('
string|'"skip_unless failed to work properly."'
op|')'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'test'
op|'.'
name|'skip_if'
op|'('
name|'False'
op|','
string|'"This test case should never be skipped."'
op|')'
newline|'\n'
DECL|member|test_001_increase_test_counter
name|'def'
name|'test_001_increase_test_counter'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'ExampleSkipTestCase'
op|'.'
name|'test_counter'
op|'+='
number|'1'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'test'
op|'.'
name|'skip_unless'
op|'('
name|'True'
op|','
string|'"This test case should never be skipped."'
op|')'
newline|'\n'
DECL|member|test_002_increase_test_counter
name|'def'
name|'test_002_increase_test_counter'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'ExampleSkipTestCase'
op|'.'
name|'test_counter'
op|'+='
number|'1'
newline|'\n'
nl|'\n'
DECL|member|test_003_verify_test_counter
dedent|''
name|'def'
name|'test_003_verify_test_counter'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'assertEquals'
op|'('
name|'ExampleSkipTestCase'
op|'.'
name|'test_counter'
op|','
number|'2'
op|','
nl|'\n'
string|'"Tests were not skipped appropriately"'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
