begin_unit
comment|'# Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'# not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'# a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#      http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'# License for the specific language governing permissions and limitations'
nl|'\n'
comment|'# under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'sys'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|UUIDSentinels
name|'class'
name|'UUIDSentinels'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'from'
name|'oslo_utils'
name|'import'
name|'uuidutils'
newline|'\n'
name|'self'
op|'.'
name|'_uuid_module'
op|'='
name|'uuidutils'
newline|'\n'
name|'self'
op|'.'
name|'_sentinels'
op|'='
op|'{'
op|'}'
newline|'\n'
nl|'\n'
DECL|member|__getattr__
dedent|''
name|'def'
name|'__getattr__'
op|'('
name|'self'
op|','
name|'name'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'name'
op|'.'
name|'startswith'
op|'('
string|"'_'"
op|')'
op|':'
newline|'\n'
indent|'            '
name|'raise'
name|'ValueError'
op|'('
string|"'Sentinels must not start with _'"
op|')'
newline|'\n'
dedent|''
name|'if'
name|'name'
name|'not'
name|'in'
name|'self'
op|'.'
name|'_sentinels'
op|':'
newline|'\n'
indent|'            '
name|'self'
op|'.'
name|'_sentinels'
op|'['
name|'name'
op|']'
op|'='
name|'str'
op|'('
name|'self'
op|'.'
name|'_uuid_module'
op|'.'
name|'generate_uuid'
op|'('
op|')'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'self'
op|'.'
name|'_sentinels'
op|'['
name|'name'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
dedent|''
dedent|''
name|'sys'
op|'.'
name|'modules'
op|'['
name|'__name__'
op|']'
op|'='
name|'UUIDSentinels'
op|'('
op|')'
newline|'\n'
endmarker|''
end_unit
