begin_unit
comment|'# Copyright 2011 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
string|'"""Example Module for testing utils.monkey_patch()."""'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|CALLED_FUNCTION
name|'CALLED_FUNCTION'
op|'='
op|'['
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|example_decorator
name|'def'
name|'example_decorator'
op|'('
name|'name'
op|','
name|'function'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""decorator for notify which is used from utils.monkey_patch()\n\n        :param name: name of the function\n        :param function: - object of the function\n        :returns: function -- decorated function\n    """'
newline|'\n'
DECL|function|wrapped_func
name|'def'
name|'wrapped_func'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwarg'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'CALLED_FUNCTION'
op|'.'
name|'append'
op|'('
name|'name'
op|')'
newline|'\n'
name|'return'
name|'function'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwarg'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'wrapped_func'
newline|'\n'
dedent|''
endmarker|''
end_unit
