begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2011 Citrix Systems, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'StringIO'
newline|'\n'
nl|'\n'
name|'import'
name|'glance'
op|'.'
name|'client'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|stubout_glance_client
name|'def'
name|'stubout_glance_client'
op|'('
name|'stubs'
op|','
name|'cls'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Stubs out glance.client.Client"""'
newline|'\n'
name|'stubs'
op|'.'
name|'Set'
op|'('
name|'glance'
op|'.'
name|'client'
op|','
string|"'Client'"
op|','
nl|'\n'
name|'lambda'
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|':'
name|'cls'
op|'('
op|'*'
name|'args'
op|','
op|'**'
name|'kwargs'
op|')'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|FakeGlance
dedent|''
name|'class'
name|'FakeGlance'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
DECL|member|__init__
indent|'    '
name|'def'
name|'__init__'
op|'('
name|'self'
op|','
name|'host'
op|','
name|'port'
op|'='
name|'None'
op|','
name|'use_ssl'
op|'='
name|'False'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'pass'
newline|'\n'
nl|'\n'
DECL|member|get_image
dedent|''
name|'def'
name|'get_image'
op|'('
name|'self'
op|','
name|'image'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'meta'
op|'='
op|'{'
nl|'\n'
string|"'size'"
op|':'
number|'0'
op|','
nl|'\n'
op|'}'
newline|'\n'
name|'image_file'
op|'='
name|'StringIO'
op|'.'
name|'StringIO'
op|'('
string|"''"
op|')'
newline|'\n'
name|'return'
name|'meta'
op|','
name|'image_file'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
