begin_unit
comment|'# Copyright 2013 Intel Corporation.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
comment|'# @author: Shane Wang, Intel Corporation.'
nl|'\n'
nl|'\n'
string|'"""\nCPU monitor to retrieve CPU information\n"""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'compute'
name|'import'
name|'monitors'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|_CPUMonitorBase
name|'class'
name|'_CPUMonitorBase'
op|'('
name|'monitors'
op|'.'
name|'ResourceMonitorBase'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""CPU monitor base."""'
newline|'\n'
nl|'\n'
DECL|member|_get_cpu_frequency
name|'def'
name|'_get_cpu_frequency'
op|'('
name|'self'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return CPU current frequency and its timestamp."""'
newline|'\n'
name|'return'
name|'None'
op|','
name|'None'
newline|'\n'
nl|'\n'
DECL|member|_get_cpu_user_time
dedent|''
name|'def'
name|'_get_cpu_user_time'
op|'('
name|'self'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return CPU user mode time and its timestamp."""'
newline|'\n'
name|'return'
name|'None'
op|','
name|'None'
newline|'\n'
nl|'\n'
DECL|member|_get_cpu_kernel_time
dedent|''
name|'def'
name|'_get_cpu_kernel_time'
op|'('
name|'self'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return CPU kernel time and its timestamp."""'
newline|'\n'
name|'return'
name|'None'
op|','
name|'None'
newline|'\n'
nl|'\n'
DECL|member|_get_cpu_idle_time
dedent|''
name|'def'
name|'_get_cpu_idle_time'
op|'('
name|'self'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return CPU idle time and its timestamp."""'
newline|'\n'
name|'return'
name|'None'
op|','
name|'None'
newline|'\n'
nl|'\n'
DECL|member|_get_cpu_iowait_time
dedent|''
name|'def'
name|'_get_cpu_iowait_time'
op|'('
name|'self'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return CPU I/O wait time and its timestamp."""'
newline|'\n'
name|'return'
name|'None'
op|','
name|'None'
newline|'\n'
nl|'\n'
DECL|member|_get_cpu_user_percent
dedent|''
name|'def'
name|'_get_cpu_user_percent'
op|'('
name|'self'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return CPU user mode percentage and its timestamp."""'
newline|'\n'
name|'return'
name|'None'
op|','
name|'None'
newline|'\n'
nl|'\n'
DECL|member|_get_cpu_kernel_percent
dedent|''
name|'def'
name|'_get_cpu_kernel_percent'
op|'('
name|'self'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return CPU kernel percentage and its timestamp."""'
newline|'\n'
name|'return'
name|'None'
op|','
name|'None'
newline|'\n'
nl|'\n'
DECL|member|_get_cpu_idle_percent
dedent|''
name|'def'
name|'_get_cpu_idle_percent'
op|'('
name|'self'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return CPU idle percentage and its timestamp."""'
newline|'\n'
name|'return'
name|'None'
op|','
name|'None'
newline|'\n'
nl|'\n'
DECL|member|_get_cpu_iowait_percent
dedent|''
name|'def'
name|'_get_cpu_iowait_percent'
op|'('
name|'self'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return CPU I/O wait percentage and its timestamp."""'
newline|'\n'
name|'return'
name|'None'
op|','
name|'None'
newline|'\n'
nl|'\n'
DECL|member|_get_cpu_percent
dedent|''
name|'def'
name|'_get_cpu_percent'
op|'('
name|'self'
op|','
op|'**'
name|'kwargs'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return generic CPU utilization and its timestamp."""'
newline|'\n'
name|'return'
name|'None'
op|','
name|'None'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
