begin_unit
comment|'# Copyright (C) 2013 eNovance SAS <licensing@enovance.com>'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Author: Cyril Roelandt <cyril.roelandt@enovance.com>'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'# not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'# a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#      http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'# License for the specific language governing permissions and limitations'
nl|'\n'
comment|'# under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'test'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'virt'
op|'.'
name|'libvirt'
name|'import'
name|'designer'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|DesignerTestCase
name|'class'
name|'DesignerTestCase'
op|'('
name|'test'
op|'.'
name|'NoDBTestCase'
op|')'
op|':'
newline|'\n'
DECL|member|test_set_vif_bandwidth_config_no_extra_specs
indent|'    '
name|'def'
name|'test_set_vif_bandwidth_config_no_extra_specs'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
comment|'# Test whether test_set_vif_bandwidth_config_no_extra_specs fails when'
nl|'\n'
comment|"# its second parameter has no 'extra_specs' field."
nl|'\n'
nl|'\n'
indent|'        '
name|'try'
op|':'
newline|'\n'
comment|"# The conf will never be user be used, so we can use 'None'."
nl|'\n'
comment|'# An empty dictionary is fine: all that matters it that there is no'
nl|'\n'
comment|"# 'extra_specs' field."
nl|'\n'
indent|'            '
name|'designer'
op|'.'
name|'set_vif_bandwidth_config'
op|'('
name|'None'
op|','
op|'{'
op|'}'
op|')'
newline|'\n'
dedent|''
name|'except'
name|'KeyError'
name|'as'
name|'e'
op|':'
newline|'\n'
indent|'            '
name|'self'
op|'.'
name|'fail'
op|'('
string|"'KeyError: %s'"
op|'%'
name|'e'
op|')'
newline|'\n'
dedent|''
dedent|''
dedent|''
endmarker|''
end_unit
