begin_unit
comment|'# Copyright 2014 NEC Corporation.  All rights reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
DECL|variable|base_create
name|'base_create'
op|'='
op|'{'
nl|'\n'
string|"'type'"
op|':'
string|"'object'"
op|','
nl|'\n'
string|"'properties'"
op|':'
op|'{'
nl|'\n'
string|"'server'"
op|':'
op|'{'
nl|'\n'
string|"'type'"
op|':'
string|"'object'"
op|','
nl|'\n'
string|"'properties'"
op|':'
op|'{'
nl|'\n'
comment|'# TODO(oomichi): To focus the schema extension, now these'
nl|'\n'
comment|'# properties are not defined. After it, we need to define'
nl|'\n'
comment|'# them.'
nl|'\n'
comment|"# 'name': ..."
nl|'\n'
op|'}'
op|','
nl|'\n'
comment|'# TODO(oomichi): After all extension schema patches are merged,'
nl|'\n'
comment|'# this code should be enabled. If enabling before merger, API'
nl|'\n'
comment|'# extension parameters would be considered as bad parameters.'
nl|'\n'
comment|"# 'additionalProperties': False,"
nl|'\n'
op|'}'
op|','
nl|'\n'
op|'}'
op|','
nl|'\n'
string|"'required'"
op|':'
op|'['
string|"'server'"
op|']'
op|','
nl|'\n'
comment|'# TODO(oomichi): ditto, enable here after all extension schema'
nl|'\n'
comment|'# patches are merged.'
nl|'\n'
comment|"# 'additionalProperties': False,"
nl|'\n'
op|'}'
newline|'\n'
endmarker|''
end_unit
