begin_unit
comment|'#!/usr/bin/env python'
nl|'\n'
nl|'\n'
string|'"""Tool for checking if patch contains a regression test.\n\nPass in gerrit review number as parameter, tool will download branch and run\nmodified tests without bug fix.\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'string'
newline|'\n'
name|'import'
name|'subprocess'
newline|'\n'
name|'import'
name|'sys'
newline|'\n'
nl|'\n'
comment|'#TODO(jogo) use proper optParser'
nl|'\n'
DECL|variable|gerrit_number
name|'gerrit_number'
op|'='
name|'sys'
op|'.'
name|'argv'
op|'['
number|'1'
op|']'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|run
name|'def'
name|'run'
op|'('
name|'cmd'
op|','
name|'fail_ok'
op|'='
name|'False'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'print'
string|'"running: %s"'
op|'%'
name|'cmd'
newline|'\n'
name|'try'
op|':'
newline|'\n'
indent|'        '
name|'rval'
op|'='
name|'subprocess'
op|'.'
name|'check_output'
op|'('
name|'cmd'
op|','
name|'shell'
op|'='
name|'True'
op|')'
newline|'\n'
dedent|''
name|'except'
name|'subprocess'
op|'.'
name|'CalledProcessError'
op|':'
newline|'\n'
indent|'        '
name|'if'
name|'not'
name|'fail_ok'
op|':'
newline|'\n'
indent|'            '
name|'print'
string|'"the above command terminated with an error"'
newline|'\n'
name|'sys'
op|'.'
name|'exit'
op|'('
number|'1'
op|')'
newline|'\n'
dedent|''
name|'pass'
newline|'\n'
dedent|''
name|'return'
name|'rval'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|test_works
dedent|''
name|'test_works'
op|'='
name|'False'
newline|'\n'
nl|'\n'
DECL|variable|original_branch
name|'original_branch'
op|'='
name|'run'
op|'('
string|'"git rev-parse --abbrev-ref HEAD"'
op|')'
newline|'\n'
name|'run'
op|'('
string|'"git review -d %s"'
op|'%'
name|'gerrit_number'
op|')'
newline|'\n'
comment|'# run new tests with old code'
nl|'\n'
name|'run'
op|'('
string|'"git checkout HEAD^ nova"'
op|')'
newline|'\n'
name|'run'
op|'('
string|'"git checkout HEAD nova/tests"'
op|')'
newline|'\n'
nl|'\n'
comment|'# identify which tests have changed'
nl|'\n'
DECL|variable|tests
name|'tests'
op|'='
name|'run'
op|'('
string|'"git whatchanged --format=oneline -1 | grep \\"nova/tests\\" "'
nl|'\n'
string|'"| cut -f2"'
op|')'
op|'.'
name|'split'
op|'('
op|')'
newline|'\n'
DECL|variable|test_list
name|'test_list'
op|'='
op|'['
op|']'
newline|'\n'
name|'for'
name|'test'
name|'in'
name|'tests'
op|':'
newline|'\n'
indent|'    '
name|'test_list'
op|'.'
name|'append'
op|'('
name|'string'
op|'.'
name|'replace'
op|'('
name|'test'
op|'['
number|'0'
op|':'
op|'-'
number|'3'
op|']'
op|','
string|"'/'"
op|','
string|"'.'"
op|')'
op|')'
newline|'\n'
nl|'\n'
comment|'# run new tests, expect them to fail'
nl|'\n'
DECL|variable|expect_failure
dedent|''
name|'expect_failure'
op|'='
name|'run'
op|'('
op|'('
string|'"tox -epy27 %s 2>&1"'
op|'%'
name|'string'
op|'.'
name|'join'
op|'('
name|'test_list'
op|')'
op|')'
op|','
nl|'\n'
DECL|variable|fail_ok
name|'fail_ok'
op|'='
name|'True'
op|')'
newline|'\n'
name|'if'
string|'"FAILED (id="'
name|'in'
name|'expect_failure'
op|':'
newline|'\n'
DECL|variable|test_works
indent|'    '
name|'test_works'
op|'='
name|'True'
newline|'\n'
nl|'\n'
comment|'# cleanup'
nl|'\n'
dedent|''
name|'run'
op|'('
string|'"git checkout HEAD nova"'
op|')'
newline|'\n'
DECL|variable|new_branch
name|'new_branch'
op|'='
name|'run'
op|'('
string|'"git status | head -1 | cut -d \' \' -f 4"'
op|')'
newline|'\n'
name|'run'
op|'('
string|'"git checkout %s"'
op|'%'
name|'original_branch'
op|')'
newline|'\n'
name|'run'
op|'('
string|'"git branch -D %s"'
op|'%'
name|'new_branch'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
name|'if'
name|'test_works'
op|':'
newline|'\n'
indent|'    '
name|'print'
name|'expect_failure'
newline|'\n'
name|'print'
string|'""'
newline|'\n'
name|'print'
string|'"*******************************"'
newline|'\n'
name|'print'
string|'"SUCCESS: test covers regression"'
newline|'\n'
dedent|''
name|'else'
op|':'
newline|'\n'
indent|'    '
name|'print'
name|'expect_failure'
newline|'\n'
name|'print'
string|'""'
newline|'\n'
name|'print'
string|'"***************************************"'
newline|'\n'
name|'print'
string|'"FAILURE: test does not cover regression"'
newline|'\n'
name|'sys'
op|'.'
name|'exit'
op|'('
number|'1'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
