begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2011 Justin Santa Barbara'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'time'
newline|'\n'
name|'import'
name|'unittest'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
name|'import'
name|'flags'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'log'
name|'import'
name|'logging'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'tests'
op|'.'
name|'integrated'
name|'import'
name|'integrated_helpers'
newline|'\n'
name|'from'
name|'nova'
op|'.'
name|'tests'
op|'.'
name|'integrated'
op|'.'
name|'api'
name|'import'
name|'client'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|LOG
name|'LOG'
op|'='
name|'logging'
op|'.'
name|'getLogger'
op|'('
string|"'nova.tests.integrated'"
op|')'
newline|'\n'
nl|'\n'
DECL|variable|FLAGS
name|'FLAGS'
op|'='
name|'flags'
op|'.'
name|'FLAGS'
newline|'\n'
name|'FLAGS'
op|'.'
name|'verbose'
op|'='
name|'True'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|ServersTest
name|'class'
name|'ServersTest'
op|'('
name|'integrated_helpers'
op|'.'
name|'_IntegratedTestBase'
op|')'
op|':'
newline|'\n'
DECL|member|test_get_servers
indent|'    '
name|'def'
name|'test_get_servers'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Simple check that listing servers works."""'
newline|'\n'
name|'servers'
op|'='
name|'self'
op|'.'
name|'api'
op|'.'
name|'get_servers'
op|'('
op|')'
newline|'\n'
name|'for'
name|'server'
name|'in'
name|'servers'
op|':'
newline|'\n'
indent|'            '
name|'LOG'
op|'.'
name|'debug'
op|'('
string|'"server: %s"'
op|'%'
name|'server'
op|')'
newline|'\n'
nl|'\n'
DECL|member|test_create_and_delete_server
dedent|''
dedent|''
name|'def'
name|'test_create_and_delete_server'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Creates and deletes a server"""'
newline|'\n'
nl|'\n'
comment|'# Create server'
nl|'\n'
nl|'\n'
comment|'# Build the server data gradually, checking errors along the way'
nl|'\n'
name|'server'
op|'='
op|'{'
op|'}'
newline|'\n'
name|'good_server'
op|'='
name|'self'
op|'.'
name|'_build_minimal_create_server_request'
op|'('
op|')'
newline|'\n'
nl|'\n'
name|'post'
op|'='
op|'{'
string|"'server'"
op|':'
name|'server'
op|'}'
newline|'\n'
nl|'\n'
comment|'# Without an imageRef, this throws 500.'
nl|'\n'
comment|'# TODO(justinsb): Check whatever the spec says should be thrown here'
nl|'\n'
name|'self'
op|'.'
name|'assertRaises'
op|'('
name|'client'
op|'.'
name|'OpenStackApiException'
op|','
nl|'\n'
name|'self'
op|'.'
name|'api'
op|'.'
name|'post_server'
op|','
name|'post'
op|')'
newline|'\n'
nl|'\n'
comment|'# With an invalid imageRef, this throws 500.'
nl|'\n'
name|'server'
op|'['
string|"'imageRef'"
op|']'
op|'='
name|'self'
op|'.'
name|'user'
op|'.'
name|'get_invalid_image'
op|'('
op|')'
newline|'\n'
comment|'# TODO(justinsb): Check whatever the spec says should be thrown here'
nl|'\n'
name|'self'
op|'.'
name|'assertRaises'
op|'('
name|'client'
op|'.'
name|'OpenStackApiException'
op|','
nl|'\n'
name|'self'
op|'.'
name|'api'
op|'.'
name|'post_server'
op|','
name|'post'
op|')'
newline|'\n'
nl|'\n'
comment|'# Add a valid imageId/imageRef'
nl|'\n'
name|'server'
op|'['
string|"'imageId'"
op|']'
op|'='
name|'good_server'
op|'.'
name|'get'
op|'('
string|"'imageId'"
op|')'
newline|'\n'
name|'server'
op|'['
string|"'imageRef'"
op|']'
op|'='
name|'good_server'
op|'.'
name|'get'
op|'('
string|"'imageRef'"
op|')'
newline|'\n'
nl|'\n'
comment|'# Without flavorId, this throws 500'
nl|'\n'
comment|'# TODO(justinsb): Check whatever the spec says should be thrown here'
nl|'\n'
name|'self'
op|'.'
name|'assertRaises'
op|'('
name|'client'
op|'.'
name|'OpenStackApiException'
op|','
nl|'\n'
name|'self'
op|'.'
name|'api'
op|'.'
name|'post_server'
op|','
name|'post'
op|')'
newline|'\n'
nl|'\n'
comment|'# Set a valid flavorId/flavorRef'
nl|'\n'
name|'server'
op|'['
string|"'flavorRef'"
op|']'
op|'='
name|'good_server'
op|'.'
name|'get'
op|'('
string|"'flavorRef'"
op|')'
newline|'\n'
name|'server'
op|'['
string|"'flavorId'"
op|']'
op|'='
name|'good_server'
op|'.'
name|'get'
op|'('
string|"'flavorId'"
op|')'
newline|'\n'
nl|'\n'
comment|'# Without a name, this throws 500'
nl|'\n'
comment|'# TODO(justinsb): Check whatever the spec says should be thrown here'
nl|'\n'
name|'self'
op|'.'
name|'assertRaises'
op|'('
name|'client'
op|'.'
name|'OpenStackApiException'
op|','
nl|'\n'
name|'self'
op|'.'
name|'api'
op|'.'
name|'post_server'
op|','
name|'post'
op|')'
newline|'\n'
nl|'\n'
comment|'# Set a valid server name'
nl|'\n'
name|'server'
op|'['
string|"'name'"
op|']'
op|'='
name|'good_server'
op|'['
string|"'name'"
op|']'
newline|'\n'
nl|'\n'
name|'created_server'
op|'='
name|'self'
op|'.'
name|'api'
op|'.'
name|'post_server'
op|'('
name|'post'
op|')'
newline|'\n'
name|'LOG'
op|'.'
name|'debug'
op|'('
string|'"created_server: %s"'
op|'%'
name|'created_server'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'assertTrue'
op|'('
name|'created_server'
op|'['
string|"'id'"
op|']'
op|')'
newline|'\n'
name|'created_server_id'
op|'='
name|'created_server'
op|'['
string|"'id'"
op|']'
newline|'\n'
nl|'\n'
comment|"# Check it's there"
nl|'\n'
name|'found_server'
op|'='
name|'self'
op|'.'
name|'api'
op|'.'
name|'get_server'
op|'('
name|'created_server_id'
op|')'
newline|'\n'
name|'self'
op|'.'
name|'assertEqual'
op|'('
name|'created_server_id'
op|','
name|'found_server'
op|'['
string|"'id'"
op|']'
op|')'
newline|'\n'
nl|'\n'
comment|'# It should also be in the all-servers list'
nl|'\n'
name|'servers'
op|'='
name|'self'
op|'.'
name|'api'
op|'.'
name|'get_servers'
op|'('
op|')'
newline|'\n'
name|'server_ids'
op|'='
op|'['
name|'server'
op|'['
string|"'id'"
op|']'
name|'for'
name|'server'
name|'in'
name|'servers'
op|']'
newline|'\n'
name|'self'
op|'.'
name|'assertTrue'
op|'('
name|'created_server_id'
name|'in'
name|'server_ids'
op|')'
newline|'\n'
nl|'\n'
comment|'# Wait (briefly) for creation'
nl|'\n'
name|'retries'
op|'='
number|'0'
newline|'\n'
name|'while'
name|'found_server'
op|'['
string|"'status'"
op|']'
op|'=='
string|"'build'"
op|':'
newline|'\n'
indent|'            '
name|'LOG'
op|'.'
name|'debug'
op|'('
string|'"found server: %s"'
op|'%'
name|'found_server'
op|')'
newline|'\n'
name|'time'
op|'.'
name|'sleep'
op|'('
number|'1'
op|')'
newline|'\n'
name|'found_server'
op|'='
name|'self'
op|'.'
name|'api'
op|'.'
name|'get_server'
op|'('
name|'created_server_id'
op|')'
newline|'\n'
name|'retries'
op|'='
name|'retries'
op|'+'
number|'1'
newline|'\n'
name|'if'
name|'retries'
op|'>'
number|'5'
op|':'
newline|'\n'
indent|'                '
name|'break'
newline|'\n'
nl|'\n'
comment|'# It should be available...'
nl|'\n'
comment|"# TODO(justinsb): Mock doesn't yet do this..."
nl|'\n'
comment|"#self.assertEqual('available', found_server['status'])"
nl|'\n'
nl|'\n'
dedent|''
dedent|''
name|'self'
op|'.'
name|'_delete_server'
op|'('
name|'created_server_id'
op|')'
newline|'\n'
nl|'\n'
DECL|member|_delete_server
dedent|''
name|'def'
name|'_delete_server'
op|'('
name|'self'
op|','
name|'server_id'
op|')'
op|':'
newline|'\n'
comment|'# Delete the server'
nl|'\n'
indent|'        '
name|'self'
op|'.'
name|'api'
op|'.'
name|'delete_server'
op|'('
name|'server_id'
op|')'
newline|'\n'
nl|'\n'
comment|'# Wait (briefly) for deletion'
nl|'\n'
name|'for'
name|'_retries'
name|'in'
name|'range'
op|'('
number|'5'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'try'
op|':'
newline|'\n'
indent|'                '
name|'found_server'
op|'='
name|'self'
op|'.'
name|'api'
op|'.'
name|'get_server'
op|'('
name|'server_id'
op|')'
newline|'\n'
dedent|''
name|'except'
name|'client'
op|'.'
name|'OpenStackApiNotFoundException'
op|':'
newline|'\n'
indent|'                '
name|'found_server'
op|'='
name|'None'
newline|'\n'
name|'LOG'
op|'.'
name|'debug'
op|'('
string|'"Got 404, proceeding"'
op|')'
newline|'\n'
name|'break'
newline|'\n'
nl|'\n'
dedent|''
name|'LOG'
op|'.'
name|'debug'
op|'('
string|'"Found_server=%s"'
op|'%'
name|'found_server'
op|')'
newline|'\n'
nl|'\n'
comment|"# TODO(justinsb): Mock doesn't yet do accurate state changes"
nl|'\n'
comment|"#if found_server['status'] != 'deleting':"
nl|'\n'
comment|'#    break'
nl|'\n'
name|'time'
op|'.'
name|'sleep'
op|'('
number|'1'
op|')'
newline|'\n'
nl|'\n'
comment|'# Should be gone'
nl|'\n'
dedent|''
name|'self'
op|'.'
name|'assertFalse'
op|'('
name|'found_server'
op|')'
newline|'\n'
nl|'\n'
comment|'# TODO(justinsb): Enable this unit test when the metadata bug is fixed'
nl|'\n'
comment|'#    def test_create_server_with_metadata(self):'
nl|'\n'
comment|'#        """Creates a server with metadata"""'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#        # Build the server data gradually, checking errors along the way'
nl|'\n'
comment|'#        server = self._build_minimal_create_server_request()'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#        for metadata_count in range(30):'
nl|'\n'
comment|'#            metadata = {}'
nl|'\n'
comment|'#            for i in range(metadata_count):'
nl|'\n'
comment|"#                metadata['key_%s' % i] = 'value_%s' % i"
nl|'\n'
comment|"#            server['metadata'] = metadata"
nl|'\n'
comment|'#'
nl|'\n'
comment|"#            post = {'server': server}"
nl|'\n'
comment|'#            created_server = self.api.post_server(post)'
nl|'\n'
comment|'#            LOG.debug("created_server: %s" % created_server)'
nl|'\n'
comment|"#            self.assertTrue(created_server['id'])"
nl|'\n'
comment|"#            created_server_id = created_server['id']"
nl|'\n'
comment|'#            # Reenable when bug fixed'
nl|'\n'
comment|"#            # self.assertEqual(metadata, created_server.get('metadata'))"
nl|'\n'
comment|'#'
nl|'\n'
comment|"#            # Check it's there"
nl|'\n'
comment|'#            found_server = self.api.get_server(created_server_id)'
nl|'\n'
comment|"#            self.assertEqual(created_server_id, found_server['id'])"
nl|'\n'
comment|"#            self.assertEqual(metadata, found_server.get('metadata'))"
nl|'\n'
comment|'#'
nl|'\n'
comment|'#            # The server should also be in the all-servers details list'
nl|'\n'
comment|'#            servers = self.api.get_servers(detail=True)'
nl|'\n'
comment|"#            server_map = dict((server['id'], server) for server in servers)"
nl|'\n'
comment|'#            found_server = server_map.get(created_server_id)'
nl|'\n'
comment|'#            self.assertTrue(found_server)'
nl|'\n'
comment|'#            # Details do include metadata'
nl|'\n'
comment|"#            self.assertEqual(metadata, found_server.get('metadata'))"
nl|'\n'
comment|'#'
nl|'\n'
comment|'#            # The server should also be in the all-servers summary list'
nl|'\n'
comment|'#            servers = self.api.get_servers(detail=False)'
nl|'\n'
comment|"#            server_map = dict((server['id'], server) for server in servers)"
nl|'\n'
comment|'#            found_server = server_map.get(created_server_id)'
nl|'\n'
comment|'#            self.assertTrue(found_server)'
nl|'\n'
comment|'#            # Summary should not include metadata'
nl|'\n'
comment|"#            self.assertFalse(found_server.get('metadata'))"
nl|'\n'
comment|'#'
nl|'\n'
comment|'#            # Cleanup'
nl|'\n'
comment|'#            self._delete_server(created_server_id)'
nl|'\n'
nl|'\n'
nl|'\n'
dedent|''
dedent|''
name|'if'
name|'__name__'
op|'=='
string|'"__main__"'
op|':'
newline|'\n'
indent|'    '
name|'unittest'
op|'.'
name|'main'
op|'('
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
