begin_unit
comment|'# Copyright [2010] [Anso Labs, LLC]'
nl|'\n'
comment|'# '
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License");'
nl|'\n'
comment|'#    you may not use this file except in compliance with the License.'
nl|'\n'
comment|'#    You may obtain a copy of the License at'
nl|'\n'
comment|'# '
nl|'\n'
comment|'#        http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'# '
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS,'
nl|'\n'
comment|'#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
nl|'\n'
comment|'#    See the License for the specific language governing permissions and'
nl|'\n'
comment|'#    limitations under the License.'
nl|'\n'
nl|'\n'
string|'"""\nSimple base set of RBAC rules which map API endpoints to LDAP groups.\nFor testing accounts, users will always have PM privileges.\n"""'
newline|'\n'
nl|'\n'
nl|'\n'
comment|'# This is logically a RuleSet or some such.'
nl|'\n'
nl|'\n'
DECL|function|allow_describe_images
name|'def'
name|'allow_describe_images'
op|'('
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'True'
newline|'\n'
nl|'\n'
DECL|function|allow_describe_instances
dedent|''
name|'def'
name|'allow_describe_instances'
op|'('
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'True'
newline|'\n'
nl|'\n'
DECL|function|allow_describe_addresses
dedent|''
name|'def'
name|'allow_describe_addresses'
op|'('
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'True'
newline|'\n'
nl|'\n'
DECL|function|allow_run_instances
dedent|''
name|'def'
name|'allow_run_instances'
op|'('
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
op|':'
newline|'\n'
comment|'# target_object is a reservation, not an instance'
nl|'\n'
comment|'# it needs to include count, type, image, etc.'
nl|'\n'
nl|'\n'
comment|'# First, is the project allowed to use this image'
nl|'\n'
nl|'\n'
comment|'# Second, is this user allowed to launch within this project'
nl|'\n'
nl|'\n'
comment|'# Third, is the count or type within project quota'
nl|'\n'
nl|'\n'
indent|'    '
name|'return'
name|'True'
newline|'\n'
nl|'\n'
DECL|function|allow_terminate_instances
dedent|''
name|'def'
name|'allow_terminate_instances'
op|'('
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
op|':'
newline|'\n'
comment|'# In a project, the PMs and Sysadmins can terminate'
nl|'\n'
indent|'    '
name|'return'
name|'True'
newline|'\n'
nl|'\n'
DECL|function|allow_get_console_output
dedent|''
name|'def'
name|'allow_get_console_output'
op|'('
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
op|':'
newline|'\n'
comment|'# If the user launched the instance, '
nl|'\n'
comment|'# Or is a sysadmin in the project, '
nl|'\n'
indent|'    '
name|'return'
name|'True'
newline|'\n'
nl|'\n'
DECL|function|allow_allocate_address
dedent|''
name|'def'
name|'allow_allocate_address'
op|'('
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
op|':'
newline|'\n'
comment|"# There's no security concern in allocation, "
nl|'\n'
comment|'# but it can get expensive. Limit to PM and NE.'
nl|'\n'
indent|'    '
name|'return'
name|'True'
newline|'\n'
nl|'\n'
DECL|function|allow_associate_address
dedent|''
name|'def'
name|'allow_associate_address'
op|'('
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
op|':'
newline|'\n'
comment|'# project NE only'
nl|'\n'
comment|'# In future, will perform a CloudAudit scan first'
nl|'\n'
comment|'# (Pass / Fail gate)'
nl|'\n'
indent|'    '
name|'return'
name|'True'
newline|'\n'
nl|'\n'
DECL|function|allow_register
dedent|''
name|'def'
name|'allow_register'
op|'('
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'False'
newline|'\n'
nl|'\n'
DECL|function|is_allowed
dedent|''
name|'def'
name|'is_allowed'
op|'('
name|'action'
op|','
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'return'
name|'globals'
op|'('
op|')'
op|'['
string|"'allow_%s'"
op|'%'
name|'action'
op|']'
op|'('
name|'user'
op|','
name|'project'
op|','
name|'target_object'
op|')'
newline|'\n'
nl|'\n'
dedent|''
endmarker|''
end_unit
