begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright 2011 NTT DATA CORPORATION.'
nl|'\n'
comment|'# Copyright 2011 OpenStack LLC.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\nAuth module specific utilities and helper functions.\n"""'
newline|'\n'
nl|'\n'
name|'import'
name|'netaddr'
newline|'\n'
name|'import'
name|'string'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|get_host_only_server_string
name|'def'
name|'get_host_only_server_string'
op|'('
name|'server_str'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""\n    Returns host part only of the given server_string if it\'s a combination\n    of host part and port. Otherwise, return null string.\n    """'
newline|'\n'
nl|'\n'
comment|'# First of all, exclude pure IPv6 address (w/o port).'
nl|'\n'
name|'if'
name|'netaddr'
op|'.'
name|'valid_ipv6'
op|'('
name|'server_str'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'return'
string|"''"
newline|'\n'
nl|'\n'
comment|'# Next, check if this is IPv6 address with port number combination.'
nl|'\n'
dedent|''
name|'if'
name|'server_str'
op|'.'
name|'find'
op|'('
string|'"]:"'
op|')'
op|'!='
op|'-'
number|'1'
op|':'
newline|'\n'
indent|'        '
op|'['
name|'address'
op|','
name|'sep'
op|','
name|'port'
op|']'
op|'='
name|'server_str'
op|'.'
name|'replace'
op|'('
string|"'['"
op|','
string|"''"
op|','
number|'1'
op|')'
op|'.'
name|'partition'
op|'('
string|"']:'"
op|')'
newline|'\n'
name|'return'
name|'address'
newline|'\n'
nl|'\n'
comment|'# Third, check if this is a combination of general address and port'
nl|'\n'
dedent|''
name|'if'
name|'server_str'
op|'.'
name|'find'
op|'('
string|"':'"
op|')'
op|'=='
op|'-'
number|'1'
op|':'
newline|'\n'
indent|'        '
name|'return'
string|"''"
newline|'\n'
nl|'\n'
comment|'# This must be a combination of host part and port'
nl|'\n'
dedent|''
op|'('
name|'address'
op|','
name|'port'
op|')'
op|'='
name|'server_str'
op|'.'
name|'split'
op|'('
string|"':'"
op|')'
newline|'\n'
name|'return'
name|'address'
newline|'\n'
dedent|''
endmarker|''
end_unit
