begin_unit
comment|'# Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'# not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'# a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#      http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'# Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'# License for the specific language governing permissions and limitations'
nl|'\n'
comment|'# under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'testtools'
newline|'\n'
nl|'\n'
name|'from'
name|'oslo_utils'
name|'import'
name|'uuidutils'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'tests'
name|'import'
name|'uuidsentinel'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|TestUUIDSentinels
name|'class'
name|'TestUUIDSentinels'
op|'('
name|'testtools'
op|'.'
name|'TestCase'
op|')'
op|':'
newline|'\n'
DECL|member|test_different_sentinel
indent|'    '
name|'def'
name|'test_different_sentinel'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'uuid1'
op|'='
name|'uuidsentinel'
op|'.'
name|'foobar'
newline|'\n'
name|'uuid2'
op|'='
name|'uuidsentinel'
op|'.'
name|'barfoo'
newline|'\n'
name|'self'
op|'.'
name|'assertNotEqual'
op|'('
name|'uuid1'
op|','
name|'uuid2'
op|')'
newline|'\n'
nl|'\n'
DECL|member|test_returns_uuid
dedent|''
name|'def'
name|'test_returns_uuid'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'assertTrue'
op|'('
name|'uuidutils'
op|'.'
name|'is_uuid_like'
op|'('
name|'uuidsentinel'
op|'.'
name|'foo'
op|')'
op|')'
newline|'\n'
nl|'\n'
DECL|member|test_returns_string
dedent|''
name|'def'
name|'test_returns_string'
op|'('
name|'self'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'self'
op|'.'
name|'assertIsInstance'
op|'('
name|'uuidsentinel'
op|'.'
name|'foo'
op|','
name|'str'
op|')'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
