begin_unit
comment|'# vim: tabstop=4 shiftwidth=4 softtabstop=4'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2010 Citrix Systems, Inc.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""\n:mod:`xenapi` -- Nova support for XenServer and XCP through XenAPI\n==================================================================\n"""'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|HelperBase
name|'class'
name|'HelperBase'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""\n    The base for helper classes.\n    """'
newline|'\n'
op|'@'
name|'classmethod'
newline|'\n'
DECL|member|get_rec
name|'def'
name|'get_rec'
op|'('
name|'cls'
op|','
name|'session'
op|','
name|'record_type'
op|','
name|'ref'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'try'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'session'
op|'.'
name|'call_xenapi'
op|'('
string|"'%s.get_record'"
op|'%'
name|'record_type'
op|','
name|'ref'
op|')'
newline|'\n'
dedent|''
name|'except'
name|'session'
op|'.'
name|'XenAPI'
op|'.'
name|'Failure'
op|','
name|'e'
op|':'
newline|'\n'
indent|'            '
name|'if'
name|'e'
op|'.'
name|'details'
op|'['
number|'0'
op|']'
op|'!='
string|"'HANDLE_INVALID'"
op|':'
newline|'\n'
indent|'                '
name|'raise'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
name|'return'
name|'None'
newline|'\n'
nl|'\n'
dedent|''
op|'@'
name|'classmethod'
newline|'\n'
DECL|member|get_all_refs_and_recs
name|'def'
name|'get_all_refs_and_recs'
op|'('
name|'cls'
op|','
name|'session'
op|','
name|'record_type'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Retrieve all refs and recs for a Xen record type.\n\n        Handles race-conditions where the record may be deleted between\n        the `get_all` call and the `get_record` call.\n        """'
newline|'\n'
nl|'\n'
name|'for'
name|'ref'
name|'in'
name|'session'
op|'.'
name|'call_xenapi'
op|'('
string|"'%s.get_all'"
op|'%'
name|'record_type'
op|')'
op|':'
newline|'\n'
indent|'            '
name|'rec'
op|'='
name|'cls'
op|'.'
name|'get_rec'
op|'('
name|'session'
op|','
name|'record_type'
op|','
name|'ref'
op|')'
newline|'\n'
comment|'# Check to make sure the record still exists. It may have'
nl|'\n'
comment|'# been deleted between the get_all call and get_record call'
nl|'\n'
name|'if'
name|'rec'
op|':'
newline|'\n'
indent|'                '
name|'yield'
name|'ref'
op|','
name|'rec'
newline|'\n'
dedent|''
dedent|''
dedent|''
dedent|''
endmarker|''
end_unit
