begin_unit
comment|'# Copyright (c) 2011 Openstack, LLC.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'import'
name|'logging'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'scheduler'
op|'.'
name|'filters'
name|'import'
name|'abstract_filter'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|LOG
name|'LOG'
op|'='
name|'logging'
op|'.'
name|'getLogger'
op|'('
string|"'nova.scheduler.filter.instance_type_filter'"
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|InstanceTypeFilter
name|'class'
name|'InstanceTypeFilter'
op|'('
name|'abstract_filter'
op|'.'
name|'AbstractHostFilter'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""HostFilter hard-coded to work with InstanceType records."""'
newline|'\n'
DECL|member|instance_type_to_filter
name|'def'
name|'instance_type_to_filter'
op|'('
name|'self'
op|','
name|'instance_type'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Use instance_type to filter hosts."""'
newline|'\n'
name|'return'
name|'instance_type'
newline|'\n'
nl|'\n'
DECL|member|_satisfies_extra_specs
dedent|''
name|'def'
name|'_satisfies_extra_specs'
op|'('
name|'self'
op|','
name|'capabilities'
op|','
name|'instance_type'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Check that the capabilities provided by the compute service\n        satisfy the extra specs associated with the instance type"""'
newline|'\n'
name|'if'
string|"'extra_specs'"
name|'not'
name|'in'
name|'instance_type'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'True'
newline|'\n'
nl|'\n'
comment|'# NOTE(lorinh): For now, we are just checking exact matching on the'
nl|'\n'
comment|'# values. Later on, we want to handle numerical'
nl|'\n'
comment|'# values so we can represent things like number of GPU cards'
nl|'\n'
dedent|''
name|'try'
op|':'
newline|'\n'
indent|'            '
name|'for'
name|'key'
op|','
name|'value'
name|'in'
name|'instance_type'
op|'['
string|"'extra_specs'"
op|']'
op|'.'
name|'iteritems'
op|'('
op|')'
op|':'
newline|'\n'
indent|'                '
name|'if'
name|'capabilities'
op|'['
name|'key'
op|']'
op|'!='
name|'value'
op|':'
newline|'\n'
indent|'                    '
name|'return'
name|'False'
newline|'\n'
dedent|''
dedent|''
dedent|''
name|'except'
name|'KeyError'
op|','
name|'e'
op|':'
newline|'\n'
indent|'            '
name|'return'
name|'False'
newline|'\n'
dedent|''
name|'return'
name|'True'
newline|'\n'
nl|'\n'
DECL|member|_basic_ram_filter
dedent|''
name|'def'
name|'_basic_ram_filter'
op|'('
name|'self'
op|','
name|'host_name'
op|','
name|'host_info'
op|','
name|'instance_type'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Only return hosts with sufficient available RAM."""'
newline|'\n'
name|'requested_ram'
op|'='
name|'instance_type'
op|'['
string|"'memory_mb'"
op|']'
newline|'\n'
name|'free_ram_mb'
op|'='
name|'host_info'
op|'.'
name|'free_ram_mb'
newline|'\n'
name|'return'
name|'free_ram_mb'
op|'>='
name|'requested_ram'
newline|'\n'
nl|'\n'
DECL|member|filter_hosts
dedent|''
name|'def'
name|'filter_hosts'
op|'('
name|'self'
op|','
name|'host_list'
op|','
name|'query'
op|','
name|'options'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Return a list of hosts that can create instance_type."""'
newline|'\n'
name|'instance_type'
op|'='
name|'query'
newline|'\n'
name|'selected_hosts'
op|'='
op|'['
op|']'
newline|'\n'
name|'for'
name|'hostname'
op|','
name|'host_info'
name|'in'
name|'host_list'
op|':'
newline|'\n'
indent|'            '
name|'if'
name|'not'
name|'self'
op|'.'
name|'_basic_ram_filter'
op|'('
name|'hostname'
op|','
name|'host_info'
op|','
nl|'\n'
name|'instance_type'
op|')'
op|':'
newline|'\n'
indent|'                '
name|'continue'
newline|'\n'
dedent|''
name|'capabilities'
op|'='
name|'host_info'
op|'.'
name|'compute'
newline|'\n'
name|'if'
name|'capabilities'
op|':'
newline|'\n'
indent|'                '
name|'if'
name|'not'
name|'capabilities'
op|'.'
name|'get'
op|'('
string|'"enabled"'
op|','
name|'True'
op|')'
op|':'
newline|'\n'
indent|'                    '
name|'continue'
newline|'\n'
dedent|''
name|'if'
name|'not'
name|'self'
op|'.'
name|'_satisfies_extra_specs'
op|'('
name|'capabilities'
op|','
nl|'\n'
name|'instance_type'
op|')'
op|':'
newline|'\n'
indent|'                    '
name|'continue'
newline|'\n'
nl|'\n'
dedent|''
dedent|''
name|'selected_hosts'
op|'.'
name|'append'
op|'('
op|'('
name|'hostname'
op|','
name|'host_info'
op|')'
op|')'
newline|'\n'
dedent|''
name|'return'
name|'selected_hosts'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
