begin_unit
comment|'# Copyright (c) 2011-2012 Openstack, LLC.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
nl|'\n'
name|'import'
name|'abstract_filter'
newline|'\n'
name|'from'
name|'nova'
name|'import'
name|'flags'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|variable|FLAGS
name|'FLAGS'
op|'='
name|'flags'
op|'.'
name|'FLAGS'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|IsolatedHostsFilter
name|'class'
name|'IsolatedHostsFilter'
op|'('
name|'abstract_filter'
op|'.'
name|'AbstractHostFilter'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Returns host."""'
newline|'\n'
nl|'\n'
DECL|member|host_passes
name|'def'
name|'host_passes'
op|'('
name|'self'
op|','
name|'host_state'
op|','
name|'filter_properties'
op|')'
op|':'
newline|'\n'
indent|'        '
name|'spec'
op|'='
name|'filter_properties'
op|'.'
name|'get'
op|'('
string|"'request_spec'"
op|','
op|'{'
op|'}'
op|')'
newline|'\n'
name|'props'
op|'='
name|'spec'
op|'.'
name|'get'
op|'('
string|"'instance_properties'"
op|','
op|'{'
op|'}'
op|')'
newline|'\n'
name|'image_ref'
op|'='
name|'props'
op|'.'
name|'get'
op|'('
string|"'image_ref'"
op|')'
newline|'\n'
name|'image_isolated'
op|'='
name|'image_ref'
name|'in'
name|'FLAGS'
op|'.'
name|'isolated_images'
newline|'\n'
name|'host_isolated'
op|'='
name|'host_state'
op|'.'
name|'host'
name|'in'
name|'FLAGS'
op|'.'
name|'isolated_hosts'
newline|'\n'
name|'return'
name|'image_isolated'
op|'=='
name|'host_isolated'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
