begin_unit
comment|'# Copyright (c) 2011-2012 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo'
op|'.'
name|'config'
name|'import'
name|'cfg'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'scheduler'
name|'import'
name|'filters'
newline|'\n'
nl|'\n'
DECL|variable|isolated_opts
name|'isolated_opts'
op|'='
op|'['
nl|'\n'
name|'cfg'
op|'.'
name|'ListOpt'
op|'('
string|"'isolated_images'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
op|'['
op|']'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Images to run on isolated host'"
op|')'
op|','
nl|'\n'
name|'cfg'
op|'.'
name|'ListOpt'
op|'('
string|"'isolated_hosts'"
op|','
nl|'\n'
DECL|variable|default
name|'default'
op|'='
op|'['
op|']'
op|','
nl|'\n'
DECL|variable|help
name|'help'
op|'='
string|"'Host reserved for specific images'"
op|')'
op|','
nl|'\n'
op|']'
newline|'\n'
DECL|variable|CONF
name|'CONF'
op|'='
name|'cfg'
op|'.'
name|'CONF'
newline|'\n'
name|'CONF'
op|'.'
name|'register_opts'
op|'('
name|'isolated_opts'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|IsolatedHostsFilter
name|'class'
name|'IsolatedHostsFilter'
op|'('
name|'filters'
op|'.'
name|'BaseHostFilter'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Returns host."""'
newline|'\n'
nl|'\n'
DECL|member|host_passes
name|'def'
name|'host_passes'
op|'('
name|'self'
op|','
name|'host_state'
op|','
name|'filter_properties'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""\n        Result Matrix:\n                     | isolated_image | non_isolated_image\n        -------------+----------------+-------------------\n        iso_host     |    True        |     False\n        non_iso_host |    False       |      True\n\n        """'
newline|'\n'
comment|'# If the configuration does not list any hosts, the filter will always'
nl|'\n'
comment|'# return True, assuming a configuration error, so letting all hosts'
nl|'\n'
comment|'# through.'
nl|'\n'
name|'isolated_hosts'
op|'='
name|'CONF'
op|'.'
name|'isolated_hosts'
newline|'\n'
name|'isolated_images'
op|'='
name|'CONF'
op|'.'
name|'isolated_images'
newline|'\n'
name|'if'
name|'not'
name|'isolated_images'
op|':'
newline|'\n'
comment|'# As there are no images to match, return False if the host is in'
nl|'\n'
comment|'# the isolation list'
nl|'\n'
indent|'            '
name|'return'
name|'host_state'
op|'.'
name|'host'
name|'not'
name|'in'
name|'isolated_hosts'
newline|'\n'
nl|'\n'
dedent|''
name|'spec'
op|'='
name|'filter_properties'
op|'.'
name|'get'
op|'('
string|"'request_spec'"
op|','
op|'{'
op|'}'
op|')'
newline|'\n'
name|'props'
op|'='
name|'spec'
op|'.'
name|'get'
op|'('
string|"'instance_properties'"
op|','
op|'{'
op|'}'
op|')'
newline|'\n'
name|'image_ref'
op|'='
name|'props'
op|'.'
name|'get'
op|'('
string|"'image_ref'"
op|')'
newline|'\n'
name|'image_isolated'
op|'='
name|'image_ref'
name|'in'
name|'isolated_images'
newline|'\n'
name|'host_isolated'
op|'='
name|'host_state'
op|'.'
name|'host'
name|'in'
name|'isolated_hosts'
newline|'\n'
name|'return'
name|'image_isolated'
op|'=='
name|'host_isolated'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
