begin_unit
comment|'# Copyright (c) 2012 OpenStack Foundation'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
name|'from'
name|'oslo_log'
name|'import'
name|'log'
name|'as'
name|'logging'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'scheduler'
name|'import'
name|'filters'
newline|'\n'
nl|'\n'
DECL|variable|LOG
name|'LOG'
op|'='
name|'logging'
op|'.'
name|'getLogger'
op|'('
name|'__name__'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|class|RetryFilter
name|'class'
name|'RetryFilter'
op|'('
name|'filters'
op|'.'
name|'BaseHostFilter'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Filter out nodes that have already been attempted for scheduling\n    purposes\n    """'
newline|'\n'
nl|'\n'
DECL|member|host_passes
name|'def'
name|'host_passes'
op|'('
name|'self'
op|','
name|'host_state'
op|','
name|'spec_obj'
op|')'
op|':'
newline|'\n'
indent|'        '
string|'"""Skip nodes that have already been attempted."""'
newline|'\n'
name|'retry'
op|'='
name|'spec_obj'
op|'.'
name|'retry'
newline|'\n'
name|'if'
name|'not'
name|'retry'
op|':'
newline|'\n'
comment|'# Re-scheduling is disabled'
nl|'\n'
indent|'            '
name|'LOG'
op|'.'
name|'debug'
op|'('
string|'"Re-scheduling is disabled"'
op|')'
newline|'\n'
name|'return'
name|'True'
newline|'\n'
nl|'\n'
comment|'# TODO(sbauza): Once the HostState is actually a ComputeNode, we could'
nl|'\n'
comment|'# easily get this one...'
nl|'\n'
dedent|''
name|'host'
op|'='
op|'['
name|'host_state'
op|'.'
name|'host'
op|','
name|'host_state'
op|'.'
name|'nodename'
op|']'
newline|'\n'
comment|"# TODO(sbauza)... and we wouldn't need to primitive the hosts into"
nl|'\n'
comment|'# lists'
nl|'\n'
name|'hosts'
op|'='
op|'['
op|'['
name|'cn'
op|'.'
name|'host'
op|','
name|'cn'
op|'.'
name|'hypervisor_hostname'
op|']'
name|'for'
name|'cn'
name|'in'
name|'retry'
op|'.'
name|'hosts'
op|']'
newline|'\n'
nl|'\n'
name|'passes'
op|'='
name|'host'
name|'not'
name|'in'
name|'hosts'
newline|'\n'
nl|'\n'
name|'if'
name|'not'
name|'passes'
op|':'
newline|'\n'
indent|'            '
name|'LOG'
op|'.'
name|'debug'
op|'('
string|'"Host %(host)s fails.  Previously tried hosts: "'
nl|'\n'
string|'"%(hosts)s"'
op|','
op|'{'
string|"'host'"
op|':'
name|'host'
op|','
string|"'hosts'"
op|':'
name|'hosts'
op|'}'
op|')'
newline|'\n'
nl|'\n'
comment|"# Host passes if it's not in the list of previously attempted hosts:"
nl|'\n'
dedent|''
name|'return'
name|'passes'
newline|'\n'
dedent|''
dedent|''
endmarker|''
end_unit
