begin_unit
comment|'# Copyright 2010 United States Government as represented by the'
nl|'\n'
comment|'# Administrator of the National Aeronautics and Space Administration.'
nl|'\n'
comment|'# All Rights Reserved.'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Licensed under the Apache License, Version 2.0 (the "License"); you may'
nl|'\n'
comment|'#    not use this file except in compliance with the License. You may obtain'
nl|'\n'
comment|'#    a copy of the License at'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#         http://www.apache.org/licenses/LICENSE-2.0'
nl|'\n'
comment|'#'
nl|'\n'
comment|'#    Unless required by applicable law or agreed to in writing, software'
nl|'\n'
comment|'#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT'
nl|'\n'
comment|'#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the'
nl|'\n'
comment|'#    License for the specific language governing permissions and limitations'
nl|'\n'
comment|'#    under the License.'
nl|'\n'
nl|'\n'
string|'"""Database setup and migration commands."""'
newline|'\n'
nl|'\n'
name|'from'
name|'nova'
op|'.'
name|'db'
op|'.'
name|'sqlalchemy'
name|'import'
name|'migration'
newline|'\n'
nl|'\n'
DECL|variable|IMPL
name|'IMPL'
op|'='
name|'migration'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|db_sync
name|'def'
name|'db_sync'
op|'('
name|'version'
op|'='
name|'None'
op|','
name|'database'
op|'='
string|"'main'"
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Migrate the database to `version` or the most recent version."""'
newline|'\n'
name|'return'
name|'IMPL'
op|'.'
name|'db_sync'
op|'('
name|'version'
op|'='
name|'version'
op|','
name|'database'
op|'='
name|'database'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|db_version
dedent|''
name|'def'
name|'db_version'
op|'('
name|'database'
op|'='
string|"'main'"
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Display the current database version."""'
newline|'\n'
name|'return'
name|'IMPL'
op|'.'
name|'db_version'
op|'('
name|'database'
op|'='
name|'database'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|db_initial_version
dedent|''
name|'def'
name|'db_initial_version'
op|'('
name|'database'
op|'='
string|"'main'"
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""The starting version for the database."""'
newline|'\n'
name|'return'
name|'IMPL'
op|'.'
name|'db_initial_version'
op|'('
name|'database'
op|'='
name|'database'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
DECL|function|db_null_instance_uuid_scan
dedent|''
name|'def'
name|'db_null_instance_uuid_scan'
op|'('
name|'delete'
op|'='
name|'False'
op|')'
op|':'
newline|'\n'
indent|'    '
string|'"""Utility for scanning the database to look for NULL instance uuid rows.\n\n    Scans the backing nova database to look for table entries where\n    instances.uuid or instance_uuid columns are NULL (except for the\n    fixed_ips table since that can contain NULL instance_uuid entries by\n    design). Dumps the tables that have NULL instance_uuid entries or\n    optionally deletes them based on usage.\n\n    This tool is meant to be used in conjunction with the 267 database\n    migration script to detect and optionally cleanup NULL instance_uuid\n    records.\n\n    :param delete: If true, delete NULL instance_uuid records found, else\n                   just query to see if they exist for reporting.\n    :returns: dict of table name to number of hits for NULL instance_uuid rows.\n    """'
newline|'\n'
name|'return'
name|'IMPL'
op|'.'
name|'db_null_instance_uuid_scan'
op|'('
name|'delete'
op|'='
name|'delete'
op|')'
newline|'\n'
dedent|''
endmarker|''
end_unit
